### ISSUE TITLE
Adding hazmat for trucks (Vehicle parameters)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#10974]
# Review
- [x]  "A" is missing in "No restriction" line
- [x] Option doesn't work, tested on the tunnel https://www.openstreetmap.org/way/253770361#map=15/52.4583/13.4260

# ToDo
Adding hazmat for trucks (Vehicle parameters). https://taginfo.openstreetmap.org/keys/hazmat#overview

## Android, [Figma](https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?node-id=2227%3A76291)
- [x]  Add access to the options thru Navigation –> Options
- [x] Rename to `Transporting of hazardous materials`
- [x] Show selected category on the second line.
- [x]  Icon:
• No – ic_action_hazmat_limit
• Yes – ic_action_hazmat_limit_colored
- [x]  By default **Transporting of hazardous materials** should be set to **No**
- [x] **A (No restrictions)** is default option, after selecting **Yes**
 
<table style="width:100%">
  <tr>
    <th>In list</th>
    <th>No</th>
    <th>Yes</th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/169524656-0dd4f28f-a97c-4df4-a01d-359e7cd582fb.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/169546441-e79c80ce-cf2d-4042-9263-11d4319f8518.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/169546446-be06ce3d-b8eb-41a9-bbec-84f405d3a1ed.png"  width="300" height="auto"/> </td>
  </tr>
</table> 

## Core 
- [x]  Done

**Comment by Chumva** [comment]
https://github.com/osmandapp/OsmAnd/pull/14603
