### ISSUE TITLE
Track recording widgets: duration, uphill, downhill

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#11190]
It would be great options to be able to see the time of your trip on widgets. 

--------

We need to have 3 additional widgets of recording (1 already present) to choose:
1. Time of recording track
2. Uphill of the recording track
3. Distance of recording (already present)
4. Downhill

## ToDo

- [x] Widgets should be available only if "Trip recording plugin" is enabled.

### Time of recording track
- [x]  Add widget **Time of recording track**, 
- -  Icon – `widget_track_recording_duration_day/night`
- -  Tap: open > Currently recording track > Track > Overview tab 

### Uphill of recording track
- [x] Add widget **Uphill of recording track**, icon – ``
- -  Icon – `widget_track_recording_uphill_day/night`
- -  Tap: open > Currently recording track > Track > Altitude tab

### Downhill of recording track
- [x] Add widget **Downhill of recording track**, icon – ``
- -  Icon – `widget_track_recording_downhill_day/night`
- -  Tap: open > Currently recording track > Track > Altitude tab

**Comment by PaRi53** [comment]
In particular, the hiking time visible directly on the map as a widget.
