### ISSUE TITLE
Plan route: Hide Widgets. Show: Compass, configure map, search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#11311]
# Review 
- [x]  After changing compass orientation, the plan route line starts to float separately from the position.
- [x] Widgets appears on the map after open Search > Item > Context menu: close menu.

# ToDo
- [x] **Show:** Compass / Search and configure map visible
<img src="https://user-images.githubusercontent.com/9365308/113832170-04b5af80-9791-11eb-9b8a-d8abbab8b612.png"  width="300" height="auto"/> 

- [x] **Hide widgets:** Select track on the map, tap on the "Edit" button, "Plan route" will be opened, map widgets will be visible. If you open Menu – Plan Route – Select the same track, widgets would be visible.
<img src="https://user-images.githubusercontent.com/9365308/113269988-b3fe0c80-92e1-11eb-9aee-c4c4dd9cc6d3.png"  width="300" height="auto"/>
