### ISSUE TITLE
Add parameter to use Rtept as straight line

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#12169]
# Review
- [x] Fix issue with arrow (turn) line over whole route
## ToDo
- [x] Add new parameter in Navigation > Follow track: 'Connect track points as'
- [x] Parameter has two toggles `[Selected profile name | Straight line]`. The selected profile should be selected by default.
- [x] Put new parameter under "Navigation type", use the same UI layout

### Description
When you choose to follow the track, the navigation sometimes makes strange circles and turns and uses paths that are not included on the track.

OsmAnd 3.9.10
[testtt.gpx.zip](https://github.com/osmandapp/OsmAnd/files/6849697/testtt.gpx.zip)

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/126336118-ac674e71-fc03-45a2-9079-efd5bf42a482.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/126336171-f51cd3b1-948f-4c34-9332-cb5377b4f658.png"  width="300" height="auto"/></th>
  </tr>
 <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/126336203-f554eb4a-7ffc-47b7-a695-1e2a273e315d.png"  width="300" height="auto"/></th>
    <th><img src="https://user-images.githubusercontent.com/80623554/126336239-bcea90a6-4d93-490b-8f05-6a34cf7f5509.png"  width="300" height="auto"/></th>
  </tr>
</table>
