### ISSUE TITLE
Issue with the large GPX track

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#12443]
# Review
- [ ]  We need to calculate the time span for days, months, and years. One of the included tracks starts in 2017 and ends in 2019 :). Currently, we show hours 20632:20:00
<img src="https://user-images.githubusercontent.com/9365308/140501910-b8613d30-79d6-41ab-9c50-321a626e03a7.png"  width="300" height="auto"/> 

# ToDo
### Description
GPX track from https://transeurotrail.org/france/#4.18/46.870/3.091, contains 23 segments.

- [x]  When you try to select it for navigation, Follow the track, shows only 10 segments
- [x] Trying to open the "Track" tab in the track context menu, leads to OsmAnd crash, without the exception.log
- [x] Issue with navigating through the whole track (looks like segments not joining correctly)
- [x] Issue with navigating through the whole track in reverse direction (looks like segments not joining correctly)

[logcat (6).log](https://github.com/osmandapp/OsmAnd/files/6967350/logcat.6.log)
Device : CAP_sprout
Brand : Nokia
Model : Nokia 5.3
Product : CaptainAmerica_00WW
Build : 00WW_1_290_SP07
Version : 10
App Version : OsmAnd+
Apk Version : 4.0.0#32519m 400

**Comment by vshcherb** [comment]
[la-velodyssee.gpx.zip](https://github.com/osmandapp/OsmAnd/files/6975016/la-velodyssee.gpx.zip)
