### ISSUE TITLE
Cannot turn off shutter sound in A/V notes plugin

### ISSUE THREAD

**Issue by petersohn** [osmandapp/OsmAnd#12648]
### Description

I disabled the shutter sound in the A/V notes plugin, yet it still plays the sound when I take a photo.

### How to reproduce?

* Enable A/V notes plugin.
* In the plugin settings, set "Use system app" and "Camera shutter sound" both to disabled.
* Take a photo note.

It will still play the sound.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: Android 10, LineageOS 17.1
Device model: Motorola Edge

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13627

**Comment by dmpr0** [comment]
# Review
Android 6. 
- [ ]  Doesn't work if use system app is true.

**Comment by vshcherb** [comment]
Sound could be disabled in camera app itself in case you use system app.

**Comment by vshcherb** [comment]
We should disable / hide Toggle in case use system app is selected

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Change **Use system app** from switch to dialog with two options **Camera app**: System / OsmAnd
- [ ]  If  **Camera app** > OsmAnd, show **Camera shutter sound** option

**Comment by sonora** [comment]
Have not researched, but quite possibly facilitating to turn off the shutter sound may be a violation of privacy regulations in some countries.

**Comment by dmpr0** [comment]
# Review 
- [ ]  Shutter sound is present no matter if it **On** or **Off**

**Comment by dmpr0** [comment]
Docs:
* Not all devices allows to turn off Shutter sound, on this devices **Shutter sound** options will be absent

**Comment by sonora** [comment]
Yes, exactly, privacy law mandate in some countries.

**Comment by Chumva** [comment]
Also, we can disable preference instead of hiding it as @sonora [suggested](https://github.com/osmandapp/OsmAnd/pull/17046#issuecomment-1520897134)

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/navigation/guidance/voice-navigation#settings-of-voice-prompts
