### ISSUE TITLE
Long tap on map next to the track doesn't work correctly

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#12663]
# Review
- [ ]  Long tap on the track > point context menu with track name tap navigation > navigation UI show track name as the destination. Maybe we need to replace it with coordinates.

# ToDo
Spillover - https://github.com/osmandapp/OsmAnd/issues/12257#issuecomment-887449308
- [x] Long tap on map next to the track with precise location should open Point context menu (main difference navigation & share button functionality)
- [x] For track menu rename Navigation button to "Follow track"
