### ISSUE TITLE
Improve distinction between Pharmacy & Parapharmacy

### ISSUE THREAD

**Issue by valerio-bozzolan** [osmandapp/OsmAnd#13001]
# 🚀 feature request

### Description

At the moment OsmAnd have no distinction between pharmacies and parapharmacies but they are different:

* **Pharmacy**: medicines are sold and **medical advices are given**
* * `amenity=pharmacy` + `dispensing != no`
* * [Wikidata Q13107184](https://www.wikidata.org/wiki/Q13107184)
* **Parapharmacy**: sale of parapharmaceuticals and pharmaceutical products **without prescription**
* * `amenity=pharmacy` + `dispensing=no`
* * [Wikidata Q920671](https://www.wikidata.org/wiki/Q920671)

### Proposed solution

In the default map theme, improve the graphical distinction:

* for pharmacies: icon should be **green** (instead of pink)
* for parapharmacies: show "Parapharmacy" (instead of "Pharmacy")

### Describe alternatives you've considered

Feel free to share more ideas in the comments.

### Current pharmacy
> ![OsmAnd pharmacy](https://user-images.githubusercontent.com/6052909/137455259-0140b108-b986-448d-a667-5df66d4d04c0.png)
> See the icon that now is pink. We propose green instead.

### Current parapharmacy
> ![OsmAnd parapharmacy](https://user-images.githubusercontent.com/6052909/137455276-adca4fc0-afe9-4ba6-bfa2-9d59d08451ac.png)
> See the name that now is "Pharmacy" even if it's a Parapharmacy. We propose to keep the pink color.

 ## Credits

Many thanks to **Francesco Ansanelli** (@fansanelli) - Italian OpenStreetMap contributor - original author of this bug report since 2020. Many thanks to Italian OpenStreetMap contributors and Wikimedia Italia Staff members.

## TODO

* [X] specifications (2020)
* [X] OsmAnd economical quote (2021)
* [X] funds from [Wikimedia Italia](https://www.wikimedia.it/) (2021)
* [x] start of work (2021-2022)
* [ ] end of work (2022)

Contributors are encouraged in sharing ideas on this issue having said that we have already submitted an economical quote to OsmAnd for their support.

**Comment by vshcherb** [comment]
Probably this issue can be tested already

**Comment by fansanelli** [comment]
> Probably this issue can be tested already

Dear @vshcherb ,

thanks for merging my PR. It lacks the label changes yet, from pharmacy to parapharmacy when dispensing=no. Translations should be done too.

Many thanks
Francesco
