### ISSUE TITLE
Add Plan route tool to the Quick action menu

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#13022]
It would be nice to be able to get access to the Plan route tool via Quick action menu.

**Comment by francwalter** [comment]
It was my feature request, which I had sent to the support by email :)

It is right, the drawer is the same (now?), two clicks, one for the menu button, one for 'Plan route'.
Then another 3 clicks for:
'Create new route' > 'Line icon' > 'Walking'
that makes 5 clicks and I would use it more often just to check a walking distance.
The shortcut in Actions could be then a one click directly to this, that would be nice!
Unfortunately the last used "Route between points" (for me it's nearly always "Walking") is not remembered :(

**Comment by dmpr0** [comment]
# ToDo
- [ ]  Add new quick action "Create new route" in "Create items" category with 
- [ ] Use icon `ic_action_plan_route`. 
- [ ] Taping on action: launch "Plan a Route" with first point set on the map center. Should work simillar to "Context menu > Actions > Plan a route"

**Comment by mmh-dev** [comment]
https://github.com/osmandapp/OsmAnd/pull/13606
