### ISSUE TITLE
add "commercial" to vehicle parameters

### ISSUE THREAD

**Issue by johndh** [osmandapp/OsmAnd#13123]
# 🚀 feature request

### Description

Certain routes specify "no commercial use" or similar, which is distinct from "no trucks", as it also forbids smaller vehicles being used for commerce, such as a delivery car or plumbing van. E.g. Natchez Trace Parkway in Tennessee doesn't allow any commercial use whatsoever, but does allow recreational hauling.
### Describe the solution you'd like

Allow a means of categorizing whether a profile is for a commercial vehicle (truck) or non-commercial (like a motorhome or personal vehicle pulling a boat trailer).
### Describe alternatives you've considered

Using a truck profile for a delivery car, or a car profile for an RV, doesn't achieve the correct results.

**Comment by dmpr0** [comment]
Support for https://wiki.openstreetmap.org/wiki/Key:goods should be added

**Comment by dmpr0** [comment]
## ToDo, [Figma](https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?node-id=2262%3A144522)

- [ ]  Rename **Goods vehicles restrictions** to **Goods delivery**
- [ ]  Icon: `ic_action_van`
- - [ ] Use profile active color if **Yes** selected
- [ ]  Use dialog with Yes/No buttons.

<table style="width:100%">
  <tr>
    <th>List item states.</th>
    <th>No</th>
    <th>Yes</th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/173042329-e6e7634e-45c4-4f9f-b432-ff337c2adc78.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173042335-6b2a10ef-6a5b-4256-84b7-275b55e6215c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173042339-3c74171d-f132-455e-abc7-c6a7d279f159.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nazar-kutz** [comment]
**Implement UI > PR**
https://github.com/osmandapp/OsmAnd/pull/14565
