### ISSUE TITLE
Current speed / speed limit widget (including Android Auto)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#13413]
## Description
Add new widget with current speed and speed limit. Visually similar to screen alerts that shows on the bottom right side of the screen.

# ToDo

## Widget on map

|**Current speed** | S | M | L |
|---|---|---|---|
| Width | 72 dp | 88 dp | 126 dp |
| Height | 56 dp | 72 dp | 96 dp |
|**Text size** | | | |
| Value | 24 sp |  36 sp | 60 sp  |
| Units text size | 11 sp | 11 sp | 11 sp |
|**Corner radius** | | |
| Android | 6 dp | 6 dp | 6 dp  |
| Android Auto | 16 dp |16 dp | 16 dp |

# Android Auto

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>EU</th>
    <th>USA</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/230927186-641a34f1-df93-478a-af8f-78c83c2fa79c.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/230927208-b2096ed6-b448-41e2-8d40-2756aa4da81d.png"  width="400" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x] Show widget on the right side bellow top buttons
- [x] Widget should use and follow the same set of settings 

**Current speed, widget**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/efe63abf-ac3b-44c8-a7e8-754ff26179c3"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Fixed Width for 3 digits.
- [x] Min. size, **L**arge:
- - [x] W / H = 126 x 96 dp + 3 dp stroke
- [x] Min. size, **M**edium:
- - [x] W / H = 88 x 72 dp + 3 dp stroke
- [x] Text:
- - [x] Value: L / M – 36 / 60 sp
- - [x] Units: L / M – 11 / 11 sp
- - [ ] Text align to the right side to LTR

**Speed limit warning**
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f7ec4682-7654-471e-a4b2-30fb5c7a2f4f"  width="300" height="auto"/> </td>
  </tr>
</table>  

- [x] Speed limit warning should be shown on the left side of Current speed widget.
- [ ] Support two version USA / Canada and Europe 

# Android

## Configure Screen

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Configure Screen </th>
    <th>List item states </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/dd78b4dc-f19a-41e1-b83d-3664a921eab6"  width="300" height="auto"/> </td>
    <td valign=top><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/db1f5d09-fa36-4d68-bcc0-11f9c40010ed"  width="300" height="auto"/> </td>
  </tr>
</table>  
</details>  
 

- [x]  Add new item **Speedometer** to card **Other**
- - [x] Icon
- - [x] Tap, should open separate screen with widget settings 

### Speedometer settings

<table style="width:100%">
  <tr>
    <th>Disabled</th>
    <th>Enabled, L</th>
    <th>Enabled, M</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/765c31b6-bb0f-4ce6-8fa4-f4fd33131a90"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a5df7c58-4316-4cb0-a401-cf0e7c142dd2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/80e83691-1359-45a1-b8aa-493448026446"  width="300" height="auto"/> </td>
  </tr>
</table>   

# Next task (PM team)
- Preview for all widgets

<details>
    <summary>Original request</summary>

I think it will be useful to add Speed and limit widget for Android Auto screen (Car Play too).
- Display constantly current limit (grey icon if not exceeding) as Alert, (original color if exceeding) 
- Add setting to  Screen Alert widget as constantly display Speed limit 
- Check that exceeding has lower priority than other alerts (cause it's using same spot)

![image](https://user-images.githubusercontent.com/44466116/146926834-34246800-b95f-4faf-95a4-9656ea03faf9.png)

</details>

**Comment by mdykierek** [comment]
I agree.
I came here to report this feature request, but found this one, so +1 from me.

**Comment by FedericoBusero** [comment]
Max speed on Android Auto: +1

**Comment by WizoneDE** [comment]
love the way how tomtom has integrated it. merged with the current osmand style:

Speed limit and current Speed: (Long head unit)
![speed_1_big](https://user-images.githubusercontent.com/35132439/217815842-345ffb23-c291-4c9b-b08e-531820e42667.png)

Speed limit and current Speed with overspeeding warning: (Long head unit)
![speed_1_big_warn](https://user-images.githubusercontent.com/35132439/217815851-1e6fb54d-4aea-438f-8459-d9532c8dfba2.png)

Speed limit and current Speed: (short head unit)
![speed_1_small](https://user-images.githubusercontent.com/35132439/217815854-6b187eb8-cb0e-448b-8763-ee47197b9f51.png)

Speed limit and current Speed with overspeeding warning: (short head unit)
![speed_1_small_warn](https://user-images.githubusercontent.com/35132439/217815858-0e0b4140-a474-4ee3-8eb1-ee15a26c7793.png)

Speed limit and current Speed: (Long head unit)
![speed_2_big](https://user-images.githubusercontent.com/35132439/217815865-fc893617-557c-450c-81c2-a91c61d38e2c.png)

Speed limit and current Speed: (short head unit)
![speed_2_small](https://user-images.githubusercontent.com/35132439/217815866-e418a936-03ef-4ec8-97bb-0d4b4ebbc531.png)

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <th>EU</th>
    <th>USA</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/230927186-641a34f1-df93-478a-af8f-78c83c2fa79c.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/230927208-b2096ed6-b448-41e2-8d40-2756aa4da81d.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 

## Configure Screen

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="ttps://github.com/osmandapp/OsmAnd/assets/9365308/7be23ee9-ae8e-44d8-a502-7e9be3370051"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Missed divider above **Speedometer** item

**Comment by DmitryAlexei** [comment]
When parking and creating a route, i.e., by going to the profile where you turned on the speedometer widget
- speedometer widget indicates null. 

After you move, when you stand at traffic lights, 0 is shown. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/89ab8806-b81d-45b9-9186-82487ff5a146"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 2
- [ ] Should displayed both on Android Auto and on Mobile device?

**Comment by DaanLT** [comment]
I have device:

car head unit, 1280x720 screen, UIS7862 based (ums512), android 10 (API/SDK 29),
https://gadgetversus.com/processor/unisoc-uis7862-specs/

OsmAnd nightly build:
OsmAnd~ 4.7.0#1894m, released 2024-03-22

have those speedometer issues:
speedometer does not apper at all on any profile, only shows in active navigatiom mode.
----
current speed does not fit widget on all sizes:
![Screenshot_2024-03-22_114414](https://github.com/osmandapp/OsmAnd/assets/128729388/70b7efaa-bad1-41ed-a4a6-64c2ada84175)
![Screenshot_2024-03-22_114421](https://github.com/osmandapp/OsmAnd/assets/128729388/0c19870d-b6e1-4dce-95d9-68b018100c78)
![Screenshot_2024-03-22_114432](https://github.com/osmandapp/OsmAnd/assets/128729388/0e96840c-7a9a-48e8-b4d4-04160d95490a)
------
whem in active navigation mode, additional warning icons cause speedometer jumps/position change:
![Screenshot_2024-03-22_114851](https://github.com/osmandapp/OsmAnd/assets/128729388/72d152c1-ffe4-4399-834f-19cf5ac53c63)
![Screenshot_2024-03-22_114922](https://github.com/osmandapp/OsmAnd/assets/128729388/a7345037-1d55-43d7-adbf-94d9f5aff3ba)
------
Screen widgets problem:
Current speed widget no longer available - only speed limit one available in browse or car profile.
In browse profile current speed is shown in car profile its not.

![Screenshot_2024-03-22_115449](https://github.com/osmandapp/OsmAnd/assets/128729388/3af769c0-98ea-4c38-940a-f192277e163f)
![Screenshot_2024-03-22_115458](https://github.com/osmandapp/OsmAnd/assets/128729388/afc9a0bd-ae99-4166-a10f-e50fdf2c5c45)
![Screenshot_2024-03-22_115923](https://github.com/osmandapp/OsmAnd/assets/128729388/3103358a-145e-4582-a757-2802d59a7682)

**Comment by DaanLT** [comment]
nightly build 2024-03-27 OsmAnd~ 4.7.0#1928m:
some updates:
now speedometer is displayed in all modes - thank you.
but problem remains with speedometer cut text:
![Screenshot_2024-03-27_111211](https://github.com/osmandapp/OsmAnd/assets/128729388/6f4b2b3f-4847-4af1-bbbb-f4f896d97fa4)
---
aslo current speed is displayed with dot, not rounded number - but only in browse profile. In navigation/car mode its displayed rouded in both speedometer and widgets area
![Screenshot_2024-03-27_111231](https://github.com/osmandapp/OsmAnd/assets/128729388/18ce9284-0568-4cba-8ce6-140930b3243b)

**Comment by EugeneZmeuk** [comment]
**02.05.2024**
- [ ] added [Speedometer](https://osmand.net/docs/user/widgets/info-widgets#speedometer) section for Informationa widgets article
- [ ] added [Speedometer](https://osmand.net/docs/user/navigation/auto-car#speedometer) section for AA article

**Comment by vshcherb** [comment]
- [ ] Speedometer should be related to Alerts of exceeding speed especially to the setting of Tolerance of speed exceeding
- [ ] Speedometer also works as current street, so it works without navigation in some profiles (see other documentation)

**Comment by lukasb314** [comment]
> 1. [voice-settings](https://osmand.net/docs/user/navigation/guidance/voice-navigation/#voice-settings)
> 2. [speed-limit](https://osmand.net/docs/user/navigation/guidance/voice-navigation/#speed-limit)
> 3. [speedometer widget](https://osmand.net/docs/user/widgets/info-widgets#speedometer)
> 4. [AA](https://osmand.net/docs/user/navigation/auto-car#speedometer)

Is this speedometer widget still working as shown in the documentation? I can't find anything like that in the iOS app.

Generally I'm looking for the setting to _permanently_ display the current speed limit on the CarPlay screen - not just when I'm overspeeding.

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Configure Screen</th>
    <th>Speedometer</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/356ca821-93e1-48d8-827f-5f93bcbd8d9c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d0363c69-cad3-4371-adec-6d95ab45b8e2"  width="300" height="auto"/> </td>
  </tr>
</table>   
Hi! @lukasb314.

You can enable Speedometer in Menu – Configure Screen – Speedometer – Speed limit warning – Always. Speed limit signs will be shown always if data is present on the map.

**Comment by lukasb314** [comment]
Thank you @dmpr0 

I was looking at the Panel Configuration all the time 😞
