### ISSUE TITLE
The switch for GP services

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#13518]
There is an issue with altitude data during trip recording (for Google Play services):
https://github.com/osmandapp/OsmAnd/issues/10864
<img src="https://user-images.githubusercontent.com/44466116/148813060-40f11b4e-13aa-4ee1-b238-2b63050e287c.png"  width="300" height="auto"/> 

I propose to make the switch:  Google Play services <-> Android API  as it is done in Organic maps:
<img src="https://user-images.githubusercontent.com/44466116/148813077-8887ef1f-c57f-4c9f-9225-579eb7b9a498.png"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
# ToDo
### OsmAnd Settings:
- [ ]  Create new settings group "Other"
- [ ] Move "Dialogs and Notification" into "Other" group
- [ ] Add new "Location source" option into "Other" group

### Location source
- [ ]  Add two options: "Google Play Services", "Android API".
- [ ] "Google Play Services" should be selected by default
- [ ] For Amazon and Huawei builds, "Android API" should be selected by default

<table style="width:100%">
  <tr>
    <th>OsmAnd Settings. <a href="https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?node-id=2%3A28615">Figma</a> </th>
    <th>Location source dialog. <a href="https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?node-id=1910%3A138912">Figma</a> </th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/149325967-ffd1c9ed-87ea-4657-aeba-b9dfc35c2dd4.png"  width="300" height="auto"/></th>
    <th valign=top><img src="https://user-images.githubusercontent.com/9365308/149326103-d07afb90-25c3-4e6f-8bcc-73456d2fed78.png"  width="300" height="auto"/></th>
  </tr>
</table>

**Comment by Chumva** [comment]
This should be added here - https://github.com/osmandapp/OsmAnd/pull/13715

**Comment by sonora** [comment]
Could anybody specify here which mechanism our **nightly master builds** used prior to Feb. 8 ?

(I am comparing some old tracks and want to be sure what artifacts are due to this issue or not.)

**Comment by sonora** [comment]
Thanks, Victor!

After reviewing a bunch of tracks recorded with OsmAnd over the years, it seems I advocate https://github.com/osmandapp/OsmAnd/issues/13805. When looking at all tracks apparently  recorded with the google mechanism, on several devices, it seems that they systematically expose a lot more vertical noise, often with elevation amplitudes up tp 20 or 30 m (at rest) between points, where the Android API seemed to produce artifacts at least one order of magnitude smaller.

**Comment by vshcherb** [comment]
I think since it's now configurable it's not a question any more and we need to follow Google recommendations by default

**Comment by sonora** [comment]
Yea, probably so...

I invite everbody to record a track with Android API, then mid☆trip change ro google, rhen at the end of the trip check it out the result n OsmAnd's altitude graph. I have yet ro find a devixe where the difference is anything less than  dramatic - average seems about a factor of ten (!) more in signal ro noise  ratio for the google method...

**Comment by scaidermern** [comment]
> I invite everbody to record a track with Android API, then mid☆trip change to google, rhen at the end of the trip check it out the result in OsmAnd's altitude graph. I have yet to find a devixe where the difference is anything less than dramatic - average seems about a factor of ten (!) less signal ro noise ratio for the google method...

Same route, different day, top is Android API, bottom is Google PlayServices.

![height](https://user-images.githubusercontent.com/1040784/178246916-e9edd6ac-d895-4d4a-a069-a89544f57339.png)

I can't see any significant difference. However, this could very well be device- or os-specific (Android 10 / LineageOS 17.1 on Samsung S9 here).

**Comment by sonora** [comment]
Yes, it seems device-specific indeed. I also have a feeling that pre-Android 11 there may not be a big delta but on Abdroid 11+ there is...
