### ISSUE TITLE
Analyze on map: show data from two axes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#13524]
# Review 2
- [x]  Day theme of chart marker when map mode is night
- [x]  Repeating seconds in time of day when scale interval is few seconds
- [x]  Slider doesn't support 12-hour time format (AM/PM)
- [x]  Time of the day and slider show different data

<table style="width:100%">
  <tr>
    <th>12 hour time format</th>
    <th></th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/160370961-e9817b69-1497-452e-a613-2575c8c18bcd.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/160370976-ec1e15d2-f0dc-4969-9215-ef1ab0cfe6e1.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

# Review
- [x]  Slider: Show data from 3 axes, for example "Altitude/Speed – Time of the day".  `100 m | 15 km/h | 18:34:15 `
- [x] Altitude – Time `100 m | 18:34:15 `
- [x] Altitude – Time of the day `100 m | 18:34:15 `
- - [x] Show two data from two axes
- - [x] Show seconds on x-axis
- [x]  Altitude – Speed `100 m | 15 km/h `
- [x] Slope – Distance `0% | 350 m `
- [x] Speed – Time of the day, show seconds on x-axis

# ToDo
Analyze on map: show data from two axes only for a few graphs, for example:
Speed – Distance

- [x]  Show data from both axes on slider
- - [x] Speed – Distance `15 km/h | 350 m`
- - [x] Speed – Time `27 km/h | 20:12:15 `
- - [x] Speed – Time of the day `2 km/h | 18:34:15 `

Additional:
- [x]  Don't change map zoom and point location when graph axes are changed
- [x] Number formatting on chart. 30000 m > 30 km or 30 000 m

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/148927478-56b22567-9156-43e5-8dff-246c19b01368.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/148927497-cc261bc3-215c-47aa-8a50-be0958335fd9.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/148927502-1d6e5e2d-ac97-4be6-87b7-bcb08de08a5c.png"  width="300" height="auto"/> </th>
  </tr>
</table> 

# Related issues
https://github.com/osmandapp/OsmAnd/issues/10373

**Comment by Nine-Tailed** [comment]
![Screenshot_2022-01-21-01-41-14-462_net.osmand.plus.jpg](https://user-images.githubusercontent.com/12549744/150433662-7790cc3b-3aec-4180-b8b2-a1549f8a6205.jpg)
Есть два замечания:
1. На оси времени суток нет секунд.
2. Время возле курсора не совпадает со временем на оси.

**Comment by cepprice** [comment]
https://github.com/osmandapp/OsmAnd/pull/14058
