### ISSUE TITLE
Speed/Slope for track analyze

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#14140]
## Review
- [ ]  Feels like this bottom sheet is open slowly if compare to bottom sheet in General settings.
- [x] Icons:
- - [x] Slope – `ic_action_slope`
- - [x] Time of day – `ic_action_time_of_day`
- [x]  List item height is too big. min 56dp

## ToDo
We have the issue with graph type selection for the axis because for some types on the y-axis (**Slope**, **Altitude+Slope**) only **Distance** is available on the x-axis. So after selecting Slope on Y, you can't select Time on X, or if the user selects Tyme on X, some types are missed on Y. 

- [x]  Add **Speed/Slope** type for Y-axis.
- [x] All types from Y-axis should be work with all types on X-axis. For example:
• **Slope** and **Altitude+Slope** with **Time** or T**ime of day**.

<img src=""  width="300" height="auto"/> 
<table style="width:100%">
  <tr>
    <th>Current menu</th>
    <th>Variant 1</th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/44466116/165314936-d9ce2b5b-7832-4e88-b969-7adab4969c70.png"  width="230" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/185080262-fcad5c92-6cdf-4113-a438-9cde0af2d2cf.png"  width="230" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14086mqta, released: 2023-01-11
Done

**Comment by shurasmiling** [comment]
1. https://osmand.net/docs/user/navigation/setup/route-details#analyse-on-map

2. Add to (https://osmand.net/docs/user/map/tracks-on-map#analyze-track-on-map) when writing [Article - Tracks and Routes](https://osmand.net/docs/user/map/tracks-on-map) (task hasn't been created).

**Comment by vshcherb** [comment]
Review - https://osmand.net/docs/user/map/tracks-on-map/#analyze-track-on-map
