### ISSUE TITLE
Add Option to download Vertical or Square area (Update Online Maps)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14486]
## ToDo

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4351b2cd-1ba1-4862-8e9b-250c6189ed15"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/359df861-ca0a-4158-b47d-c07a484fc483"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Change visual border of downloading area to square.
- [x] Square area should be downloaded

- - -

<details>
    <summary>Original comment</summary>

Probably we can add button to change "shape" of downloading area (Both Android / IOS) at least square but preferably vertical as well.

![telegram-cloud-photo-size-4-5837034974342133711-x](https://user-images.githubusercontent.com/1042025/172424344-6bb14673-f3fb-4fb4-9b45-7dcc35818a80.jpg)

</details>

**Comment by Skywriter960** [comment]
👍 My wish is a bounding box ... 👍

**Comment by vshcherb** [comment]
Enlarge area by height in portrait mode

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d8a67493-5caa-4349-aa2b-642bb2706d0d"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/359df861-ca0a-4158-b47d-c07a484fc483"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Scroll map area as part of UI if possible 

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/69e65083-c7cf-499a-87c6-e5c52f105670"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Not a square in Landscape
