### ISSUE TITLE
Tracks Stats Dashboard

### ISSUE THREAD

**Issue by scopecrepe** [osmandapp/OsmAnd#14673]
# 🚀 feature request

### Description

OsmAnd should have a dashboard feature similar to the [Stats feature of AllTrails](https://s3.amazonaws.com/totemv2-production/totem/assets/screenshots/attachments/5237/original/AllTrails_Stats.png?1586462712).

It appears there is no way to see stat totals for miles/kilometers of a group of recorded tracks.

### Describe the solution you'd like

Possible feature details:
- Lifetime totals for a group (example: total distance, elevation gain, moving time, etc)
- Bar graph of each month's total distance in a year

**Comment by dmpr0** [comment]
## ToDo
Add total track stars below list of tracks in all subfolders.


`Tracks – 4, distance – 246.6 km, uphill – 325 m, downhill – 456 m, duration – 08:50:35, size – 14 MB.`
- [ ]  Tracks quantity in folder
- [ ] Total sum of distance
- [ ] Total sum of uphill
- [ ] Total sum of downhill
- [ ] Total sum of duration
- [ ] Total size in MB
<table style="width:100%">
  <tr>  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2dbaaefe-c840-41b5-aa5e-43edc7ddebb1"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/tracks.md#dashboard-android

**Comment by vshcherb** [comment]
- documentation doesn't correclty identify available only on Android (confusing title)
- not specified where information is located
``` Menu → My Places → Tracks (... here should be) ```

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/personal/tracks#folder-statistics-android
