### ISSUE TITLE
Bugs Average Speed

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#14783]
# Review 2
- [x] Check if it works in background (same as track recording)
- [x] Change algorithm to calculate average to just SUM (Speed ) / N - old keep optional

# Review
- [x]  It seems doesn't work when **Take stops into account** is **On**

# ToDo
Bug Average Speed
- [x] if you set 30 min window and starts moving, average speed should be displayed immediately and not after 30 min
Simple rule: widget calculates average speed for last **X min**. If X is longer then application startup, it should not be a problem according to definition.
- [x] Looks like duplicate widgets don't support different window size
- [x] Check ETA for Markers as well
