### ISSUE TITLE
My Places / Tracks: Allow to sort by length and duration

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14890]
Currently tracks can be sorted either by name or by last modification. It would be very useful to add further sorting options such as by track length and by time duration.

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <th>Bottom sheet</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/217781389-f434ebdb-4321-45d3-b02a-bac5a50940ee.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/217781393-3fa92054-6259-4ac2-98ac-7e36e4c1ccff.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/217781396-bdea557f-2e55-4a5b-9829-e3f8dc0eb9b2.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment]
There's a problem here, it takes now several to many minutes to open the Tracks screen if you have folders with ~50-100 tracks in each.

Need to find a way like we had on "MyPlaces > Tracks",  that screen appears within 1-2 seconds (regardless of what your sorting is set to).

**Comment by sonora** [comment]
Still some open issues, if I may suggest:
- crash, see here: https://github.com/osmandapp/OsmAnd/commit/4afece701fc2b528a52bd7243a9c09b2643384c1#commitcomment-103769000
- I propose sorting should affect all tabs, remembering per tab causes more awkwardness than benefit, https://github.com/osmandapp/OsmAnd/commit/4954128d3b31a9741c3ff6ea9cbb23d6df9477bd#commitcomment-103609466 ?
- Sorting was not flawless as of late, but I will test more with latest fixes.

**Comment by sonora** [comment]
Regarding the crash (1) above, the following additional info. Suspicion is this has to do with a too high number of tracks or somehow a particular track on my 'All'  tab.So I have the following additional information: I have  temporarily renamed my tracks folder, created a new one, and in it simply copied only one of my subfolders of the original tracks folder:
- Re-opening OsmAnd, then going to this screen's 'All' folder, and sorting by Nearest works.
- Now I kill OsmAnd, rename my original tracks folder back, restart OsmAnd: The A'll' folder is still correctly sorted by Nearest, so now no crash(!)
- Now I resort it to A-Z, then back to Nearest: Now the crash re-occurs (and stays for that tab).

**Comment by Nine-Tailed** [comment]
Osmand also crashes when I try to sort the next tracks
https://github.com/osmandapp/OsmAnd/issues/16662

**Comment by sonora** [comment]
Regarding the crash (1) above: It seems this has to do with certainl file constellations or certain track files.I have e.g. a file which has 2 trkseg with only one trkpt in each. Removing that file from one folder removes the crash and makes that folder sortable by Nearest. But placing that same file in another folder causes no crash there, so it's weird.

Also: Files with only one trkpt per trkseg seem exluded from tve Mearest sorting (sorted to the end with no distance shown), why? Same for files with just wpt's?

**Comment by Chumva** [comment]
@sonora Can you check if the issue still exists with this fix? https://github.com/osmandapp/OsmAnd/pull/16668

**Comment by sonora** [comment]
I have added some observation and suggestion on code optimization here:https://github.com/osmandapp/OsmAnd/pull/16668#issuecomment-1465009762.

Seems to me the major issue we have is that the Comparator we use can behave strangly when used for sorting because of this:
- At the end of the day what we really want to sort is gpx **files** (the ones contained in the subtree of the tracks folder)
- But for some sort orders we do not use file properties, but intrinsic proprties of the gpx tracks
- Now in the Comparator we create the situation where sometimes.`compare(entry1, entry2)==0` does not have the same boolean value as `entry1.equals(entry2)`, 
- and I think that may exactly cause the weird effect on sorting we see in some constellations of users having duplicate files or files/tracks with identical properties, hard to reproduce on other devices.

**Comment by Chumva** [comment]
It is harder to cover all cases using analysis instead of just files, but it gives much more functionality to sort tracks based on their content than just for files. With https://github.com/osmandapp/OsmAnd/pull/16668 we should fix most of these issues

**Comment by sonora** [comment]
Yes, we're good now functionally! I have just tested, and think we could merge https://github.com/osmandapp/OsmAnd/pull/16668. 
- We could likely optimize the if code sligtly, I can make a subsequent PR.
- Also, our GPX analysis does not seem to return a track startpoint (hence no distance) for tracks only containing one trkpt, but that is another code area, can be looked at separately.

**Comment by sonora** [comment]
PS: Is it a big deal to have a popuup scrollbar on the side of the track list? Some of these lists can be long, scrollbar can help ease the fact that we have no search yet.

**Comment by sonora** [comment]
Cool! And see here: https://github.com/osmandapp/OsmAnd/pull/16673, this removes a few surplus condition queries.

**Comment by sonora** [comment]
PS: Maybe I'm wrong, but you cannot use that scrollbar to scroll the list right? Does it simply have to be wider, or would we have to wrap in a ScrollView?

**Comment by Chumva** [comment]
That scrollbar only shows the position in the list, probably we can use [fastScrollBar](https://stackoverflow.com/a/46026362) but we have to create some drawables for it.

**Comment by vshcherb** [comment]
This task needs to be testing

**Comment by vshcherb** [comment]
- [ ] [app:fastScrollEnabled="true"](https://heartbeat.comet.ml/adding-fast-scroll-to-recyclerview-in-android-5a963e2b509d)
- [ ] Tabs will follow sorting on My Places (will be fixed)
- [ ] For subfolders (for now, path will be displayed in the categories screen, but won't be in the tabs)

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
The punctuation mark is a point, not a coma - as in the task

<details><summary>Dot > Coma</summary>
<img width="200" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/225074084-77831656-15f4-43aa-ad4a-dfa46e968358.jpeg">
<img width="600" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/225074113-6d92f14a-8a9b-4f91-983f-428a5b42e16f.png">
</details> 

Perhaps, in landscape mode, should sort the list of folders on the right side of the screen, not in the center

https://user-images.githubusercontent.com/104760013/225075041-d7cb96bb-505d-48db-8ded-7935c0120d1c.mp4

**Comment by dmpr0** [comment]
## Review
- [ ]  Strange sorting by name
<table style="width:100%">
  <tr>
    <th colspan=2>A-Z</th>
    <th>Z-A</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/226317954-ce969e32-95de-42e0-8135-205ee1c5f21b.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226317959-28b18d59-2f18-4072-8fcd-18245bf8b527.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226318339-e8523030-246d-4d7a-950f-9d8b9ad52ea5.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14270mqta, Released: 2023-03-25
Done

**Comment by vshcherb** [comment]
- [ ] We need to try to identify cities instead of regions

**Comment by scaidermern** [comment]
Will these new sorting modes also get added to My Places / Tracks? (see the title of this ticket :))

**Comment by vshcherb** [comment]
Yes
