### ISSUE TITLE
Ask to disable battery optimization

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#14958]
People complain quite frequently about OsmAnd loosing location access when run in the background while navigating or recording a track. Usually this can be solved by disabling battery optimization for OsmAnd. However, currently every user has to to this manually.

Android allows apps to ask for exactly this, guiding the user to the corresponding setting. There are various apps that already do this.

Can you add the `REQUEST_IGNORE_BATTERY_OPTIMIZATIONS` permission and the corresponding code to OsmAnd?

**Comment by sonora** [comment]
Last I researched, that setting was not sufficient, on many systems not even required. I have a write-up somewhere on osmand.net/docs showcasing a configuration I have used flawlessly for a few years now on several Samsung devices (with that setting off).

Trouble is this may be manufacturer, device, and firmware version sensitive.  But maybe somene should doublecheck that research with newer devices before we invest into a method which will not widely apply?

**Comment by vshcherb** [comment]
https://stackoverflow.com/questions/44862176/request-ignore-battery-optimizations-how-to-do-it-right
To do:
- [ ] When you start track recording (Widget, Drawer, My places)
- [ ] Banner Trip recording plugin settings

**Comment by dmpr0** [comment]
## ToDo
* We need to add banner to Trip recording plugin settings. (similar to Speed cameras)
* Add dialog with detailed description (similar to Speed cameras)

### Trip recoding, plugin

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Banner</th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7445bffa-cff1-4016-a1f6-34a7b8fba55a"  width="300" height="auto"/> </td>
        <td><img src=""  width="360" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Show banner if [isIgnoringBatteryOptimizations](https://developer.android.com/reference/android/os/PowerManager#isIgnoringBatteryOptimizations(java.lang.String)) is true.
- [ ] Icon – `ic_action_warning_colored`
- [ ] Text – `Android battery optimisation can cause gaps and inaccuracies in recorded tracks.`
- [ ] Button – `Read more`
- [ ] Tap on button – show Battery optimisation dialog

**Comment by scaidermern** [comment]
Typo(s): optimisation -> optimi**z**ation

**Comment by sonora** [comment]
> Typo(s): optimisation -> optimi**z**ation

optimisation may go to the en_UK resource file ... 😉

**Comment by dmpr0** [comment]
# Review 
- [ ] Open setting for OsmAnd app (if possible)

**Comment by shurasmiling** [comment]
1. https://docs.osmand.net/docs/user/plugins/trip-recording#baterry-optimization
2. https://docs.osmand.net/docs/user/personal/tracks#baterry-optimization-android-only

**Comment by EugeneZmeuk** [comment]
**29.03.2024 Review**
- Trip recording article
- Tracks article
