### ISSUE TITLE
BLE/ANT+ Management Sensors 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#15459]
# ToDo
Next to ANT+ support BLE sensors
https://developer.android.com/guide/topics/connectivity/bluetooth/ble-overview

## Main screen empty state
First screen when sensors are not paired with OsmAnd.
- [x]  Image `img_help_sensors_day/night`
- [x]  **Pair new sensor** button open bottom sheet.
- [x] **Learn more about sensors.** open documentation on page https://docs.osmand.net/docs/user/plugins/external-sensors
- [x] AppBar `add` icon should launch Pair new sensor bottom sheet

### Pair new sensor bottom sheet
- [x] **Pair Bluetooth LE sensor** launch searching of BLE sensorsё
- - [x] Icon `ic_action_bluetooth`
- [x] **Pair ANT+ sensor** launch searching of ANT+ sensors
- - [x] Icon `ic_action_ant_plus`
- - [x] Detect if ANT+ is available on device?
- [x]  Taping on any Pair button, Ask for Bluetooth permission if not present.

<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>Pair new sensor</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216026089-17a502ad-ca27-45dc-af50-15b45ae3f576.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216026082-8694c780-c98b-471a-a5c3-e712e4bf02bd.png"  width="200" height="auto"/> </td>
  </tr>
</table>   

## Searching
<table style="width:100%">
  <tr>
    <th>Bluetooth Off</th>
    <th>Searching</th>
    <th>Nothing found</th>
    <th>List of available devices</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216030630-3a46e473-e341-4622-ad48-e01d2b4fa9c3.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216030622-ae68fb03-138f-4b6d-9e32-7fd4968d928f.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216030623-e13dbe6a-0101-4d10-b10a-c9c9c2de7496.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216030626-d0eaad4a-87b1-4ee4-be41-8aba23ab1c2a.png"  width="180" height="auto"/> </td>
  </tr>
</table>   

## Main screen with connected sensors, [Figma](https://www.figma.com/file/psbEg4fXLWWTl3r2JlCExd/Plugins?node-id=1702%3A35683&t=Mcdic2gCWEEMff1c-1)

- [x] If user doesn't have paired sensors, show Main screen empty state
- [x] Screen show only paired sensors
- [x] Divide sensors into two lists: **Connected** and **Disconnected**.

### Menu
- [x]  **Disconnect**, disconnect sensor, show toast. Icon `ic_action_sensor_off`
- [x] **Settings**, open sensor screen, icon `ic_action_settings_outlined`
- [x] **Rename**, open dialog. Icon `ic_action_edit_outlined`
- [x] **Forget**, icon `ic_action_sensor_remove`
<table style="width:100%">
  <tr>
    <th>External sensors</th>
    <th>Menu</th>
    <th>External sensors</th>
    <th>Menu</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216084417-d06baaad-5a03-4663-8c97-1111ffbd1538.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216084399-d0e24774-79f6-430b-9784-9a0beea3acd8.png"  width="180" height="auto"/> </td>
   <td><img src="https://user-images.githubusercontent.com/9365308/216084409-b1e5337d-b5b8-4a81-8201-6daad44b6761.png"  width="180" height="auto"/> </td>
   <td><img src="https://user-images.githubusercontent.com/9365308/216084422-2eecefc7-7011-4f4f-bacf-e7094a2295e8.png"  width="180" height="auto"/> </td>
  </tr>
</table>   

## Sensor screen, [Figma](https://www.figma.com/file/psbEg4fXLWWTl3r2JlCExd/Plugins?node-id=1761%3A40475&t=Mcdic2gCWEEMff1c-1)

<table style="width:100%">
  <tr>
    <th>Not paired</th>
    <th>Paired, Disconnected</th>
    <th>Paired, Connected</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216029081-fc0059a2-3e86-43ab-a174-0ddcae92d012.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216029084-dcdc0176-eae8-42dc-a1d3-07f389025924.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216029088-3457bdc6-00f8-4265-9ef5-a751fc09792e.png"  width="200" height="auto"/> </td>
  </tr>
</table>   

## Toast messages
- [x]  Show toast when paired sensor is connected or disconnected.
- [x]  Show toast when battery level of paired sensor is less then 15%

**Comment by dmpr0** [comment]
Docs:
- [ ] How to now what type on sensor ANT+/BLE I have.
- [ ] How to connect / activate sensor

**Comment by niobebo** [comment]
Can I test the BLE function in the current nightly build ?

**Comment by vshcherb** [comment]
Nope you can test demo apk that we're preparing though .... We plan to merge this demo app with OsmAnd.

**Comment by niobebo** [comment]
thanks 
When will the demo app be available?
 Where can I download it?

**Comment by 0xRe1nk0** [comment]
> thanks When will the demo app be available? Where can I download it?
[app-debug.zip](https://github.com/osmandapp/OsmAnd/files/10568619/app-debug.zip)

Here is the test app. Supported sensors are in the filter

**Comment by niobebo** [comment]
thanks for reply
sorry  can't install   Message:  bad or split  APK

    Am Donnerstag, 2. Februar 2023 um 13:00:02 MEZ hat 0xRe1nk0 ***@***.***> Folgendes geschrieben:  
 
 



thanks When will the demo app be available? Where can I download it?
app-debug.zip


Here is the test app. Supported sensors are in the filter

**Comment by vshcherb** [comment]
You need to unzip it after download

**Comment by niobebo** [comment]
that is was i doo...  unzip  and install the apk 

i tried also to install with a split apk installer  the Message:  select Base APK  (com.example.bletestapp)  > install Y >
error> install parse failed no certificate
sorry...

**Comment by utack** [comment]
Sorry to ask in here, but would that work also allow you to add a feature to send GPX files to ANT+ devices like a Garmin Etrex directly?  
https://www8.garmin.com/manuals/webhelp/eTrex22x-32x/EN-US/GUID-9B89C076-1C30-457C-84D0-E3DBF5A34ACB.html  
     
 That would be absolutely amazing

**Comment by dmpr0** [comment]
# Review 
## Pair new sensor bottom sheet
- [ ]  Should be shown above **External sensors** screen
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>Figma</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216026089-17a502ad-ca27-45dc-af50-15b45ae3f576.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216026082-8694c780-c98b-471a-a5c3-e712e4bf02bd.png"  width="200" height="auto"/> </td>
  </tr>
</table>

**Comment by alex-osm** [comment]
- [ ] Widgets
- [ ] Ant Battery / Rssi events
- [ ] Fix TODO 
- [ ] Check connectivity issues of all supported BLE devices

**Comment by JakDoh** [comment]
It would be good to have an additional layer that ensure authentication (CHAP or so) with the sensor (like for MiBand and other brands of wristbands) before reading data from the sensor.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#82m, Released: 2023-05-24

- [ ] Scroll still doesn't work in Landscape - button is outside the screen
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/f930bb11-83d8-46e9-b329-f4a75843c035"  width="600" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 2
### Main screen empty state

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#213m, Released: 2023-06-15

- [ ] Bluetooth icon is not displayed
- [ ] Screen status refreshes after reopening the screen
- [ ] BLE sensors search crash - possibly related to the 2nd item
[exception (58).log](https://github.com/osmandapp/OsmAnd/files/11758644/exception.58.log)





<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/104760013/8a3bf29a-db57-4e7a-82b9-ebdd4a297e94"  width="300" height="auto"/> </th>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/104760013/14e17a7a-c286-4a4a-862e-9abf3ced80f7"  width="300" height="auto"/></td>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ed78c859-85ca-4b45-9768-97fc5f1b2f50"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Remove background below shadow

- - - - - - - -
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7514cb02-696c-4205-840b-eb15d61021a6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b3b1c745-f3d8-40e4-9c38-29d231e18764"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ]  List item is divided into two items, ScreenReader can't read Title and Value by one press. On other screens list item is implemented as one target.

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/plugins/external-sensors
- https://osmand.net/docs/user/plugins/trip-recording#recording-settings
- https://osmand.net/docs/user/widgets/info-widgets#-external-sensors-widgets
