### ISSUE TITLE
Truck Profile Hazardous Materials Issue

### ISSUE THREAD

**Issue by Farshief** [osmandapp/OsmAnd#15646]
### Description
The options under Tranporting of Hazardous Materials show options A-E for me in the USA where we use hazardous classes 1-9.

I've searched and the closest thing I could find A-E options for were the Netherlands but im not sure how that would translate into USA truck routing. I found no other guides which explained how to set up these options which makes this option effectively unusable in the USA.

### How to reproduce?
Settings->Truck->Navigation Settings->Route Parameters->Transporting of Hazardous Material

### Your Environment
OsmAnd Version:4.2.6
Android/iOS version:Android 12
Device model: SM-S906U

**Comment by xmd5a2** [comment]
Categories description
https://www.iafc.org/topics-and-tools/hazmat/fusion-center/transportation-commodities/dot-hazard-classification-system

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Allow to select few categories

**Comment by DmitryAlexei** [comment]
https://osmand.net/docs/user/navigation/routing/car-based-routing#route-parameters---truck

**Comment by dmpr0** [comment]
# Review 1
- [ ]  Fix separator distance from the right
- [ ] Increase back button touch target size to 48 dp 
- [ ] TalkBack, add indication of current state for class

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/navigation/routing/car-based-routing#route-parameters---truck
