### ISSUE TITLE
Base routing has disconnected road islands

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#15802]
Related issues (reverted / not fixed currently)

- [x] https://github.com/osmandapp/OsmAnd/issues/15384
- [x] https://github.com/osmandapp/OsmAnd/issues/14924
- [x] https://github.com/osmandapp/OsmAnd/issues/11770
- [x] https://github.com/osmandapp/OsmAnd/issues/17882
--------------------------- 

1. Algorithm find road clusters by simple connectivity (https://github.com/osmandapp/OsmAnd-tools/blob/fixBaseRoutingRoads/java-tools/OsmAndMapCreatorUtilities/src/main/java/net/osmand/obf/preparation/ImproveRoadConnectivity.java#L48) IMPROVE_ROUTING_ALGORITHM_VERSION = 2  (makeAreaDisconnectedPoints). 

Pros:
- Very simple implementation - 200-300 LOC 
- Very quick calculation (Denmark region - 30 second)
- Finds very few possible road isolations (100 for Denmark)
- Simple constants to control and possible to run few iterations

Cons: 
- Doesn't fix issue with oneways (https://github.com/osmandapp/OsmAnd/issues/14924)

2. Algorithm compare Base Routing vs Normal Routing - IMPROVE_ROUTING_ALGORITHM_VERSION = 1.
1) For all isolated points calculate 2 Dijsktra Algorithm on Base Routing and Normal Routing. **Start**: isolated point, **Stop** at 20 KM (Constant) from point
2) Compare reachable points, if base point wasn't reached by Base Layer Dijkstra but was reached by Normal Layer Dijkstra should be added "shortcuts" 

Pros:
- Finds all "missing routes" from isolated points
- Completeness

Cons:
- Doesn't find "missing route" between 2 parallel roads for example.
- Quite a lot of disconnected points present on some maps ~1000 and requires ~1000 requests

**Comment by vshcherb** [comment]
Test that mentioned cases are fixed with HH routing.

**Comment by RZR-UA** [comment]
Tests are done.

Summarized results marked in 1st message's todo list.

Detailed results and screenshots were added to the corresponding issues.

**Comment by vshcherb** [comment]
Tests to compare A* / HH - Java (Routing time & Geometry): 
- [ ] BRP (ok) HH (not-ok, **longer route!**) cpp (wrong) https://github.com/osmandapp/OsmAnd/issues/15384
- [ ] BRP (ok) HH (ok, **slightly faster**) cpp (ok) https://github.com/osmandapp/OsmAnd/issues/14924
- [ ] BRP (wrong) HH (**ok**) cpp (wrong) https://github.com/osmandapp/OsmAnd/issues/11770
- [ ] BRP=HH=cpp (all ok, but Web has issue) https://github.com/osmandapp/OsmAnd/issues/17882

**Comment by RZR-UA** [comment]
[html-report.zip](https://github.com/osmandapp/OsmAnd/files/14065806/html-report.zip)

![ok](https://github.com/osmandapp/OsmAnd/assets/90444451/8aa6d58d-b35b-49c5-91cf-9e2ce4cec2d8)

![2phase](https://github.com/osmandapp/OsmAnd/assets/90444451/22d8bdd6-4d81-4341-98fe-d353e7f9b6c9)
