### ISSUE TITLE
improve the speed limit margin

### ISSUE THREAD

**Issue by huitre39** [osmandapp/OsmAnd#15875]
Hi, when I want to set the margin before I get a speeding alert, I can choose between 0 and -5
Can you add more numbers? -1, -2, and -3 ?

it allows to adjust with the real speed between the car counter and the gps value

thank you in advance

**Comment by dmpr0** [comment]
## ToDo
We can change current UI with the list to something that will allows to select any value between current min. and max. parameters, for example slider.

<table style="width:100%">
  <tr>
    <th>Current</th>
    <th>New</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207337230-c354464b-cea9-46cf-ba7f-ce051a76563d.png"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by huitre39** [comment]
yes, it's a good idea

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14226mqta, Released: 2023-03-09
Done

**Comment by dmpr0** [comment]
# Review
- [ ]  Show selected value on the second line

**Comment by dmpr0** [comment]
# Review 
- [ ]  Hide **Speed limit tolerance** item if **Announce speed limit** is Off.

- - - - - 
### Crash

- [ ]  Fix crash with **Miles per hour**. Log [exception (1).log](https://github.com/osmandapp/OsmAnd/files/11052903/exception.1.log)
```
Exception occured in thread Thread[main,5,main] : 
java.lang.IllegalStateException: The stepSize(1.0) must be 0, or a factor of the valueFrom(-6.2)-valueTo(12.4) range
	at com.google.android.material.slider.BaseSlider.validateStepSize(BaseSlider.java:533)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:586)
	at com.google.android.material.slider.BaseSlider.maybeCalculateTicksCoordinates(BaseSlider.java:1476)
	at com.google.android.material.slider.BaseSlider.updateTrackWidth(BaseSlider.java:1497)
	at com.google.android.material.slider.BaseSlider.onSizeChanged(BaseSlider.java:1467)

```
#### How to reproduce
* Open **Menu** - **Settings** – **Walking** – **General settings** – **Units of Speed**
* Change **Units of Speed** to **Miles per hour**
* Go back to **Settings** – **Walking** – **Navigation settings** - **Voice prompts**
* Tap on **Speed limit tolerance**, crash

> Device : CAP_sprout
> Brand : Nokia
> Model : Nokia 5.3
> Product : CaptainAmerica_00WW
> Build : 00WW_2_290_SP04
> Version : 11
> App Version : OsmAnd~
> Apk Version : 4.4.0#14261mqta 4400
