### ISSUE TITLE
Make appearance of direction arrows similar to v1 engine

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#15980]
## Review
- [ ]  Arrows looks too big and arrow head is pixelated, can we use another image?
- [ ] Arrows size doesn't change with **Text size** or **Map magnifier** parameter.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/209835668-1b8f368f-a86c-468d-9380-00ae02b63fb7.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/209835679-3ec18c7e-b98a-4f77-a3e4-dd6863f70f8d.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

## ToDo
- [ ]  Align direction arrows apperance

OsmAnd 4.3 has introduced new **Map rendering engine(MRE)**: **Version 2 (OpenGL)** that has some difference in rendering map style, one of them is too contrast direction arrows. Can we change appearance of direction arrows to looks the same as in **Version 1** MRE.

<table style="width:100%">
  <tr>
    <th>Version 1</th>
    <th>Version 2 (OpenGL)</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207855781-dd7bc64d-1a86-4f63-96b9-3c97b9cc821e.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/207855773-0fe3d4f0-204b-4b94-8acb-f65845a33033.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

## Arrows size
In **Version 1** MRE direction arrow size changes with Map magnifier option, in **Version 2** MRE changing Map magnifier doesn't affect on arrows.
<table style="width:100%">
  <tr>
    <th>Version 1</th>
    <th>Version 2 (OpenGL)</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207888805-38b2755a-1231-4a6d-b252-dc7c371658b3.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/207888873-f5280d53-12ee-4f5c-9149-5c36da75036a.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by sonora** [comment]
Do we have an issue to systematically collect shortfalls or differences between v1 and v2 rendering?

Here is a small comparison which e.g. shows that in v2
- there seems a surplus extra line between a mountain peak icon and its label,
- or there seem contour line labels not visible in v1 in that magnification.

<img width="878" alt="v1" src="https://user-images.githubusercontent.com/845735/207885885-2be79327-d393-4f5b-8ba4-e5c55f4daca3.png">
<img width="827" alt="v2" src="https://user-images.githubusercontent.com/845735/207885928-17fadebb-937b-467e-8aed-94f2b09595cc.png">

**Comment by xmd5a2** [comment]
![Screenshot_2022-12-19_14-40-14](https://user-images.githubusercontent.com/5829014/208418549-3521ff87-5da1-43aa-aca4-2155e80aac60.png)

**Comment by xmd5a2** [comment]
@sonora Yes. Is is bad to mix different issues of different origin.

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14050mqta, released: 2022-12-27
The size of arrows in Legacy is different from the size of arrows in OpenGL + in iOS 4.4.2.1 arrows are displayed in blue

https://user-images.githubusercontent.com/104760013/209657752-64be08eb-762f-4eab-9399-39abee7bf551.mp4

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/209657746-beb4ad18-f2cb-4b5c-9992-fb702d79eab6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
