### ISSUE TITLE
Allow to search and choose icon for favorite from Custom POI Search

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16223]
-------------------
User case: It would be of great help if these were all selectable for personal favorites in the Add/Edit dialog. I like to give you an example: assume I find a shoemaker somewhere who is not yet marked as shoemaker in the OSM map. To add the shoemaker icon to a new favorite for that location
- I add the new favorite
- I have to look around where to find a location which has a shoemaker icon already
- create a temporary favorite for that location to make the icon available in the icon history area
- delete this temporary favorite
- search for the favorite I wanted to decorate originally and edit that one again to assign the desired icon from the icon history selection
I'm constantly fighting against this while travelling. It would be of great help to have all/most of the OSM icons selectable in the favorites icon menus.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1042025/213702250-0bc99220-3837-4047-ac61-206e8c3c9c71.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Currently it's a manual process cause it requires categorization

**Comment by vshcherb** [comment]
it's already working like you can add any favorite icon and  other icons needs to be properly categorized

**Comment by aarnolds** [comment]
Hi vshcherb,

great to hear that you added some functionality to choosing icons for favorites. I'm currently using 4.3.6. In which release will the change be activated. What's the procedure now if I want to use an icon not currently offered in the menu? Can I be of some help with categorizing icons?

Thanks and cheers, Ado

**Comment by scaidermern** [comment]
> it's already working like you can add any favorite icon and other icons needs to be properly categorized

Would it be possible to just re-use the POI categories? POIs are already categorized and POIs have icons -> icons are categorized. Simply re-use the POI categories to have categories for all available icons.

**Comment by aarnolds** [comment]
> ... POIs have icons -> icons are categorized. ...

That's a very good idea! There are some categories missing (like e.g. craftsmen [shoe maker, ceramist/potter], artists, ...) but is would be a very good starting point.

**Comment by MiMoHo** [comment]
> Would it be possible to just re-use the POI categories? POIs are already categorized and POIs have icons -> icons are categorized. Simply re-use the POI categories to have categories for all available icons.

Once a favorite place is created, the POI icon is determined by the map's POI when creating a favorite on an existing POI. But: when creating a POI on a blank map, no categorization is being made and the user can select the icon freely. However, there is just a small selection of icons in the categories _Recent_, _Special_, _Amenity_, _Transport_, _Service_, _Symbols_ etc. They are not always spot-on, or let's say one could place an icon in two or more categories like _Amenity_ and _Travel_. Searching for an icon that you don't know exactly how it looks like is time-consuming and it may not even be listed so you end up not finding it like a rubbish bin.
The current workaround is to search for an existing POI of the desired category, make this place a favorite, delete it and then create the actual favorite place by choosing the icon from the most recently used icons. However, this does not work with edited POIs as this leads to bug #18648 
@anastasiia936 made a very good request that I would like to see implemented as well! Let's get rid of the incomplete icon categories and let the user **text-search** for the desired icon to be used.

**Comment by dmpr0** [comment]
## ToDo

- [ ] We could get categories and icons hierarchy from Custom Filter. 
- - [ ] Don't show categories / icons with `ic_action_categories_search`, it used for typed without icon
- [ ] Leave **Special** and **Symbol** category as it is now. (Others hidden and should be tested for duplicates)

**Comment by e-pirate** [comment]
The idea of possibility to add any POI icon as favourites point icon was independently suggested in my feature request for favourites icons history synchronization between all account devices and web map that mentioned by @EugeneZmeuk in previous post. The workaround to achieve this action is the same as described - search for desired icon among POI, place temporary point to add desired icon to favourites icon history, remove temporary point and then use icon from history. The ability to choose icon directly from the sorted POI categories list as described on TODO above is a nice and demanded improvement.

**Comment by dmpr0** [comment]
# Review 
- [ ] Crash, searching for "pi"
* * Log file [exception (1).log](https://github.com/user-attachments/files/16280869/exception.1.log)

**Comment by vshcherb** [comment]
- Crash, searching for "pi" - not reproduced any more

**Comment by EugeneZmeuk** [comment]
**Docs**
- [ ] [Favorite appearance](https://osmand.net/docs/user/personal/favorites#create-and-edit): 
    - "You can select icon for your favorite from our list" change to "POI icons list" (while Android only)
    - Change screenshots (2 pcs): choosing icon (Android) and color (Android+iOS)
    - Change screenshot for "Add new category" (Android+iOS)
- [ ] [Waypoint appearance](https://osmand.net/docs/user/map/tracks/track-context-menu#add-waypoint-to-a-track)
   - the same

**Comment by vshcherb** [comment]
- [ ] New bullet point after (https://osmand.net/docs/user/personal/favorites/#edit-replace-and-delete) ``` ### Favorite icons ``` where we could make small screenshot and 2 sentences about big variety of icons. It could be embedded in Android / iOS block
- [ ] Waypoint (https://osmand.net/docs/user/map/tracks/track-context-menu/#add-waypoint-to-a-track) doesn't need to copy these screenshots and text but could point as link to (a big variety of icons is supported -> link -
