### ISSUE TITLE
Add a keybinding to switch to next profile

### ISSUE THREAD

**Issue by joostbijl** [osmandapp/OsmAnd#16327]
# 🚀 feature request

### Description

When you are riding on your motorcycle you have different needs (for Osmand) at different moments. A typical day for me would be that I start riding on an offroad trail using the osmand offroad map with very little detail other than tracks and hills. At some point I need fuel or food so i want a view that shows me fuel & supermarket PoI. At the end of the day I'm on the lookout for a camp site and like to see where they are, preferably on a regular street map so that i can quickly go there.

### Describe the solution you'd like

Osmand already has profiles that can be set up pretty much to suit each of these preferences described above.

I'm using a keyboard to control Osmand from the handlebars (https://jaxeadv.com/barbuttons/) and I'd like to be able to cycle through the different profiles. I'd be very happy if Osmand would go to the next profile when i hit 'P' on the keyboard.

### Describe alternatives you've considered

The alternative is that you stop riding, take off your gloves, open the hamburger menu, drop down the profiles, and select the right profile. Or you coudl search for a poi. Then put on your gloves and start riding.

I also created a ticket first in the iOS issues, but this applies to Android just as well: https://github.com/osmandapp/OsmAnd-iOS/issues/2476

**Comment by dmpr0** [comment]
## ToDo
- [ ]  **External input device**, by default set to **Keyboard**.
- [ ] Zoom in, bind to two keys, `+` and `=`. _(- make '=' equals '+')_
- [ ] Bind `Esc` to back? _(to close **Context menu** or **Modal views**)_
- [ ] Bind `N` to open **Navigation** view 
- [ ] Bind `S` to open **Search** view
- [ ] Bind `P` to switch to the next app profile. Show toast like message **App profile: Name**. https://github.com/osmandapp/OsmAnd-iOS/issues/2476
- [ ] Bind `O` to switch to the previous app profile.

**Comment by dmpr0** [comment]
# Review 
- [ ]  Generic keyboard's works even if disabled @vshcherb

**Comment by vshcherb** [comment]
- Generic keyboard should be enabled by default. For now we can remove option to completely disable keyboard and implement once we have request.

**Comment by dmpr0** [comment]
## Review 
- [ ]  Show toast message when switching between profiles.  "App profile: Name."
- [ ] Proposition to bind one key to center on location, `L` for example.

**Comment by shurasmiling** [comment]
[External input device – additional buttons](https://github.com/osmandapp/OsmAnd-iOS/issues/2698#top)
#2698
