### ISSUE TITLE
Allow to Download/Update online tiles setted as Overlay/Underlay

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#16362]
# Task
OsmAnd allows to use Online map tiles layers as **Map source**, **Overlay** or **Underlay layer**. When Online tile map layer is set as Map source, in map context menu two new options is available **Download map** and **Update map**.
- [x] Show and allow to use actions **Download map** and **Update map** in context menu when online layer is set as **Overlay** or **Underlay**.

------------------------
Skip for now
- [ ] Reset to default button doesn't work
- Download map and Update map buttons are not displayed in Context menu actions when selecting a POI on the map - Not reproducible
- Create or edit POI button has a different name in Context menu actions - Not relevant
-------------------------------

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/215823943-6a2f6fb0-f804-4ea2-9538-d5efa4ef429c.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/215823950-1fa5be2d-d572-429e-af31-718e656ab644.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/215823951-dc5f7b87-bfd0-457a-b2b2-9fc2d59d4296.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/215823956-fff56252-920b-494f-84f6-080a7eab7345.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/215824293-33c04fbf-f33e-404f-bffc-d33325d0b0be.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/215824305-ae4d8afa-24cb-4688-8dbc-2cf718f4d19f.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

https://user-images.githubusercontent.com/104760013/215824549-3628e254-7dfb-446f-8507-eb7b76b19c57.mp4

### Your Environment
OsmAnd Version: OsmAnd~ 4.4.0#14139mqta, released: 2023-01-31
Android/iOS version: Android 12
Device model: Poco x3 nfc

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14236mqta, Released: 2023-03-14
Done
**But** sometimes happens Crash during download map in Underlay (1/5)
[exception (37).log](https://github.com/osmandapp/OsmAnd/files/10970551/exception.37.log)

**Comment by dmpr0** [comment]
Documentation:
* We need to mention that now downloading online tiles are available: Overlay and Underlay too.

**Comment by dmpr0** [comment]
# Review
- [ ]  Crash [exception.log](https://github.com/osmandapp/OsmAnd/files/11051111/exception.log)
Set FiryHydrants maps as Overlay, try to launch Download Map.

> Device : CAP_sprout
> Brand : Nokia
> Model : Nokia 5.3
> Product : CaptainAmerica_00WW
> Build : 00WW_2_290_SP04
> Version : 11
> App Version : OsmAnd~
> Apk Version : 4.4.0#14261mqta 4400

**Comment by shurasmiling** [comment]
- https://docs.osmand.net/docs/user/map/raster-maps#download--update-tiles
- http://localhost:3000/docs/user/map/raster-maps#select-raster-maps
- http://localhost:3000/docs/user/map/map-context-menu#customize
