### ISSUE TITLE
Notes about current implementation: Configure Map / My Places Tracks

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16508]
OsmAnd is finally truly on its way to becoming a **GPX File Manager**.

Great work producing the new `Configure map >Tracks screen`! Here are some things to still consider:

- [x] **(1)** Still no sort functionality -> https://github.com/osmandapp/OsmAnd/issues/14890
- [x] #16725
- [ ] **(3)** A `Select all` / `Deselect all`  button or checkbox is missing on the individual folder tabs. And: only the "On map" folder tab needs a `Hide all` or `Select recent` button, not needed on the other tabs..
- **(4)** Should port the individual track actions to here (3-dot menu per track): `Show on map`, `Rename`, `Move`, `Share`. Also for folders.  -> _Will be only in My Places_
- [x] **(5)** We cut off the track name if it does not fit on two lines. But a good track management screen should be able to display track names completely. May perhaps be worked around by adding the `Rename` functionality, see above, where the full name would be displayed. (Some commercial tracks contain essential info at the end of the track name, e.g. difficulty ratings.)
 - [x] **(6)** On the folder-overarching tabs ON MAP and ALL, we show each track's folder in the column 4 of the sub-line,  but there is very little space on phones in portrait mode. Should use an additional line below for the folder name.
- [x] **(7)** The config screen "Track appearance" always opens with its bottom visible, but should show the top of the dialog.
- [x] **(8)** The section "On map / recently visible" seems only populated if you hide all tracks by directly using the toggle in `Configure map > Tracks,` but not if you use the `Hide all` button on the new dialog.
- [ ] **(9)** **Crash (NPE):** Perhaps by putting the screen to the background at the wrong time: [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/10788447/exception.log.txt) (EDIT: Have not observed any more lately).
- [ ] **(10)** Tab headers incomplete: https://github.com/osmandapp/OsmAnd/commit/215e4f273423387277c10df3427ec2a8e0ff496e#commitcomment-101388687
- [x] **(11)** **Crash (index-out-of-bounds):** Occurs if you tap the `Folders` button too soon after opening the Tracks screen: 
[exception.log.txt](https://github.com/osmandapp/OsmAnd/files/10797069/exception.log.txt) (EDIT: Seems fixed.)
- [ ] **(12)** User request: Add the ability to create a new folder.
- [x] **(13)** Only 1 level of sub-folders is supported, i.e. `<osmand data> / tracks / hikes / variants` is not be displayed in the 'Switch folder' list.
- [ ] **(14)** The setting "Show currently recorded track on map" if enabled is itself counted as a visible track, details see #16524. Also: As a result and/or due to additional bugs, the parent screen "Configure maps" often shows the wrong number of allegedly visible tracks in the small print in its line item 'Tracks'.
- [x] **(15)** The section "On map / recently visible" has the issue that successive showing and hiding **the same track** creates an concurrent entry for it both in lists "Visible" and "Recently visible". (This also creates successive hide/show misbehavior of  the "Recent" list.)
- [ ] **(16)** The section "On map / recently visible" further has issues with tracks which were renamed via their context menu while visible on the map (the old name gets added under "Recently visible", the new name is still under "Visible").
- [x] **(17)** Let's return to two-line tab headers like we had in the initial commit. Shortening to just one line does not display enough characters on many tabs to even identify which folder they belong to.
- [ ] **(18)** When tapping on the "Folders" button, then swipe-scrolling up through the folders list, the scrolling always gets stuck when the first line "On map" hits the top screen edge. You need to scroll again to continue.
- [ ] **(19)** If the name of a track file ends with `(a).gpx`, where _a_  is one or more arbitrary characters, that portion of the file name is not displayed!?! (Does not seem to happen iff the 'parentheses'-portion is somewhere in the middle of the file name.)
- [ ] **(20)** Several different screens shown intermingled: Open the new Tracks screen. Tap the device Home button. Open a file manager and tap on a gpx file to open in OsmAnd. OsmAnd will come back to the foreground with the Tracks screen showing (not the map with the track). Hit the decice'Back button. OsmAnd will display the Configure map screen  overlayed with the track context dialog, and some map widgets like the map scale indicator.
- [ ] **(21)** Decide if we want a tappable scrollbar to scrol the track lists, in particular the 'All 'tab can be quite long.
- [ ] **(22)** Use better line spacing to group items (and some other display-related suggestions), see #16676.

I think once these are resolved, this screen is functionally equivalent `MyPlaces > Tracks` and we could combine (#11336, https://github.com/osmandapp/OsmAnd/issues/16515#issuecomment-1441360752).

**Comment by sonora** [comment]
Plus: Related NPE: Probably had put the app in the background with the tracks tab still open: [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/10788447/exception.log.txt)

**Comment by anastasiia936** [comment]
Add the ability to create a new folder for tracks without leaving the My places ->Tracks folder

**Comment by sonora** [comment]
- [ ] **(13)** Other than `MyPlaces >Tracks`, which supports it ok, the new screen `Configure map > Track > Switch folder` seems to only support 1 level of sub-folders, to the effect that a folder `<osmand data> / tracks / hikes / variants` seems to not be displayed in the 'Switch folder' list.

**Comment by vshcherb** [comment]
needs sorting features - Search functionality is likely missing in configure maps but present in my places. Some features will be in 4.4 other in 4.5, so it's good to keep track of but it needs to be investigated.
@sonora you can update 1 topic issue to not produce other comments

**Comment by dmpr0** [comment]
- [ ] 3. We need to add search button to AppBar and open new screen
- [ ] 5. My Places > Tracks will be slightly different, but track item will be the same. I think we can show 3 lines of text for name.



6. This screen is manly used for on/off track on the map. Second line slightly change in depending on Sorting https://github.com/osmandapp/OsmAnd/issues/14890
12. I think **Add folder** is redundant here too, because main task is enable/disable tracks.

**Comment by sonora** [comment]
@vshcherb , @dmpr0 So what's our strategy here now, with Victor carrying this over to Milestone 4.5, and Dmytro only a few hours later removing it again and closing as completed?

There are a number of significant usability and strategic improvement possibilities in the items above, as well as some blockers which make portions of the new screen even in its very basic functionality rather unusable, like items (3) and (16). Overall, I have just re-tested everything and find only 8 of the currently 22 items truly fixed.

Even more important: I really vote for keeping this 'under steam' and developing it all the way, promoting it to it's full potential as a GPX File Manager?

**Comment by dmpr0** [comment]
> Even more important: I really vote for keeping this 'under steam' and developing it all the way, promoting it to it's full potential as a GPX File Manager?

Main purpose/goal/action of **this** screen (located in Configure Map > Tracks) is to manage track **visible** on the **map**.

**Comment by vshcherb** [comment]
Well this issue was helpful in the beginning but all almanach issues lead to collect everything that probably not going to be fixed.
Main misunderstandings:
- My Places  - GPX will be complete full action lists with editing, Configure Map -> Track will not pretend to replace it or be full the same
- Some features might take 1 release to implement, another 3 and another 1-2 years, so there is no sense to track them all in one issue

**Comment by sonora** [comment]
@vshcherb You know what, I think this is partly _mea culpa_, because the standard answer to your observation is that we (meaning also me) should somehow find a way to separate the
- (A) **operational line items** I gather from my testing and user feedback, i.e. bugs, regressions, and significant usability flaws, from the
- (B) **strategic deliberations**, i.e. how can we position OsmAnd better functionally, more agreeably or conventionally, which screens could be combined mid term to create more usability, user acceptance, etc.

While (A) items ("Issues") need short term fixing, I do believe that the more long running (B) items ("Strategic Ideas, over time developed into Guidance") are the precious ones for our way forward which really create value and progress for the product asymptotically. We should find a way to document and develop these, and mark which ones are "_accepted_" vs. "_suggested_", because exactly such a _modus operandi_ creates the lighthouse effect both for our developers and discussion participants.

Do we have such a repository of "strategic ideas" somewhere? I can think of a short list of "Issues" we had over time which would actually fall in there, while today as "github Issues" they have simply been closed, just because there was no short term plan or way to implement completely.

**Comment by vshcherb** [comment]
@sonora my experience tells me that 
- really annoying bugs get over all attention anyway whether it's a simple bug like collapse / uncollapse section or something complex. This deserves separate issues but they will be open regardless whether you create them in advance or not.
- There are small issues that are simple overlook, so like in this list you mentioned some of them are read and fix
- There are discussible issues that are not going to be implemented whether the target audience is very small or they go in conflict with other guidelines or a bigger target audience - also in that list

So most important is to collect and provide feedback while feature being implemented so in the easiest form and after that split them in group or individual and let it go to community decide whether it's real annoying or something very specific.

There is always time pressure to implement other features and not do 1 screen = 1 year, implementation takes a lot of time.

**Comment by vshcherb** [comment]
You can also see probably what's in our list for 2023 and it needs to be done somehow.

**Comment by sonora** [comment]
Sure, I will take the time and break out a few follow-ups.Current thinking is:

- (A) Usability: `Create Select all` /`Deselect all` buttons on the folder tabs

- (B) Functionality: #16725 already exists.

- (C) Usability: Add 3-dots menu for individual tracks actions: `Show on map,` `Rename`, `Move`, `Share`. `Show on map` is the most pressing, screen does currently not facilitate to find out where any individual track is actually located.

- (D) Strategic: Already in place: Combine our two Tracks screens, #11336, but we probably now wnat it on the new and not the old screen?

**Comment by sonora** [comment]
@vshcherb, @dmpr0 So would you say the tracks reworking is essentially finished, or have we closed this prematurely?

It is my impression with the numerous usability and stability issues we have now open, some of which do not receive much visible attetion, that we may have maneuvered this topic to an interim state where it is not truly usable, at least for GPX power users? Is anybody overlooking this topic overall who intensely uses OsmAnd for track management? Or would it help if I create a new super-issue at least referencing everything which has been raised about this epic in different issues subsequently?

We are giving awary huge potential if we test what we have only with a few tracks, thinking its only use is selecting 3 and show/hide them on the map. 😉 The requirements of our power users and issues they have exceed this by far! 😉

**Comment by dmpr0** [comment]
@sonora 
> @vshcherb, @dmpr0 So would you say the tracks reworking is essentially finished,

No

**Comment by vshcherb** [comment]
Based on reviews on main GPX tasks - UI is almost finished and should be usable. Certain features are not implemented and won't make 4.5 release likely. 

There is already a big list of UI small issues and improvements, so for now it makes sense only critical issues i.e. Apply sorting to folders.,  Random folder is open after adding new folder.

Usability issues need to be postopned

**Comment by sonora** [comment]
Ok, thank you both for the assessment!

Perhaps to just name two: Accidental deletion of tracks sounds real critical (#17522). And a "Select all" toggle per folder  is really a basic usability issue once you have a folder-organized collection of more than just a few tracks (#17103).

**Comment by vshcherb** [comment]
Accidental deletion of tracks sounds real critical (https://github.com/osmandapp/OsmAnd/issues/17522) - this is critical, if you reproduced it, I will reopen it.
