### ISSUE TITLE
Remove Proxy default settings

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd#16549]
Proxy is periodically randomly activated for some users, making it impossible to download maps (because the download map list is unavailable). 
Unfortunately, we do not have a pattern to reproduce bug (with random enabling Proxy), but if this setting is not necessary, please remove it. 
How the download maps menu displays, when the Proxy is enabled.

<img src="https://user-images.githubusercontent.com/80623554/221520320-5a2c9fc6-b52a-4c89-8d06-83fff6acab6d.png"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
## ToDo

**OsmAnd Settings**
- [ ]  Hide switch button on **Proxy** list item on **OsmAnd Settings** screen.
<img src="https://user-images.githubusercontent.com/9365308/221529897-7d6003af-9de4-4d7a-8dc9-52c04d3770c5.png"  width="300" height="auto"/> 

**Proxy**
- [ ]  Remove default **Proxy host**
- [ ]  Main switch  tap behaviour:
- - [ ] If Proxy host is empty, open Proxy host test field after taping.
- - [ ] If Proxy host is entered, turn on Proxy.

**Comment by dmpr0** [comment]
Crash 
Version  OsmAnd~ 4.4.0#14198mqta
27.02.2023 2:00:51
```
Apk Version : 4.4.0#14198mqta 4400
Exception occured in thread Thread[main,5,main] : 
java.lang.NullPointerException: Attempt to read from field 'android.widget.Editor$SelectionHandleView android.widget.Editor$SelectionModifierCursorController.mStartHandle' on a null object reference
	at android.widget.Editor$SelectionModifierCursorController.access$3900(Editor.java:6350)
	at android.widget.Editor$TextActionModeCallback.<init>(Editor.java:4080)
	at android.widget.Editor.startActionModeInternal(Editor.java:2381)
	at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:299)
	at android.widget.SelectionActionModeHelper.startSelectionActionMode(SelectionActionModeHelper.java:280)
	at android.widget.SelectionActionModeHelper.lambda$startSelectionActionModeWithSmartSelectAnimation$0$SelectionActionModeHelper(SelectionActionModeHelper.java:334)
	at android.widget.-$$Lambda$SelectionActionModeHelper$xdBRwQcbRdz8duQr0RBo4YKAnOA.run(Unknown Source:4)
	at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:342)
	at android.widget.SelectionActionModeHelper.lambda$l1f1_V5lw6noQxI_3u11qF753Iw(Unknown Source:0)
	at android.widget.-$$Lambda$SelectionActionModeHelper$l1f1_V5lw6noQxI_3u11qF753Iw.accept(Unknown Source:4)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:1034)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:988)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

```

**Comment by nazar-kutz** [comment]
**Pull Request**
* https://github.com/osmandapp/OsmAnd/pull/16855

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#14290mqta, Released: 2023-04-03 
Maine issue - Done

- [ ] Clicking on the icon should open a link to the documentation https://osmand.net/docs/user/personal/global-settings#privacy-and-security.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229490435-0c723186-a000-4c4c-8f5d-d39e2f02018b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review 
- [ ]  Open Keybaord when bottom sheet with TextField is opens
- [ ] Keyboard appears only after second tap
- [ ] Crash after entering Port number.

<table style="width:100%">
  <tr>
    <th>Keyboard behavior</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/230610263-8764c3dc-e0c8-4ece-8714-448ba6e1be3d.mp4"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by nazar-kutz** [comment]
**Fix ** https://github.com/osmandapp/OsmAnd/issues/16549#issuecomment-1500253522
* https://github.com/osmandapp/OsmAnd/pull/16951
