### ISSUE TITLE
Landing screen allow to choose data by type – Android Auto 

### ISSUE THREAD

**Issue by wolfsolver** [osmandapp/OsmAnd#16632]
# 🚀 feature request

### Description

On Android auto the favorite search show result from all categories as in this screen
![IMG_20230308_181617038_HDR.jpg](https://user-images.githubusercontent.com/3205448/223783346-fb209b23-5fa9-4ba9-bf5d-8831e07a32bc.jpg)

### Describe the solution you'd like
I have a lot of favourite, so is not agile to scroll list.

In my opinion is better to have 2 level navigation:
- first select favorite group
- second scroll favorite in selected favourite group

**Comment by Zirochkabila** [comment]
@wolfsolver This has already been implemented - try downloading the night version https://osmand.net/docs/versions/nightly_versions

**Comment by wolfsolver** [comment]
faster than thought!

I tried to install nightly build, but not visible in AA launcher. Anyway I joined to beta version on Google play, so waiting for normal release 

From my point of view Issue can closed.

**Comment by Zirochkabila** [comment]
Do this in AA https://github.com/osmandapp/OsmAnd-iOS/issues/2595

**Comment by dmpr0** [comment]
## ToDo
We need to redesign onboarding, to add ability to view POI, History, Favorites, Track and Markers independently.

**Comment by dmpr0** [comment]
## Review 
- [ ]  Map should show items from viewed group. Selecting POI Category of favorite group should update map and display all points from the group on the map



- - - - 
- [ ]  **Stop** button is lost?

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/252f4901-a1bd-45be-af05-3f71b205a19c"  width="480" height="auto"/> </td>
  </tr>
</table>

**Comment by wolfsolver** [comment]
Amazing! Just tested on AA and the new interface is exactly what I expected.

I do some test in a couple of days to give more details feedback

:)

**Comment by gena01** [comment]
So a few personal issues with the new UI:
1. Please please please add a "Home" button or top level item. (I guess Work or other pre-programmmed destinations could be added to) In Google Maps at least it usually shows up near the top in the search even though i wish there was a button for it. (I know this is is available in non Android Auto mode in Osmand like a pre-programmed destination). 
2. If I click on "Favorites"/Categories right after it pops open sometimes I get an empty list and I need to go back to the main pop dialog and try again in a few minutes until it loads.
3. In favorites the destination "estimate" tends to be a bit off, so  maybe don't show it or fix the estimation? 
4. If I use regular fuel in my car (which I can also configure in Osmand) when can we hide "Charging Station" category altogether? Or provide other means to disable certain categories in "Android Auto" dialog altogether. While driving common things I tend to look for along the route are: service/stop area, food and fuel/gas stations.
5. Add "Street Name" widget to AA mode. (Should I make a separate issue for this one?) I know Google Maps shows this information in their turn widgets. I know that voice guidance does say the street names during driving, wish I could see it too.
6. Add a button to toggle audible/voice guidance in AA. Google Maps has 3 modes: "all", "important" (turns, exits, etc) or none (quiet/no audio).

**Comment by dmpr0** [comment]
## Review 
- [ ]  Add possibility to increase radius for POI categories screen. Current is around 200 m, for Car is too small.
<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/952bb006-555b-417f-92f2-ca69cca92047"  width="600" height="auto"/> 

- - - -

**Comment by dmpr0** [comment]
# Review 
<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/392ebfc4-e8cc-4e65-b35d-f9645e99638b"  width="600" height="auto"/> 

- [ ] Calculated route only partially visible on the screen

**Comment by dmpr0** [comment]
# Review 4
- [ ]  Add **My location** button if possible

**Comment by vshcherb** [comment]
Reopen to fix History crash in G Play

**Comment by shurasmiling** [comment]
Button to hide Landing screen menu – Android Auto
