### ISSUE TITLE
Add Search to Configure Map > Tracks

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16725]
## ToDo
Add search to new **Tracks** screen in **Configure Map**.

## Tracks
- [x]  Add Search action to AppBar
- - [x] Icon `ic_action_search_dark`
- - [x] `android:contentDescription` = `Search`

<table style="width:100%">
  <tr>
    <th>AppBar</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/231990460-3f498748-874c-43fd-ad1e-76cacaad845a.png"  width="360" height="auto"/> </td>
  </tr>
</table>   

#### AppBar
- [x]  Back button `android:contentDescription` = `Back`
- [x] Clear button
- - [x] Show when something is typed
- - [x] `android:contentDescription` = `Clear search field`
- - [x]  Touch target size = 48 dp
- [x] Start state Text hint **Search track by name**

<table style="width:100%">
  <tr>
    <th>Start state</th>
    <th>Few tracks selected</th>
    <th>All tracks selected</th>
    <th>Empty state</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232034615-d049c4f5-d430-4a44-a8c2-c45d03fb6002.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/231966460-f13bb581-73af-4223-abfe-1bec92eecdec.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/231966468-e4257d8b-f10c-409c-88a3-4bdd445390c6.png"  width="180" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/231966470-d176b068-0b3e-4b6b-8bcb-57c9a074c2e1.png"  width="180" height="auto"/> </td>

  </tr>
</table>

**Comment by dmpr0** [comment]
## Review
- [ ]  Open keyboard by default

- - - - 

- [ ]  Update **On map** track list, after hitting **Apply** on Search screen
<table style="width:100%">

  <tr>
    <td>
<video source src="https://user-images.githubusercontent.com/9365308/235642521-7cffff6d-2079-4cef-b293-0f05f519c2d1.mp4"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#35904m, Released: 2023-05-07

- [ ] Request with a space after the name is not displayed (**"David"** - ok, **"David "** - doesn't display)
- [ ] Track sorting in the **On map** list does not update after adding a track





https://user-images.githubusercontent.com/104760013/236684013-237b7c11-882d-4511-be7f-da54fbe3cb97.mp4


https://user-images.githubusercontent.com/104760013/236684139-b6fa675d-1985-4180-8886-4801777606c7.mp4

**Comment by vshcherb** [comment]
To do search doesn't search:
"mon" in "15_25_Monday"
“15_25 “ - 2023_15_25_13”
"David " in "David"
"munchen" does not find "München".

**Comment by sonora** [comment]
@vshcherb I guess no results for
> “15_25 “ - 2023_15_25_13”
> "David " in "David

is strictly speaking correct, or why would we ignore a blank if a user explicitly typed one?

**Comment by vshcherb** [comment]
@sonora we should trim all user inputs remove space before and especially after - that's a traditional

**Comment by sonora** [comment]
Yeah, probably true, but it may be unecpected or inconvenient.

I sometimes search for strings like "San " to find the pattern "San XXX", at the same time excluding all concatenations like "Santa" or "Santo", "Sangre" etc.. In most search engines you would be able to search for an axact pattetn at least if you put your search string in quotation marks, but that we don't support, I think...

**Comment by sonora** [comment]
Just tested today's nightly: When using the track search, Android now often reports the app is not responsive, and the search or trying to scroll any results is now extremely laggy. (Seems caused by today's fixes, not yet observed yesterday).

**Comment by Zirochkabila** [comment]
@sonora I did not notice this behavior in today's [nightly version](https://download.osmand.net/latest-night-build/OsmAnd-android-full-arm64.apk)

**Comment by sonora** [comment]
For me it's a lot more crippled than your video shows: As soon as I type a single character in the search slot,  the app essentislly stalls. Subsequently typed characters take minutes to even show up, and the list of results is practically unscrollable. After a while Android reports the app as unresponsive.

It seems independent of how many tracks are visible on the map. But is probably related to how many tracks you have on the device.

May be some constant sorting going on, perhaps on the hundreds of results after having typed only a single character, or similar.

The issue was not present until the May 9 commits.

**Comment by sonora** [comment]
And here is an NPE which occurs if you tap rhe search button too quickly after entering the screen: [exception.log.txt](https://github.com/osmandapp/OsmAnd/files/11456201/exception.log.txt)

**Comment by sonora** [comment]
@Chumva  The app freeze can be traced back to exactly this change

![image](https://github.com/osmandapp/OsmAnd/assets/845735/0e0aa143-4c90-4b01-be66-a7163ef092f8)

in https://github.com/osmandapp/OsmAnd/pull/17146. Reverting that single line makes the search **instantaneous**, and no freeze any more.

The search results seem to also be ok, from what I see, **with one weird exception**: Searching for an expression fails to produce all search results where that expression is immediate preceded by an underscore "_":
- E.g. searching for "Fri" will produce search results like "Africa" ok,
- but will not produce any tracks recorded on a Friday, i.e. with "_Fri" in their name. 
- Searching for "_Fri" fails also.
- But searching for just "ri" will produce them ok!

So the question is: _What is special about the underscore in the file name?_ If we solved that question, we could likely go back to use the fast `itemObject.name.contains` instead of the laggy collator, and be done with this issue?

**Comment by sonora** [comment]
I've just checked and this is the best I've seen so far!

There is now a noticeable delay of about 3 seconds every time I tap the 'Search' button (on the` Configure map > Tracks screen`), but after that the search is instantaneous, also instantly responsive to when you type additional characters, and also scrolling is now responsive.

What is harder to check is if the search results are complete.
- [ ] Could we maybe put the number of found hits in parentheses after in the caption of the `SELECT ALL` button, in the fashion `SELECT ALL (7)` etc.? Then it would be much easier to check, because I can correlate to how many tracks fitting the search I have in the file system.  May also be a useful feature to make people aware to not accidentally select hundreds of tracks on the map, which would cause as subsequent map performance issue.

**Comment by sonora** [comment]
@Chumva  Here's asmall glitch still: If you start the search on the "All" or any of the subfolder tabs, each search result will correctly display the containing folder as well (as is needed for identification). But if you start the search while the "On map" tab is displayed (as is default when entering the screen), each search result suppresses its folder line display.

**Comment by Chumva** [comment]
@sonora folder names in items description also [depends on the sort type](https://github.com/osmandapp/OsmAnd/blob/33deacb0e44fd19cf0f5c554a8e2a2ad04005b4e/OsmAnd/src/net/osmand/plus/configmap/tracks/viewholders/TrackViewHolder.java#L297)

**Comment by sonora** [comment]
I had already implemented the count (https://github.com/osmandapp/OsmAnd/commit/c86d826a9ef4c6071f40725d2dca7da7b2df4d72), needed it for the testing if we now reliably find all related hits. But I think it is a useful feature to leave in place: It creates the awareness of how many tracks you are about to make visible, something otherwise obscured.
