### ISSUE TITLE
Navigation History: displays points used in Navigation

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16895]
## ToDo
> [Note:](https://github.com/osmandapp/OsmAnd-iOS/issues/1757#issuecomment-1479419548) Android should be fixed as well so Navigation History only displays points used in Navigation

History – Navigation, should displays only points used in Navigation, currently **Search history** and **Navigation history** in **OsmAnd Settings** - **History**, shows almost the same list of items.

- [x]  Show points used in Navigation. (**OsmAnd Settings** - **History** - **Navigation history**)

**Comment by dmpr0** [comment]
## Review 
- [ ]  Allow to export separately. Add separate items to Export: Search history, Navigation history.
- [ ] Share on each screen opens wrong share sheet.
