### ISSUE TITLE
Show Contour lines if Map source is Online map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#16912]
## ToDo
Version 1 of Map rendering engine doesn't support show contour lines if Map source was set to any Online tile map. With Version 2 map rendering engine it possible.

- [x]  Show Contour lines if Map source is Online map
- [x]  Use 3D maps when Map source is Online map

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.5.0#90m, Released: 2023-05-25

- [ ] V1 + Online map - Contour lines don't show


https://github.com/osmandapp/OsmAnd/assets/104760013/8d1df5ec-1f14-4490-b27e-1fbe77dbf86c

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/global-settings#map-rendering-engine
https://osmand.net/docs/user/map/raster-maps#3d-relief
https://osmand.net/docs/user/plugins/contour-lines#contour-lines
