### ISSUE TITLE
Configure Map > Tracks: Add "Select all" / "Deselect all" button

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#16913]
For the sake of usability, a `Select all `/ `Deselect all` button or checkbox is needed on the individual folder tabs.

Plus: Only the "On map" folder tab should show the curretnt `Hide all` and `Select recent` buttons: Both functions relate to what currently is or recently was displayed on the map, so on the individual folder tabs this functionality is misleading.

**Comment by dmpr0** [comment]
# ToDo


<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>On Map</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7a0dad95-0907-4252-b032-8d8b3af8f023"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/619f8b5f-0265-4c91-88ac-b35c1f6cbd9b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6ffad516-f66a-444f-9b46-cf3c2f1d0776"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>  


- [ ]  Show **Hide all** / **Select recent** button for **On Map** tab
- [ ] Show **Select all** / **Deselect all** buttons for all other folder related tabs.

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Video</th>
    <th>Selected tracks</th>
    <th>Result</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/91501ab0-87ca-4496-8ede-28e2745d0736"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3a004da2-e15d-41d8-bdad-7844015910da"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/adc22033-92b7-4ee1-9fbf-bfecc8c55317"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ]  Select all, sometimes doesn't work. Log file [logcat (1) (1).log](https://github.com/osmandapp/OsmAnd/files/12882806/logcat.1.1.log)
