### ISSUE TITLE
Add Android Location services for OsmAnd Tracker

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#16933]
## ToDo

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <th>Settings</th>
    <th>Location source</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7aab2e7c-e31b-46e6-bf1c-824ec4c30f8c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0a77a347-bf94-49d7-ac12-4bea538e7403"  width="300" height="auto"/> </td>
  </tr>
</table>  

</details>  

### Settings, [Figma](https://www.figma.com/file/WWwm5hKg2KSrxYuXHIXEalT7/OsmAnd---GPS-Tracker?type=design&node-id=180-19226&mode=dev) 
- [x] Add new option **Location source**, with two parameters:
- - [x]  **Google Play Services** - set by default
- - [x] **Android API**
- [x] Show bottom sheet on tap

- - -

<details>
    <summary>Original request</summary>

OsmAnd tracker (https://osmand.net/docs/user/plugins/osmand-tracker/) uses only Google location service. If the smartphone doesn't have Google Play service OsmAnd tracker doesn't find the location.

We need to add choosing of Location service (https://osmand.net/docs/user/personal/global-settings#location-source) for OsmAnd tracker:
Google Play or "Android API"

</details>

**Comment by juanro49** [comment]
Hi!

Are there any news about this? 😊

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Crash</summary>

```
FATAL EXCEPTION: main
    Process: net.osmand.telegram, PID: 19681
    java.lang.NoClassDefFoundError: Failed resolution of: Lgnu/trove/map/hash/TIntObjectHashMap;
    	at net.osmand.util.MapUtils.<clinit>(MapUtils.java:621)
    	at net.osmand.telegram.TelegramLocationProvider.getAngle(TelegramLocationProvider.kt:320)
    	at net.osmand.telegram.TelegramLocationProvider.updateCompassVal(TelegramLocationProvider.kt:314)
    	at net.osmand.telegram.TelegramLocationProvider.onSensorChanged(TelegramLocationProvider.kt:262)
    	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:1069)
    	at android.os.MessageQueue.nativePollOnce(Native Method)
    	at android.os.MessageQueue.next(MessageQueue.java:344)
    	at android.os.Looper.loopOnce(Looper.java:189)
    	at android.os.Looper.loop(Looper.java:317)
    	at android.app.ActivityThread.main(ActivityThread.java:8501)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
    Caused by: java.lang.ClassNotFoundException: gnu.trove.map.hash.TIntObjectHashMap
    	at net.osmand.util.MapUtils.<clinit>(MapUtils.java:621) 
    	at net.osmand.telegram.TelegramLocationProvider.getAngle(TelegramLocationProvider.kt:320) 
    	at net.osmand.telegram.TelegramLocationProvider.updateCompassVal(TelegramLocationProvider.kt:314) 
    	at net.osmand.telegram.TelegramLocationProvider.onSensorChanged(TelegramLocationProvider.kt:262) 
    	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:1069) 
    	at android.os.MessageQueue.nativePollOnce(Native Method) 
    	at android.os.MessageQueue.next(MessageQueue.java:344) 
    	at android.os.Looper.loopOnce(Looper.java:189) 
    	at android.os.Looper.loop(Looper.java:317) 
    	at android.app.ActivityThread.main(ActivityThread.java:8501) 
    	at java.lang.reflect.Method.invoke(Native Method) 
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
```


</details>  



- [ ] Unable to test, crash
