### ISSUE TITLE
Widgets / Recording -  BLE/ANT+

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17200]
# ToDo
 BLE/ANT+ Widgets And Trip Recording
Refactoring: 
- Select Source per Widget and Trip Recording Setting

## Configure Screen
- [x] Widgets should be visible and be able to be added, no matter if any sensor is connected
- [x] Widgets should be able to be added to the panel, no matter if any sensor is connected
- [x] Add **Settings** for each external sensors widget.
- [x] Add option **Source of data**
- - [x] Taping **Source of data** should open **Paired sensors** screen

<table style="width:100%">
  <tr>
    <th>Sensor settings</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/7bce56d4-8f22-4b20-8b9f-8d1bd450b8db"  width="300" height="auto"/> </td>
  </tr>
</table>   

&nbsp;

## Trip recording plugin, [Figma](https://www.figma.com/file/psbEg4fXLWWTl3r2JlCExd/Plugins?type=design&node-id=2192%3A50742&t=Gf5yz4wiDvlPvGeq-1)

- [x]  Add new group **Data**
- [x] Add new item **External sensors**
- - [x] Visible only if **External sensors** plugin is on
- - [x] Tap opens new screen **External sensors**
- [x] **External sensors** Second line: 
- - [x] Show None if any data type are linked with sensors, 
- - [x]  Show list of linked data types.

### External sensors
* The screen allows to select sensor for each data type. 
* OsmAnd will write data for selected type into a track while trip recording.

- [x]  Show five supported data types
- [x] **Speed**, icon `ic_action_speed_outlined`
- [x] **Bicycle cadence**, icon `ic_action_sensor_cadence_outlined`
- [x] **Bicycle power**, icon `ic_action_sensor_bicycle_power_outlined`
- [x] **Heart rate**, icon `ic_action_sensor_heart_rate_outlined`
- [x] **Temperature**, icon `ic_action_thermometer`
- [x] Tap on any data type, will open **Paired sensors** screen

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/87065edb-85e5-47b9-bae1-24c83dd54729"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/253b32b1-28aa-43b3-a2fe-dab50c130274"  width="200" height="auto"/> </td>
  </tr>
</table>

## Paired sensors
- [x] Show list of **paired** sensors matching by data type. List should contain connected and disconnected sensors.
- [x] Tap in any item, should select it and close the view
- [x] Add button **Pair new sensor**, tap should launch searching process 

<table style="width:100%">
  <tr>
    <th>Paired sensors</th>
    <th>Paired sensors: Empty state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1fd62d2c-a4b0-4b2f-a259-934f9edd03a5"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/76bcaef2-942d-47db-acf2-ca742f3eb869"  width="200" height="auto"/> </td>
  </tr>
</table>

**Comment by JakDoh** [comment]
It would be good to have an additional layer that ensure authentication (CHAP or so) with the sensor (like for MiBand and other brands of wristbands) before reading data from the sensor.

**Comment by dmpr0** [comment]
# Review
- [ ]  Show sensor name
- [ ] Allow to select only proper type sensors
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/290b4e15-a4c9-47ce-9404-9c8ca3627258"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/39bb2712-5591-4c2c-9564-2f16b05c63a3"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
**Doc:**
`<osmand:heart_rate_sensor>`
`<osmand:speed_sensor>`
`<osmand:bike_cadence_sensor`>
`<osmand:power_sensor>`
`<osmand:temperature_sensor>`

**Comment by dmpr0** [comment]
# Review 2
- [ ]  Reset **Trip recording plugin** settings to default, doesn't reset selection for **External sensors**.

**Comment by dmpr0** [comment]
> Settings are related to External Settings Plugin and displayed only with External Sensors plugin enabled.

Settings related to Trip recording, (thats why, they placed here) relate to data that will be or not recorded to the track. You can change mentioned settings in External sensor plugin settings.

**Comment by vshcherb** [comment]
Settings than should be always visible even if External sensor plugin is disabled

**Comment by dmpr0** [comment]
https://en.wikipedia.org/wiki/Trip

**Comment by vshcherb** [comment]
Well we could make Trip Recording part of Default functionality especially now we have Trip Recording as Drawer item. Then we can move Trip recording settings to BLE Plugin

**Comment by shurasmiling** [comment]
All links are in this issue:
[BLE/ANT+ Management Sensors](https://github.com/osmandapp/OsmAnd/issues/15459#top)
#15459
