### ISSUE TITLE
HELP: Replace offline outdated help with online links

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17228]
# ToDo
Related to Android / iOS.
Offline Cache is preferable once page is open
https://creator.osmand.net:8080/view/Web/job/WebSite_UpdateWeb/ws/mobile-package.zip (63 MB)

<table style="width:100%">
  <tr>
    <th>Help</th>
    <th>Menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/903de941-958d-4106-b194-c1f71b06314b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c4190739-3cea-4e8d-a53d-b08ab6364b4d"  width="300" height="auto"/> </td>
  </tr>
</table>   

## AppBar

**Menu**
- [x]  Add Menu button, with three actions
- [x]  **Share crash log**
- - [x] Icon `ic_action_bug_outlined_send`
- - [x] Tap, send exception.log
- [x]  **Send logcat log**
- - [x] Icon `ic_action_file_report_outlined_send`
- - [x] Tap, send logcat log
- [x] **Copy build version**
- - [x] Icon `ic_action_osmand_logo`
- - [x]  Tap should copy buld information

## Most viewed

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/82f465f8-4495-40f2-9fb8-4de67179bb85"  width="300" height="auto"/> </td>
  </tr>
</table>   
Card with the list of most viewed articles.

- [x]  Use file to get most viewed articles https://github.com/osmandapp/web/blob/main/main/static/help-links-android.json
- [x]  Show list of 5 top viewed articles 
- [x] Use icon `ic_action_file_info`

## User guide
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/1b32724a-022c-4fb1-ad5c-a9f41a72451a"  width="300" height="auto"/> </td>
  </tr>
</table>   
Card with the list on links to user guide categories similar to docs.osmand.net

- [x]  Icon `ic_action_book_info`

## Troubleshooting
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d076286e-18f9-417a-a435-c9c8e9d00d27"  width="360" height="auto"/> </td>
  </tr>
</table>   

## Contact us
<table style="width:100%">
  <tr>
    <th>Contact us</th>
    <th>Telegram chats</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6b3fd5fa-b8fd-4a15-9fe6-5f55c319742a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/053573ef-57a9-4b87-b5a9-72423088878d"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x]  **Contact support**
- - [x] Icon `ic_action_at_mail`
- [x] **GitHub Discussion**
- - [x] Icon `ic_action_social_github`
- [x] **Telegram chats**
- - [x] Icon `ic_action_social_telegram`
- - [x] Tap open new screen with the list

## Report an issues
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4cc0f842-1ff6-4e87-8a74-c38408b9b762"  width="360" height="auto"/> </td>
  </tr>
</table>   

Separate card with the button to repost issues or send log files.

- [x]  **Open issue on GitHub**
- - [x] Icon `ic_action_social_github`
- - [x] Link `https://github.com/osmandapp/OsmAnd/issues`
- [x]  **Share crash log**
- - [x] Icon `ic_action_bug_outlined_send`
- - [x] Tap, send exception.log
- [x]  **Send logcat log**
- - [x] Icon `ic_action_file_report_outlined_send`
- - [x] Tap, send logcat log

## About OsmAnd
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/88355c6d-f60f-4a4a-8871-ab0f398f2ad7"  width="360" height="auto"/> </td>
  </tr>
</table>   

- [x]  **About OsmAnd**
- - [x] Icon `ic_action_osmand_logo`
- - [x] Link `https://docs.osmand.net/help-online/about`
- [x]  **What’s new**
- - [x] Icons `ic_action_clipboard_notes`
- - [x] Link 
- - [x] Show version number on second line
- - [x] Long tap on list item should copy build number to clipboard
- [x]  **Free versions**
- - [x] Icon `ic_action_gsave_dark`
- - [x] Link  `https://docs.osmand.net/docs/versions/free-versions`

**Comment by vshcherb** [comment]
https://docs.osmand.net/sitemap.xml - list of docs (https://osmand.net/docs/user/)

**Comment by Kochemnik** [comment]
maybe worth adding?
What's new in 4.5.x:
https://github.com/osmandapp/OsmAnd/milestone/38?closed=1

**Comment by dmpr0** [comment]
# Review
- [ ]  Shadow is missed below last card

**Comment by vshcherb** [comment]
@sonora It looks like when you are on a sub-menu in the Help screen, e.g. on Help>Map legend, the "back" arrow (top left on the scren) has no effect.
(The device back ley works, and also otworks on the top screens it seems to work, though.)

**Comment by sonora** [comment]
@vshcherb , @Chumva , @dmpr0 It's a very reasonable idea, boosting quality, to make our web site documentation also the basis for our "Help". It was just not manageable to have good and updated information in sync in the website docs and for the Help files separately...

**Comment by sonora** [comment]
@vshcherb  Two suggestions:

- We should move the version subtitle (and the corresponding long-tap copy)  from the "What's new" item to the "About OsmAnd" line item. It 's more conventional there. (And the "What's new" article usually refers to the _major_ release, which is stated in the article headline anyway.)

- For the actual "About OsmAnd" article, we now solely rely on the online article. Would we not like to hardcode this one back in the app?

**Comment by Chumva** [comment]
@sonora probably we will add full offline support for some articles, but now they are cashed after an article is open (it is saved as .mht file in cache dir) and then should be available offline

**Comment by sonora** [comment]
Yes, I'm less worried about any help articles not being available offline. But I guess we may continue to bundle our "About" directly in the apk?

**Comment by EugeneZmeuk** [comment]
**Review 18.03.2024:** [article link](https://osmand.net/docs/user/start-with/first-steps#offline-help)
- [ ] [Troubleshouting](https://osmand.net/docs/user/start-with/first-steps#troubleshooting): Android and iOS description
- [ ] added more links for crash log, Logcat log, Send log

**Comment by EugeneZmeuk** [comment]
**Review 25.03.2024**
- [ ] check and change screenshots (Android and iOS)
