### ISSUE TITLE
Show all widgets added by user during Navigation.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#17267]
## ToDo
We have merge top/bottom panel widgets in https://github.com/osmandapp/OsmAnd-Issues/issues/1890 and fix disappearing of Map marker widgets from the map during navigation #16171, we need to do it we the rest widgets too.

Don't hide this widgets in Navigation:
- [x]  Coordinates: Map center
- [x] Coordinates: Current location
- [x] MapMarkers TopBar

**Comment by nazar-kutz** [comment]
**Pull Request**
* https://github.com/osmandapp/OsmAnd/pull/17314

MapMarkers TopBar Fixed. 
Coordinates (Map center / Current location) widget seems already stay visible during navigation so there is no needed to fix.

**Comment by dmpr0** [comment]
# Review
- [ ]   **Street name** widget doesn't visible in **Bottom panel** in Landscape mode. 
* Profile + Settings Export [Export_2023-06-02.osf.zip](https://github.com/osmandapp/OsmAnd/files/11634436/Export_2023-06-02.osf.zip)

<table style="width:100%">
  <tr>
    <th>Portrait</th>
    <th>Landscape</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4a47df88-a735-44de-871e-cde9877ac90c"  width="300" height="auto"/> </td>
    <td valign=top><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eb330dd2-d21b-4b79-b748-0f4e12c5d451"  width="500" height="auto"/> </td>

  </tr>
</table>
