### ISSUE TITLE
Via ferrata should be supported in Pedestrian routing

### ISSUE THREAD

**Issue by pozzobonf** [osmandapp/OsmAnd#17301]
# 🐞 routing report

### Routing engine

- [X] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Pedestrian - default

### Start and end points

Start: [Rifugio 7° Alpini, Sentiero Sperti, Belluno, Veneto, Italia](https://www.openstreetmap.org/way/111825720)
End point: [Bivacco Ugo Dalla Bernardina, Sentiero Sperti, Belluno, Veneto, Italia](https://www.openstreetmap.org/way/111825992)

### Actual and expected routes

I am expecting the route to take the Via Ferrata Zacchi, instead of avoing it
Image: https://drive.google.com/file/d/1rLpIsfhIxMVxHwh2SEIa_MN1S_PLg4eq/view?usp=drive_link
Video: https://drive.google.com/file/d/12bocrrqEiF8pDlJB_Vw0S5Fr61N8-Xa3/view?usp=sharing

This is an example, but it general it avoids any Via Ferrata. In the video I have some configurations different from the pedestrian default, but the behaviour is the same also with the default. 

### Is this a regression?

Yes, it worked in the past since I always used OsmAnd for doing Via ferrata. I'm not sure which version it was. 

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.4.7 (it happens also in 4.5.0)
</code></pre>

**Device and Android/iOS version:** One Plus Nord - Android 12

**Maps used (online or offline):** Offline

- [X] Offline maps offered within the OsmAnd app for download.

- [ ] Online (tile / raster) maps 

**Anything else relevant?**
It seems not a problem due to the "existence" of the path, in fact if I select the specific path (https://drive.google.com/file/d/112cYwm-BmleMDyWq0JmwGBTTzcltR3_m/view?usp=sharing) and navigate it, the via ferrata is included. Instead, if it is an automatic route creation it avoids it. So it seems smth about a  more aggressive cost for the slope variable, like it it prefers avoiding shorter paths that have a steeper slope.

**Comment by scaidermern** [comment]
There should be a setting in the foot profile to allow or disable [via ferratas](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dvia_ferrata). Via ferratas are sections that are both difficult and (for unexperienced people) dangerous, so this setting should be off by default. Nevertheless, OsmAnd should support these since some users want to take them on purpose.

**Comment by pozzobonf** [comment]
Sorry @scaidermern , you mean that is the issue is solved that setting should be added, or I should be already able to find it? Because I can't really find it, and in the docs I can't find anything about that.. in case it exists, can you please send a screenshot so I will open a pull requests to the docs in order to improve them and close the issue? Thanks

**Comment by scaidermern** [comment]
> Sorry @scaidermern , you mean that if the issue is solved that setting should be added, or should I be already able to find it?

No, sorry if I wasn't clear enough. I support your request and I suggest to make this configurable. That's all :)

**Comment by vshcherb** [comment]
- Still not clear do we have that option (routing as pedestrian via ferrata) ? Is it on or off by default? 

In Plan Route it's possible to change route parameters

**Comment by xmd5a2** [comment]
OsmAnd never supported via ferrata routing. I've added corresponding option to pedestrian routing settings: "Allow via ferrata". @dmpr0

**Comment by dmpr0** [comment]
## ToDo
Update UI

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f30aa46a-2d20-4a9e-b6c2-fcd1f24610e1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/774f9bf0-aba1-4bfc-a8fa-50f29a74b530"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/145c8c61-3b6d-42c8-8363-a7459c846eb1"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review
- [ ]  **Via ferrata** is ignoring? if **Use elevation data** is on. Example https://www.openstreetmap.org/way/289925018#map=19/47.16476/10.59332

<table style="width:100%">
  <tr>
    <th>Use elevation: Off</th>
    <th>Use elevation: On</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b9635206-2719-4c74-8247-baba5266f795"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0670096d-43bd-4877-8a4f-52d0ad6ef077"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Cost: 5192 - https://test.osmand.net/map/?start=47.165193,10.592937&end=47.164976,10.594060&type=osmand&profile=pedestrian&params=pedestrian,allow_via_ferrata#19/47.16496/10.59318
Cost: 5296 - https://test.osmand.net/map/?start=47.165027,10.592558&end=47.164976,10.594060&type=osmand&profile=pedestrian&params=pedestrian,allow_via_ferrata#19/47.16496/10.59318

If time is correct 0:20 vs 0:45 via ferrata should have lower cost

**Comment by xmd5a2** [comment]
Fixed. Now elevation data are not taken into account when `highway=via_ferrata` + `Use elevation data`.
![изображение](https://github.com/osmandapp/OsmAnd/assets/5829014/75a80487-0518-4006-87d6-eaf809e69f70)

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#813m, released: 2023-09-28 iOS testflight 4.5.2.2
- works correctly on web and in the apps (iOS and Android) when *use elevation data* and *Mountainside route (via ferrata)* are enabled
- **in iOS Mountainside route (via ferrata) option is called *Allow via ferrata***
https://test.osmand.net/map/?start=47.165193,10.592937&end=47.164976,10.594060&type=osmand&profile=pedestrian&params=pedestrian,allow_via_ferrata#19/47.16496/10.59318

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/12665e0a-82d8-412b-96e7-10cf472ba273"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/33aa50a8-461e-4f6e-bde9-84cbd5fcb9b9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/db5d22b8-09a6-405b-b799-af17fa91e21f"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Docs: 
- added info about *Via ferrata* to the table in https://osmand.net/docs/user/navigation/routing/pedestrian-routing#route-parameters---walking 
- screenshots with pedestrian routing settings were changed
