### ISSUE TITLE
Coordinates widget: reuqest to add EPSG 2039 or 6991

### ISSUE THREAD

**Issue by playmobilmeister** [osmandapp/OsmAnd#17311]
# 🚀 feature request

### Description

Much publicly available local geographical data info, as well as the vast majority of historical data is available only in EPSG 2039 (ITM). Therefore, when navigating in a field trying to find something according to its ITM coordinates , It's sometimes easier to just have a printed map at hand. I would like to use OSMand for such navigation  (and recording new data, possibly)

### Describe the solution you'd like

Add the CRS: EPSG 2039 (ITM 1993) (or [EPSG 6991](https://epsg.io/6991) ) to the profile units configuration options.

### Describe alternatives you've considered

There's a lame paid close source option which I'd rather not use. The other option is to to pre-transform data to the approproate UTM strips and the use that. The problem, in my case - is that it's often not exact enough

**Comment by vshcherb** [comment]
Looks like we need to support much more national geo systems - https://epsg.io/28992, https://github.com/osmandapp/OsmAnd/pull/24833

``` EPSG
Projection - Conversion -> Method - name
2039 6991 - Isr projected - (18204) -> 9807 - Transverse Mercator
28992 - NL projected - (19914) ->  9809 - Oblique Stereographic (   PROJECTION["Double_Stereographic"])
21781 - Swiss projected - (19922) -> 9815 - Hotine Oblique Mercator (variant B) (PROJECTION["Hotine_Oblique_Mercator_Azimuth_Center"])
5561? - 5562 - UCS-2000 / Gauss-Kruger zone 4 (PROJECTION["Gauss_Kruger"]) -  
с Transverse Mercator) ( PROJECTION["Transverse_Mercator"])
25832 - ETRS89 / UTM zone 32N (16032) -> 9807 Transverse Mercator
```

**Comment by vshcherb** [comment]
- [x] First step we need to check API to search / select and transform coordinates by EPSG notation

**Comment by Andrewschenko** [comment]
An externally available object CoordinateTransformer was [added](https://github.com/osmandapp/OsmAnd-core/pull/1056). 
The first parameter has to be the current path to the locally available proj.db file -
OsmAnd for iOS: QString::fromNSString([NSHomeDirectory() stringByAppendingString:@"/Library/Application Support/proj"]))
OsmAnd for Android: app.getAppPath(null).getAbsolutePath()
The second parameter is the code of needed EPSG CRS (i.e. integer value 2039 for EPSG:2039)

**Comment by dmpr0** [comment]
# ToDo

# Coordinate format, Setting. Figma
<table style="width:100%">
  <tr>
    <th>Main screen</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/40d4e66b-3729-4208-9deb-6e34f1bf04d3"  width="200" height="auto"/> </td>
  </tr>
</table>   


We need to change the logic of the screen. Previously, we showed a list of all available formats with the ability to select a primary one, which was shown first in the context menu and used in the Coordinates widget. We will slightly change this by allowing the user to have a Primary format (the first one) and a list of others. The primary format will still be shown first in the context menu and in the widget, but later we will add the ability to change the format specifically for the widget.

### AppBar

- [x] Title – `Coordinate format`
- [x] Leading action – Back
- [x] Trailing actions:
- - [x] **Edit,** icon – **ic_action_edit_outlined**
- - - [x] Open Edit screen on tap
- - [x] **Menu**, icon – `ic_overflow_menu_white`

**Menu:**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4f659e4f-a2f6-40d4-96a7-493b47c22370"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] **Reset to default**, icon –
- [x] **Copy from another profile**, icon – `ic_action_copy`

### List
- [x] Description – `Preferred formats for quick access from context menu and search.`
- [x] Show list of preferred formats. The modified default list should apply only to new installs.
- - [x] DDD.DDDDD 
- - [x] DDD MM.MM
- - [x] DDD MM SS.SS
- - [x] Universal Transverse Mercator (UTM)
- - [x] Open Location Code (OLC)
- [x] Second line: show coordinate examples
- - [x] Show EPSG code for EPSG formats
- [x] Draw a full-length divider below the first format to emphasize it.
- - [x] Add `• Primary` text label for the first item
- [x] Show FAB with icon – `ic_action_add`
-  - [x] Open **Add format** screen on tap

## Edit 

<table style="width:100%">
  <tr>
    <th>Edit</th>
    <th>Confirmation dialog</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/0040a7ef-dfc4-4c79-9c9f-7ffc5edc5d17"  width="200" height="auto"/> </td>
    <td><img src=""  width="200" height="auto"/> </td>
  </tr>
</table>   

**AppBar**

- [x] Title – `Coordinate format`
- [x] Leading action – **Close**, icon – `ic_action_close`
- - [x] Show confirmation dialog on tap if changes were made
- [x] Trailing action – **Add**, icon – `ic_action_add`
- - [x] Open **Add format** screen on tap

**List:**
- [x] Show list of preferred formats
- [x] Item actions (similar to the Edit widget panel screen):
- - [x] Leading – **Remove**
- - [x] Trailing – **Move**

**Apply button**
- [x] Show at the bottom of the screen
- [x] Disable if there are no changes

## Add format
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ccffc101-d5b6-4d0c-8618-d1ec1089df18"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7cd2f52c-ec80-4df2-9ecd-e8d45ae6bcb7"  width="200" height="auto"/> </td>
  </tr>
</table>   


**AppBar**

- [x] Leading action – **Close**
- [x] Title – `Add format`

**Search bar**

- [x] Use – https://developer.android.com/reference/kotlin/androidx/compose/material3/SearchBar.composable#SearchBar
- [x] Open search view on tap. (Similar to the Astronomy search)
- [x] Placeholder – `Search EPSG code or format name`

**General**
List of formats that were shown in the app before these changes.
- [x] Hide already added formats

**Empty state**

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9d8ecb33-fa61-4e98-8bc9-f46b7efedba5"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Icon – `ic_action_coordinates_location`
- [x] Title – `Looking for a specific format?`
- [x] Description – `Search a database of over 5,000 local and national EPSG codes by country, name, or ID.`

**Search**

- [x] Formats should be searchable by name or EPSG code
- [x] Tapping **Add** should add the new format as the last item without closing the Add format screen

# Coordinates search, [Figma](https://www.figma.com/design/UzancGtMEmAOenmAvhXueQ/Search?node-id=1612-30897&m=dev)

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d443be52-ffd0-4710-aa11-ebb0c537d07c"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/922629f6-7df2-4500-9815-38e59ec3da9c"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2ef20e16-b381-4599-a25b-9f5c1f673a5c"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ce119dc4-db31-489d-89ab-ad61768fc939"  width="200" height="auto"/> </td>
  </tr>
</table>  

- [x] Use native text fields; the current one looks strange, and the `X` button is not aligned properly 
- [x] Move Format selection to the first place
- - [x] Show bottom sheet on tap
- [x] Use Outlined style Text Fields for data entry fields

**EPSG coordinates**
- [x] First field – `Easting / X`
- - [ ] Icon – `ic_action_grid_easting_x`
- [x] Second field – `Northing / Y`
- - [ ] Icon – `ic_action_grid_northing_y`

**UTM / MGRS:**

- [x] Use `ic_action_grid_utm_zones` for the Zone text field
- [ ] Use icons `ic_action_grid_easting_x` and `ic_action_grid_northing_y` for Easting and Northing

### Format bottom sheet

<table style="width:100%">
  <tr>
    <th>Predefined</th>
    <th>With Recenet</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/11690ae1-4436-4e3f-af2e-4acd0e72145f"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f601fd5b-22b6-49a6-89e8-712272e37458"  width="200" height="auto"/> </td>
  </tr>
</table>   

Bottom sheet will be used in the Coordinates search and Widget settings screens.

- [x] Use native bottom sheet; we started using them in Astronomy
- [x] Add Close button
- [x] Show Header - `Format`
- [x] Show list of predefined formats
- - [x] Draw divider below primary one

**Select other format**
Button allows use any format as temporary

- [x] Show button **Select other format** with icon – `ic_action_add`
- - [x] Open **Add format** on tap with focus on the search field
- [x] Show 5 recently added formats
- [x] Show header **Recent** if there is more than one item
- [x] This list should be the same for any place where the bottom sheet is shown

# Coordinates widget, [Figma](https://www.figma.com/design/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=3379-34078&m=dev)

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f2a5e212-f9c2-4688-922f-ce535d1842a4"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e9759bad-9c8a-4ced-af43-84e8df333dda"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f9a64958-5f0a-4441-9f07-9b33a941aab2"  width="200" height="auto"/> </td>
  </tr>
</table>  
 

- [x] Add **Settings** group for both Coordinates widget
- [x] Add new parameter **Format**
- - [x] By default set to Primary format
- - [x] Show **Format** bottom sheet on tap
- - [x] Allow to choose any format

**Comment by DmitryAlexei** [comment]
Related issue: 
- https://github.com/osmandapp/OsmAnd-Issues/issues/2933#event-26003128365

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7971m, released: 2026-06-15

**Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [x] 3. Different coordinate data for 36U versus 36N.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/50b719ce-440f-4849-b147-d76b3a0b51e1"></video>
</details>

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [x] 1. The top of the window is cropped on Android 12. On Android 15, the window is displayed correctly.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Android 12</th>
    <th>Android 15</th>
  </tr>
  <tr>
    <th><img src="https://github.com/user-attachments/assets/83f49c80-b029-43e9-86ca-96f2143cd42b" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/ff82d92d-c3be-4fff-a4ea-007757e95e23" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Severity**: 🔵 Trivial / **Priority**: 🔵 Low

* [x] 2. There is no icon for the **Copy from another profile** action.

<details><summary>Details</summary>
<img width="400" alt="Missing icon for Copy from another profile action" src="https://github.com/user-attachments/assets/bf3eb25b-3c9e-4456-884d-ac1e9b1facf2">
</details>

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.4.0#8004m, released: 2026-06-18

The issues described in Testing 1  - **Fixed**.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/0e463199-a375-477f-8f70-39c8ae11de82" width="300" height="auto"/></td>
    <th><img src="https://github.com/user-attachments/assets/ec6afcf6-49ac-46ae-a4cf-c2cea4bcadd3" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/18c68f10-00ce-4775-b147-a62f6e171228" width="300" height="auto"/></th>
  </tr>
</table>
</details>

_________

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [x] 1. When using Dark Theme, window elements are displayed in light colours - **Regression**.

<details><summary>Details</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/9ec11a43-8a35-4c56-b50c-0df920000f24">
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Figma</th>
        <th>Result</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/0ccb04fd-9632-402c-b6e5-85c87c87286f"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/6ca12c80-b61f-41fe-8cc4-838aa650558a"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Use Regular font style for Format names on all new screens

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/877cd3ce-3a24-42ed-b5f6-b20170acd293"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Divider is missing sometimes  

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Figma</th>
        <th>Result</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/a6f55fe9-ef1a-451c-8622-b7bf904ee6ca"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/fd907bd9-33de-41ee-beed-f7199a7d7291"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Add divider below AppBar
- [x] Left padding for text and divider is 72dp
- [x] Recheck right padding between Move button and right side, it should be ~16 dp 
	- [x] do the same with Add button 

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
   <tr>
        <th>Figma</th>
        <th>Result</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/2a841d72-3eb3-4b79-a581-3af29d6b5e51"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/83253cb2-ee68-48f8-a68c-04ad44f7dece"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] Increase padding between the top side and the title to 2dp. 
- [x] Increase padding between the bottom side and the description to 2dp. 
- [x] Use `ic_action_coordinates_location`.
- [x] Description line-height: 120%.

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9baf031a-1529-4553-96e3-97cbffcffac2"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Check back button in RTL

## Coordinates Search

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/6893b4ad-1d06-4926-9c53-96993aacd670"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Text not aligned. Use **Native**! text fields
- [x] Corner radius should be the same for all 4 corners for outlined text fields
- [x] What font is used in outlined text fields?

## Bottom sheet

- [x] Text style Regular for titles
- [x] Recent section should only include formats that was added by **Select other format** button
- [x] Remove divider above **Select other format** button
- [x] Bottom sheet should have one background color. Remove grey color below **Select other format** button

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/2399dd9f-a8ba-4d26-a5ea-326855bc7fb3"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] There is some additional padding around all items?

**Header**
Find a way to save this header with bottom sheet as component so we can reuse it later.
- [x] Try to decrease padding between top side and title / button to 10 dp

**Item**

- [x] Left padding between left side and Radio button = 4dp
- [x] Padding between radio button and text = 20dp

# Additional

## Coordinates Grid
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c113a0e7-5a35-43fb-8571-b9c4ccbff904"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Show **Format** bottom sheet after tapping on Format. Currently, we show the dropdown menu with a limited list of coordinates.

**Comment by Zirochkabila** [comment]
# Testing 3

> OsmAnd~ 5.4.0#8138m, released: 2026-07-02

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. The top bar title **“Add format”** is displayed outside the screen boundaries.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/1a3986ca-e1ce-4ac5-8e6e-7620963cd501"></video>
</details>

* [ ] 2. The direction of the **Back** button differs in RTL on the settings screens.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/98b5c424-6a9a-449f-b435-e51dbe40e098"></video>
</details>

**Comment by dmpr0** [comment]
@Zirochkabila 
> 2. The direction of the Back button differs in RTL on the settings screens.

Should be moved into separate task, with checking RTL for all screens.

**Comment by dmpr0** [comment]
## UI Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/50918153-3b66-4361-908a-f659793a03d4"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Tapping “Back” after selecting another format shows the “Add format” screen which I haven’t visited.

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4f97ad51-c8e5-4d6d-a3a3-5d7b1fa6f3d6"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Wrong icon is used for OLC? Use – `ic_action_world_globe`
- [x] Remove message `Valid full OLC Represents area: 10 ft x 10 ft` or `Invalid`

- - - - - -


<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/c0988695-1ac4-4fd7-b6bc-f1822eb41829"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Doesn't look like Roboto?

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Coordinates search</th>
        <th>Grid</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/b3d2b087-6b97-4a11-9324-d1d5d9ecaf86"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/348939d6-7765-47eb-ae70-d16abf504a04"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] We need to discuss this with the OpenGL team and understand why those lists are different.

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/433e19a1-1194-464a-9297-23891fbce80c"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Show numeric keyboard for EPSG types in Coordinates search

**Comment by Zirochkabila** [comment]
> 2. The direction of the Back button differs in RTL on the settings screens

Moved to the https://github.com/osmandapp/OsmAnd/issues/25357

**Comment by Zirochkabila** [comment]
# Testing 4

> OsmAnd~ 5.4.0#8337m, released: 2026-07-20

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. The numeric keypad does not appear for these coordinate types.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/b153a634-d6cf-4f2f-a87c-95fb82126b10" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/28b273f7-206d-4797-b94a-da208c095760" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [ ] 2. When returning from the coordinate system search window, the animation jerks.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/f01661f9-726c-4dbe-97f6-e9256049c9b9"></video>
</details>

* [ ] 3. The header of the **Add Format** page is cut off.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/17a1b9e3-155b-47db-954e-c57662bdf616"></video>
</details>
