### ISSUE TITLE
Apply sorting order to all subfolders – Tracks

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#17467]
Already suggested here but probably overlooked: https://github.com/osmandapp/OsmAnd/issues/17278#issuecomment-1575685950.

Currently it is really tedious to change the sorting order of tracks for each folder individually. It would be nice if the current sorting order can be applied to all subfolders. Either via a separate button or via a dialog when changing the sorting order.

**Comment by Zirochkabila** [comment]
Maybe we can add functionality similar to when a user changes settings in a profile and is offered to apply the change to all profiles or only to the current one

**Comment by dmpr0** [comment]
@Zirochkabila Yes, but variant with snackbar or toast.

**Comment by dmpr0** [comment]
## ToDo
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Folder menu</th>
        <th>Sorting menu</th>
        <th>Toast message</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eefcfffa-890a-4ddb-875b-430bf1342972"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/236d9932-bb11-40d3-a692-e982e3825218"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/440acc24-3f99-4620-bbb4-10b8027fd8b4"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   
We will add **Sort subfolders** action to open folder menu.

- [ ] Add action **Sort subfolders** to open folder menu
- - [ ] Icon – `ic_action_sort_subfolder`
- - [ ] Tap – open **Sort by** bottom sheet.
- [ ] Selecting sorting order should be applied for all subtler and tracks
- [ ] Show toast after sorting:
- - [ ] Text `Subfolders in “FOLDER NAME” is sorted by: “SORTING ORDER NAME”`, example `Subfolders in “Summer 2021” is sorted by: “Name A – Z”`

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/personal/tracks#three-dot-menu

**Comment by EugeneZmeuk** [comment]
**29.03.2024 Review**
- Tracks
