### ISSUE TITLE
Android Auto has laggy location (ANR crashes) and provides late announcements

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17505]
### Description

On Android Auto Blue arrow is driven behind actual location for 3-5 seconds which makes auto navigation very inconvenient. 

### Environment

This is definitely a regression since 2022 but latest release working release is unknown yet. Probably it happened independently of OsmAnd releases and related to Android Auto or Google Play library releases

### Workaround

Disable permission for Android Auto (Separate app) to get location, so location will be used directly from OsmAnd App

**Comment by dmpr0** [comment]
## ToDo Documentation 
- [ ]  Add article in Troubleshooting Android Auto
- [ ] Add Section about location issues.
- [ ] Fix for issues is disabling location for Android Auto app

**Comment by vshcherb** [comment]
Only documentation fix is possible

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/navigation/auto-car#issues
https://osmand.net/docs/user/troubleshooting/android_auto#location-delays-anr-crashes
