### ISSUE TITLE
Web - POI Context menu  (Photos Gallery / Rows)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#17949]
## ToDo part 1

- Initially we need to implement as Android
- Think about displaying Photo on top or redesign top bar for POI Context menu

Implement for testing all new features with backend 
- https://github.com/osmandapp/OsmAnd/issues/13926
- https://github.com/osmandapp/OsmAnd/issues/
## BUGS missing photos P180/P373/P18
- https://www.wikidata.org/wiki/Q2018731
- ```select * from wiki.wikiimages where id = 2018731;``` only 1 visible many other objects also 1

## Part
**Images in context menu**
- [x] Tap on photo should open the same photo in **Open photo** mode
- [x] Tap **Show all**, should open **Gallery** mode

### Gallery, [Figma](https://www.figma.com/design/vvLQCBSPfJlsVLnTPoCPiw/Web?node-id=1313-97401&m=dev)

<table style="width:100%">
  <tr>
    <th>Gallery</th>
    <th>Open photo</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/692b5604-752c-4dbd-a3b2-f02c8df1af17"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/21a54153-1391-47d6-9b9c-641be924644c"  width="400" height="auto"/> </td>
  </tr>
</table>   

- [x] Tap back should open context menu
- [x] Tap on photo, switch Gallery to the photo

## To do (backend)
- [x] Date / Author / License https://github.com/osmandapp/web-server-config/blob/main/servers/wikidata/download_mediainfo.sh 
- [x] Or alternatively make query to Wikimedia (https://commons.wikimedia.org/wiki/File:Siilinkarin_talvikahvio.jpg, https://commons.wikimedia.org/wiki/File:Siilinkarin_talvikahvio.jpg?action=raw)

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd/blob/ba6a9dfbc00604cc1514bf5a50d65b2b87fbdca8/OsmAnd/src/net/osmand/plus/mapcontextmenu/builders/cards/ImageCard.java#L423

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a660b9e7-ada8-4799-a8ed-1ba84eda0fef"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Show selected photo

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ea099a15-1e1c-4a58-b471-ba5bc7c05cea"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Show click state cursor when hovering on photo

**Comment by alisa911** [comment]
Adding descriptions to photos will involve mandatory parsing of data by link for each picture (query to wikimedia). There are 46 million pictures in total, and now almost 9 use pre-parsed data from latest-mediainfo.json.bz2. This speeds up work with the gallery a little.
