### ISSUE TITLE
When final segment  is not possible, display these beeline segment different dash line

### ISSUE THREAD

**Issue by lcosmin** [osmandapp/OsmAnd#17987]
# 🐞 routing report

### Routing engine

- [x] OsmAnd's in-app offline routing
- [ ] Any online routing provider (YOURS, openrouteservice, OSRM, etc.)

### Routing Profile

Car

### Start and end points

From: https://www.openstreetmap.org/way/1197979661 
To: Bucharest  ( https://www.openstreetmap.org/relation/377733 ) 

### Actual and expected routes

[Actual route
](https://drive.google.com/file/d/1MljhNB9lm0nq7R8-3c_rim43wTRaVjbM/view?usp=drive_link)

Expected route:  

I would expect at least a warning. The proposed route, which involves teleportation :) , is due to the fact that the nearest road is unpaved and I accidentally had the option to avoid unpaved roads set. 

And, if routing is not possible given the current "avoid" filters, then maybe mark the "teleportation" segment in some other color or maybe propose a route which doesn't respect all filters, don't know. 

## 🌍 Your Environment

**OsmAnd Version:**

<pre><code>

4.5.10
</code></pre>

**Device and Android/iOS version:**
Android 13

**Comment by DmitryAlexei** [comment]
OsmAnd~ 4.6.0#654m, released: 2023-08-22

**Steps to reproduce:**
- Download Romania map with live updates
- Strating point 45.65372, 26.06338, end point on the other road

Note, that starting point is located on the gravel road (see [OSM](https://www.openstreetmap.org/way/146298849#map=16/45.6561/26.0650))

**Actual result:**
- see difference in routing with and without *Avoid gravel* option in Navigation settings enabled

<table style="width:100%">
  <tr>
    <th>Default car routing</th>
    <th>Avoid gravel enabled</th>
    <th>No warning</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/99c0b519-aa8e-4bb2-87a7-6adf14bf8e94"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/902a9ca6-7186-4668-8304-bbd69701d740"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/94d60e78-bc02-41c5-8129-c6ac44b4c9c7"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by lcosmin** [comment]
Yes, I actually noticed the whole arrow _after_ I opened the ticket; however, this left me confused, as my first thought was that there's a bug of some sort. Now that I know about this "feature", it's different. I'd still tag it as an "UI/UX improvement" issue.
However, I had [this](https://drive.google.com/file/d/1MQxs6X2sd3hwo6utucJzeRgQSr_NRrhh/view?usp=drive_link) result too, but might have been from an earlier version of the app. 

Could be closed in my opinion.

**Comment by scaidermern** [comment]
Yes, it would be very nice if OsmAnd could warn if the last or first n meters can't be calculated. Then users can double check if the calculated route is really the one they want to follow. Consider it as a safety feature.

**Comment by osmonoid** [comment]
Please correct me if I am wrong, but I think this issue describes a very similar situation as in #16181
Unfortunately this issue was not considered as an actual problem/bug by the developers.
I still think that is in fact a serious bug and may get you into trouble when driving a car if you didn't inspect every section of your planned route beforehand (or at least the first and last part which are prone for this bug). Though not in your specific easy/bold example where finding a solution for the problem "on site" does not result in a long (kilometers) detour.

**Comment by lcosmin** [comment]
it sounds like the same issue, indeed.

**Comment by vshcherb** [comment]
For now good indication is straight line though we need to think what would be non-intrusive way to warn about "non-calculated start/end segment", actually it could happen only at start and at end. We need to be careful cause we have many offroad users which are get to used to this noncalculated start / finish segments.

**Comment by osmonoid** [comment]
Thank you, @vshcherb, for considering this issue.

> [...] For now good indication is straight line [...]

No question/doubt about that for the two cases of
- "now" (immediate future)
- [easy/obvious cases](https://github.com/osmandapp/OsmAnd/issues/17987#issuecomment-1687991511) using a high zoom level, i.e. from a low altitude birds eye view such as @DmitryAlexei posted (most like only for easier demonstration) 

The reason why at least I, but possibly also the other users of this issue, reported it are the less obvious cases where the straight line segment is actually not identifiable/distinguishable without zooming into the problematic areas. Other users not knowing about this "unexpected, partially straight line segment route planning feature" might run into problems e.g. when driving a car.

> [...] we need to think what would be non-intrusive way to warn about "non-calculated start/end segment" [...]
- Suggestion 1 taken from [issue #16181](https://github.com/osmandapp/OsmAnd/issues/16181#issuecomment-1382086716)
highlight the problematic segment (e.g. using a distinctive/opposite color)
![current state](https://user-images.githubusercontent.com/122121671/211151202-93ef667e-4cca-45de-9c94-fb3edac408d4.jpg)
![suggestion](https://user-images.githubusercontent.com/122121671/212369073-d0fed051-f73f-4ab4-99dd-b2d0b5cebc48.jpg)
- Suggestion 2
  - Once this feature is introduced and the user is confronted the first time with such a case: display a (both temporarily) dismissable info/warning which also can be turned off permanently in the navigation options.
  - Ideally, the warning contains both a shortcut/link to zoom to the problematic segment and a shortcut/link to the navigation settings sub-menu where this safety mechanism can be turned off permanently.

> [...] We need to be careful cause we have many offroad users which are get to used to this noncalculated start / finish segments [...]

IMHO the suggestions are in line with these considerations.

**Comment by lcosmin** [comment]
This ticket resulted from my lack of knowledge about the "draw it as a straight line" feature when part of the route is inaccesible. 

When the problematic segment is at the beginning of the track, rendering it in a  different color would probably alert the user to the fact that there's something going on there. 

However, I don't think this approach is feasible for the end of the track, as I don't think many people would visually scroll over every route they plan. Sometimes it's even difficult to do, e.g. when using Android Auto. 

So, I guess some sort of "intrusive" message is necessary, like a confirmation/warning dialogue. Something that auto-dismisses itself, like a toast notification, might go unnoticed on Android Auto for instance (because you set the destination and might start driving without looking at the car's screen). 

And, obviously, the display of this warning should be configurable for those who don't want to see it.

**Comment by scaidermern** [comment]
> We need to be careful cause we have many offroad users which are get to used to this noncalculated start / finish segments.

Maybe there should be a separate offroad profile or some setting to make a profile offroad. In the end, offroad routing is a completely different thing than routing along roads. Sending normal users offroad (which is what OsmAnd currently does) certainly isn't the correct approach.

**Comment by vshcherb** [comment]
We need to redesign full screen and backend to warn about all warnings (ferry / private roads) that could happen during the route navigation

**Comment by dmpr0** [comment]
## ToDo

- [ ] Draw dash line for unaccessible segment. Dash line style should be similar to pedestrian segments in public transport

**Comment by DmitryAlexei** [comment]
Same in iOS app https://github.com/osmandapp/OsmAnd/discussions/20996#discussioncomment-10902699

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/87126433bd609571cbbb6d409fff844ca3725d55

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/e7c2a9eed80857c12a00fadf5490fe5b8a917377

**Comment by dmpr0** [comment]
# Review


<table style="width:100%">
  <tr>
    <th>Example</th>
    <th>Current</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4d0b7a2e-85a3-4670-8ef3-8d42c3c03756"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/8038fdab-f89b-4bae-8937-bfc0d7808261"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Dashed line width should be equal to route line width

**Comment by alex-osm** [comment]
Fix line width - https://github.com/osmandapp/OsmAnd/commit/1729b412b9c25c54beb2146eb043bd60eec4c607

**Comment by dmpr0** [comment]
# Review 2

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review 
We need to try to move styling of this line into style.

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.0.0#3884m, Released: 2024-12-05`

1. At what zoom level should the arrows be displayed?
2. Perhaps we should change the color of the arrows to match the color of the route?

- [ ] Need to implement for Slope and Altitude

<table style="width:100%">
  <tr>
    <th>Zoom level</th>
    <th>Color of arrows</th>
    <th>Slope</th>
    <th>Altitude</th>
  </tr>
  <tr>
<td><video source src="https://github.com/user-attachments/assets/6c348b7e-d257-487b-a682-2419a2294b26"  width="300" height="auto"/></td>
<th><img src="https://github.com/user-attachments/assets/23ca1a7d-c578-472a-b53e-94c623e7cf74"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/802fb711-73d3-441d-9b93-287d512d367e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/cc3b38ee-a5bc-4df0-be26-1ff9e403ffa7"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
For slope altitude wont' make to 4.9 so we need separate issue in case requested
