### ISSUE TITLE
Redesign elevation graphs (Elevation widget, Analyze on map)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd#18204]
## ToDO
* We need new UI for graphs without overlapping labels

### Default presentation 
<table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/73f39953-ce2d-4b46-b760-03ca5c56e968"  width="360" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5389c145-bd65-4d66-868e-1b9482616f67"  width="360" height="auto"/> </td>
      </tr>
    </table> 

- [x] Move Y-axis labels to the right side
- [x] Graphs should take all free space between paddings and Y-axis column
- [x] Add left and right paddings `16dp`

- - -

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b714e799-d48d-4b8b-8f8c-3c963d935037"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Add vertical padding `6 dp` between chart and Y-axis labels.

- - -

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/2c21a2a1-3b92-4fc8-b514-47ab90a98aae"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/bc43026a-79de-4cd4-8cc2-3fff5491d3e0"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Column with Y-axis label should have dynamic width
- [x] Labels should be placed below horizontal grid lines

- - -

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/0989caca-1430-49a7-beb3-2efc7973c374"  width="300" height="auto"/> </td>
    <td valign=bottom><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/247ca051-610e-4d75-b182-4d49501420bb"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] We need to have ability to set different chart height on different screens

- - - 

<details>
    <summary>Original request</summary>

- My proposition is to show the Line of user Location without intersection with data of the Y-axis. The beginning of the graph can be shifted along the X-axis so that there is no overlap.

| OsmAnd 4.6|   My Proposal |
|--------|---------|
|![telegram-cloud-photo-size-2-5219971817425456979-y 1](https://github.com/osmandapp/OsmAnd/assets/44466116/c191dcfc-4ee6-4728-8510-8faed0095ec7)|![Group 192](https://github.com/osmandapp/OsmAnd/assets/44466116/dae579ed-3718-43ce-83c9-21beea560c10)|

- Next, need to add a Location point on the Graph, because the thin line is not visible during bicycle riding.

|My proposal|
|--------|
|![Group 193](https://github.com/osmandapp/OsmAnd/assets/44466116/2e481821-0df4-4f04-a963-8024d10e832f)|

</details>

**Comment by mikehgentry** [comment]
This might be a duplicate of #16145

**Comment by DmitryAlexei** [comment]
@mikehgentry you are right, these issues are very similar. Even have the same name.
- New idea is to **show Location point on the Graph, because the thin line is not visible during bicycle riding** (third screenshot).

**Comment by sonora** [comment]
**To be able to simply tap the graph to toggle marker and the label overlay on/off** would be nice. This would not permanently use screen space (like 20% ?) for e.g. labels you may only want to see once and then concentrate on the graph itself.

**Comment by mikehgentry** [comment]
Showing intermediate destinations on the graphs could be useful as well - at the moment you have to go into 'Analyse on map' and scrub the graph back and forth till you find the spot, which is a little awkward.

**Comment by sonora** [comment]
The design above uses a considerable portion of the screen width for the labels, permanently? Which could be an issue for small devices, particularly in Portrait orientation?

Could we implement to toggle this on/off, e.g. by tapping the graph area (like we already have today anyway for the movable marker)?

**Comment by sonora** [comment]
Also: The font size is _a lot smaller than the smallest font size_ we use elsewhere in any OsmAnd text. On purpose?

**Comment by DmitryAlexei** [comment]
Related #19315

**Comment by dmpr0** [comment]
# Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Remove decimal points

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] First marks is lost

**Comment by EugeneZmeuk** [comment]
**04.04.2024 Review**
- [ ] change all iOS and Android screenshots for [this section](https://osmand.net/docs/user/map/track-context-menu#altitude--speed-graphs)

**Comment by EugeneZmeuk** [comment]
**23.05.2024**
- [ ] [check graphs and text correction](https://osmand.net/docs/user/map/track-context-menu#altitude--speed-graphs)
