### ISSUE TITLE
Additional filters for Smart folders

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18221]
# ToDo
As a user I would like to create filter and smart folder based on certain properties
- Filter by selected folder
- Filter by color
- Filter by thickness

## Folder
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Closed filter</th>
    <th>Open filter</th>
    <th>All folders</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f8485651-ab43-4daa-b83c-31fc914038ad"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/19cb6036-079c-4410-b858-6b36043ad959"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/9a36114c-4b21-4172-84bc-bf187c011615"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>  

- [x]  By default set to current folder. Starting search in any folder should set filter Folder to Current option.
- [x] Show current folder (if it's not Tracks) as first item, add `Current` string to the second line
### Width

**Comment by dmpr0** [comment]
# Review 
- [ ]  Add **Not specified** item for **Color** and **Width** filter, for items without color or width

**Comment by dmpr0** [comment]
# Review 
- [ ]  Show all button for long lists should open separate screen with full list and filter by name

- - - - - - - - - - - -  
**Folders**
- [ ] Show quantity of tracks matching for all applied filters  
- [ ]  Text colour for tracks quantity in folder secondary

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/personal/tracks#filter

**Comment by dmpr0** [comment]
# Review - 2

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Video</th>
    <th>Unselected</th>
    <th>Selected</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/dcdf9295-5e12-48b6-b28e-b6352e0677d0
"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e0e9bd18-29aa-47b3-a4e9-e6c1b5d0b372"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/09b216a1-fe61-418a-b989-32b8f9d13b36"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  





- [ ] Selecting one of the folder leads to tracks quantity recalculation in other folders

**Comment by EugeneZmeuk** [comment]
**16-04-2024 Review**
- added links for [this section](https://docs.osmand.net/docs/user/personal/tracks#folder-menu-in-tracks-tab)
