### ISSUE TITLE
Map UI elements are too large with low DP (depends on Appearance for all buttons)

### ISSUE THREAD

**Issue by barathrm** [osmandapp/OsmAnd#18357]
### Description

On Android 14 the UI map elements seem to always be too large, even with the UI sizes set to the smallest possible in the android settings.

I think the same thing was reported here https://github.com/osmandapp/OsmAnd/issues/16630#issuecomment-1760416247

### Steps to reproduce

Install osmand from fdroid on an android 14 phone. Adjust display size to smallest.

### Actual result

<img src="https://github.com/osmandapp/OsmAnd/assets/76487253/ff613c48-23c4-4a17-b922-43628553ea38" width="400px">

<img src="https://github.com/osmandapp/OsmAnd/assets/76487253/a65a4ad8-2917-41f7-b2ab-6850b09e5749" width="400px">

### Expected result

UI elements should get smaller when configuring the android UI sizes to be small.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.10
Android/iOS version: android 14
Device model: pixel 4a
Crash-Logs: ?
```

**Comment by sedot42** [comment]
This affects me as well.

**Comment by vshcherb** [comment]
To do: We need to remove this code (once we can allow user to scale UI)
- [ ] https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/build-common.gradle#L260
- [ ] https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/build-common.gradle#L269
- [ ] https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/build-common.gradle#L250

On some devices tablet (drawable-large) is not correctly recognized

**Comment by vshcherb** [comment]
To Do : we need to check if we're using correct method to detect tablet version so we can keep for tablets by default large buttons

**Comment by vshcherb** [comment]
Nope for screens bigger > 800 dp we display large buttons as you make your screen items smaller, it makes your screen wide in "virtual pixels", so you switch to Tablet UI. 

We plan  make it configurable in 4.8

**Comment by dmpr0** [comment]
## ToDo

- [ ] Remove big sizes for button, leave for widgets

**Comment by vshcherb** [comment]
Task updated @Chumva @dmpr0

**Comment by dmpr0** [comment]
## ToDo

## Default buttons
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/fce0fde7-d87d-43be-9cce-b76fe6bd91de"  width="300" height="auto"/> </td>
  </tr>
</table>   

**Actions menu**
- [ ] Add new option **Appearance**
- - [ ] Icon `ic_action_appearance`
- - [ ] Tap – open Appearance screen

**Comment by Zirochkabila** [comment]
# Test 1
`OsmAnd~ 5.0.0#3972m, Released: 2024-12-20` - Fixed

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e9d1e9de-f129-40a8-88ed-3c63d0ceaadc"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Map ruler is still big?
- [ ] Text size in widgets

**Comment by vshcherb** [comment]
To design: there should be simple way provided to change button and widgets size simulatneously to comfortably use tablet for navigation as before.

- [ ] Widget text size couldn't be changed
- [ ] Icons don't scale inside buttons
- [ ] Alert size is relatively smaller?

<img width="400" alt="Screenshot 2025-01-02 at 14 39 33" src="https://github.com/user-attachments/assets/275b188a-a980-4a79-b32a-e29d183bc936" />
<img width="400" alt="Screenshot 2025-01-02 at 14 39 22" src="https://github.com/user-attachments/assets/926f3188-9a49-495c-bd45-b77286992547" />

**Comment by KartikeyTripathi469** [comment]
Hello, I would like to work on this issue.
Could you please assign it to me?

**Comment by vshcherb** [comment]
We need to disable special sizes for "tablets" which are not tablets - https://github.com/osmandapp/OsmAnd/issues/25018

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7785m, released: 2026-05-18

The size of icons and fonts adapts to the tablet's system settings.

- [ ] The ruler is still quite large

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/fb1507ad-50ed-4519-883f-2f8dbbca5186"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b944c3f2-2f8e-4e50-a10c-122d9664c0c6"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th>Nightly</th>
    <th>5.2.13</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1349b0a1-cea8-48e0-8ffb-2769457620e9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a301d41c-7b8a-4743-9d19-6e31a966df6b"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [x] Remove scale for the text in the widgets 
- [x] Remove text scale in the map ruler

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.4.0#7899m, released: 2026-06-08

**Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1. If the text size is set to medium or larger, the text in the widgets is truncated.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/561d0ea3-36a8-4449-80c0-b5b2b75b2968" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/f9adbc09-a04c-43c7-b330-64ad8478a6b9" width="300" height="auto"/></th>
  </tr>
</table>
</details>
