### ISSUE TITLE
Filter by Sensor data (HR, Cadence, Power)

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18518]
# Description 
We need to add filters by sensor data.

> Previous task https://github.com/osmandapp/OsmAnd/issues/18221

 

## ToDo
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/979c9f77-5d45-4da7-8406-b657a98d56be"  width="300" height="auto"/> </td>
  </tr>
</table>  
</details> 

Allow to filter tracks by:
- [x] **Sensor speed, max**
- [x] **Sensor speed, average**
- [x] **Heart rate, max**
- [x] **Heart rate, average**
- [x] **Bicycle Cadence, max**
- [x] **Bicycle Cadence, average**
- [x] **Bicycle Power, max**
- [x] **Bicycle Power, average**
- [x] **Temperature, max**
- [x] **Temperature, average**
- [x] Filters should be always visible, not depend on External sensors plugin state.

**Comment by Chumva** [comment]
Filters code should be simplified as we shouldn't have separate classes for filters - they don't require any specific functions. Instead we should have Conversion function (1 per unit), GPXDatabase should provide generic API to retrieve min/max field from database.

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/fc56ecdb-f2be-4192-a0a9-2f31946a18a9
"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  




- [ ] Filter by HR doesn't work
