### ISSUE TITLE
Sun position widget

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18559]
## Description 
Combined Sunrise / Sunset widget, that can show next event (sunrise on sunset) or Sunrise / Sunset.

# ToDo

## Widget group
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/877203fc-a17e-45a1-b32f-9eb083962fcc"  width="360" height="auto"/> </td>
  </tr>
</table>   
</details>  
 

* [Figma](https://www.figma.com/file/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?type=design&node-id=1495-93273&mode=dev)

- [x] Rename from `Sunrise, sunset` to `Sun position`
- [x] Add new widget `Sun position`

## Widget settings
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Settings</th>
    <th>Mode</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5777932d-a554-4666-a4fa-085811b8eaa3"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5474da50-2abe-44e1-965f-9c557a775220"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

### Mode

Allows to choose one on three modes:

- [x] **Next event**, show sunset time after sunrise, show sunrise time after sunset.
- [x] **Sunrise**, show sunrise time depends on selected Format.
- [x] **Sunset** , show sunset time depends on selected Format.

### Format
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Sun position</th>
    <th>Sunrise</th>
    <th>Sunset</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f25e0766-d8e8-4c75-9bbb-57c616a41468"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/844888e1-5f07-4735-8e7b-387fc5088702"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/deba3b4e-d612-450a-886a-bca30c646b28"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details> 

Allows to select time format between:

 

- - [x] **Time left**
- - [x] **Next sunrise**
- - [x] **Next sunset**
- - [x] **Next event**

### Widget on the map screen
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>After sunrise</th>
    <th>After sunset</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8574cca8-e0e3-4261-b3c4-9dc95b28c625"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5d4188f2-f55a-410a-8aeb-e1d47854558e"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [x] Should be available in all layouts on all panels

**Comment by Velomeloman** [comment]
Also would be great to add civil twilight (dusk, dawn) time.
