### ISSUE TITLE
Change default values for widget, buttons, options

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#18784]
## ToDo

New default values for listed options should be:

**Pedestrian**
- [x] **Snap to road** = `true`
- [x] Add **Second next turn** widget to  Widgets > Left panel
- [x]  **Map orientation** = `Movement direction`

**All profiles**
- [x]  **Transparent widgets** – `Off`
- [x] **3D Mode** – `Visible`

> iOS Task: https://github.com/osmandapp/OsmAnd-iOS/issues/3311

**Comment by sonora** [comment]
Actually, I find some of this not too intuitive:
- While 'Snap to road' may be a reasonable default for e.g. cars, pedestrians are more likely to stray off a road. It will cause issues to not reflect this in the app by default.
- 'Map orientation = Movement direction' is a particularly common feature in car navigation, while in pedestrian map use 'North is up' is very common.

Can we please re-think these portions, I think they are "weird"...

**Comment by vshcherb** [comment]
@sonora I was thinking of it and no, I couldn't find a good reason except people not pay attention mostly. The issue that people switch from Profile = Navigation thinking. I see a lot people using profile without navigation so it means very confusing by default. 
So I would say usage pattern has changed, 12 years ago these were not profiles but navigation modes
