### ISSUE TITLE
Allow assign Quick Action to external keyboard buttons

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#18821]
## Description 
I want to Allow assign Quick Action to external keyboard buttons, so I can have very big variety of actions that could be automated

**ToDo, External keyboard:**
* Screen to assign key to any added quick action
* Should be done after https://github.com/osmandapp/OsmAnd/issues/19258

# Key assignments, [Figma](https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?type=design&node-id=3639-135593&mode=dev)

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Empty state</th>
        <th>Key assignments</th>
        <th>Edit state </th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/218b78db-235e-4b70-a774-20c39ad16960"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/843f4ba7-f744-47d5-b755-56cd491aee16"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b0770a5d-ccfa-453c-9108-b65a59a2711d"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* All actions can be added or removed
* We remove None state, action without assigned key can't be added

## Empty state
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d4696bf1-2064-41ea-92c4-67d782a5edae"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Show if there is no assigned actions
- - [x] Title – `No assigned keys`
- - [x] Description – `Select an action and assign a key by tapping the 'Add' button.`
- - [x] Button – `Add`, show Add actions screen on tap
- [x] Disable **Edit** button in AppBar

## Default state
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d4696bf1-2064-41ea-92c4-67d782a5edae"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/4f9204cb-1d85-47bc-b8a7-87ba08a3b342"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] AppBar – add **Edit** button, tap open Edit mode
- [x] Add FAB (floating action button), tap –  open **Add actions**

<table style="width:100%">
  <tr>
    <td><h3>Group</h3></td>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e3d99753-c24a-47e8-9cbe-95cb6fe9272e"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show all added actions as one group
- - [x] Group header, title `Actions`
- - [x] Right side – `Key`

<table style="width:100%">
  <tr>
    <td><h3>Action item</h3></td>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f027651f-3332-4c08-8bd7-7b59c5cef002"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Show icon on the left side for all actions
- [x] Add icon for Key

## Edit mode
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Edit</th>
        <th>Discard changes</th>
        <th>Reset all</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c1bd026f-d830-4aff-ad33-36b73c199ada"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c5b2756b-8630-4e90-8797-81631f64aa6f"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e4f05434-1333-4828-a724-b91320db9e23"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Tap on remove action (left) removes action from the list
- [x] Taping **Cancel** in AppBar show **Discard changes** dialog
- [x] Taping **Apply**, should apply changes.

**Discard changes?** dialog
- [x] Show 
- - [x] After taping on Close button on AppBar
- - [x] Only if changes were made
- [x] Actions:
- - [x] **Cancel**, close the dialog leave user on the screen
- - [x] **Continue** 

# Key binding, [Figma](https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?type=design&node-id=3947-100118&mode=dev)

## Default mode
<table style="width:100%">
  <tr>
    <th>Key binding</th>
    <th>Context menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3667aedb-7f3a-44cf-aca2-ca1ff80e050c"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/001e2dde-624b-4474-b78c-f08d28c67180"  width="150" height="auto"/> </td>
  </tr>
</table>     

### AppBar
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/589bc11a-14f3-4811-b1ea-1c085dbb7f10"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>  

- [x] Add **Edit** action, tap open Edit mode
- [x] Add **Menu** action, tap open context menu
- [x] Show Name on the action by default

**Context menu**

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/9bd6b1cf-c844-4414-8a2a-264eb0f14695"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>  

- [x] **Rename**, open rename dialog
- [x] **Remove**, show confirmation dialog
- - [x] Removing action 
- - -
- [x] Remove Name item (Renaming will be moved to AppBar)

**Main card**
- [x] Show action with icon and name
- [x] Show assigned buttons

## Edit mode, [Figma](https://www.figma.com/file/qzrNQj0chuME6gyO038i6M/Settings?type=design&node-id=3947%3A102574&mode=design&t=I0upED4vlkS6Qm7L-1)
<table style="width:100%">
  <tr>
    <th>New shortcut</th>
    <th>Edit – Shortcut</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/ddfe8581-8da6-4c5b-b752-b5e210822fe9"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/5831e6b5-611b-4f41-a474-1e7ad5b065dc"  width="150" height="auto"/> </td>
  </tr>
</table>  

* Allows to Add or Remove action
* Allow to Assign or Remove Key, more then one key can be assigned

**Comment by dmpr0** [comment]
# Add action screen

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Add Action</th>
        <th>Search</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/3dbb70f3-bcb6-4de7-a65f-8755cb2daa92"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/e2e08b0f-6e10-4683-86b4-a631f42ff4fa"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Use full screen activity instead of bottom sheet

**NavBar**
- [ ] Left action = Close
- [ ] Right action = Search
- - [ ] Tap open Search screen 

**New actions:**
- [ ] Add **Map interactions** as actions:
- - [ ] **Move up**, icon – `ic_action_map_move_up`
- - [ ] **Move down**, icon – `ic_action_map_move_down`
- - [ ] **Move left**, icon – `ic_action_map_move_left`
- - [ ] **Move right**, icon – `ic_action_map_move_right`
- - [ ] **Zoom in**, icon – `ic_action_magnifier_plus`
- - [ ] **Zoom out**, icon – `ic_action_magnifier_minus`

**Comment by dmpr0** [comment]
# Review

### Key assignments

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f6dcdc95-d9fc-4d45-b405-e1acdc7d4451"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

 - [ ] Missed divider

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/be9f75c4-5403-48be-996f-3108d808c00e"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd/assets/9365308/a3422ab5-93a9-44bb-bb64-7133c738005f"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Map is visible

**Comment by dmpr0** [comment]
## Review

**Comment by shurasmiling** [comment]
- [Custom Keys Assignment](https://osmand.net/docs/user/map/interact-with-map#custom-keys-assignment)
- [External input device buttons](https://osmand.net/docs/user/map/interact-with-map#external-input-device-buttons)

**Comment by EugeneZmeuk** [comment]
"Review 30.07.2024"
- [ ] [Custom Keys Assignment](https://osmand.net/docs/user/map/interact-with-map/#custom-keys-assignment):
    - Adding introductory:  for external input devices (keyboard, joystick...) you can add own type. After that you see new type on the Type list.. Click on it for choosing it as general. Click to three dots - Rename, Duplicate, Remove.
    - Key assignments menu (after creation the new type) has standard [Action-Key assemble](https://osmand.net/docs/user/map/interact-with-map/#setup-of-external-input-devices)
    - You can delete all or part of Action-key or create new.
       - Delete - tap to "Pencil button"....
       - Edit - tap to Action-Key from the list...
       - Create - Tap to Blue-Plus button: Add action, Add Key 
 
- [ ] [External input device buttons](https://osmand.net/docs/user/map/interact-with-map/#external-input-device-buttons)   
   - "The external input device buttons also support other functions, such as opening the main menu or AV Notes." Rewrite this part (AV notes only Android, maybe not write about AV notes for introductory)

- [ ] [Custom Keys, QA - Custom buttons](https://osmand.net/docs/user/widgets/quick-action/#custom-keys)
   - delete the section
   - New "Quick Action" article structure: 
   ```
   - [Overview] - rewrite: "Quick Action widget is a custom button by default..."
   - [Enable Widget]
   - [Edit Actions List]
      - [Reorder Actions]
      - [Edit and Remove action]
   - [Add Action screen] - screenshots and description that this screen allow for Quick Action, Custom buttons, External input devices when we choose action for button or key.
      - [Action types] - here all types: Configure map, Map interaction, My Places, Navigaiton, Settings.
   - [Custom Buttons] - rewrite introductory ("Custom buttons are a unique type of Quick Action too". Now, the Quick Action is a custom button by default).
      - [Interaction with Custom Buttons]
      - [Rename and Delete Button] - here, need to add iOS screenshots too.
   
   ```

**Comment by fcg42** [comment]
Is this implemented yet? Any ETA if not?

**Comment by dmpr0** [comment]
> Is this implemented yet? Any ETA if not?

Hi! Yes you can set any quick action to external input device button, open Menu – Settings – Profile - General settings – External input device, add new Type, after that you can add new key assignments

**Comment by paddel10** [comment]
Are there any plans to support the feature while the app is running in the background or when the device is turned off?
