### ISSUE TITLE
Android auto view is cluttered with POI and causes distracion by flicker

### ISSUE THREAD

**Issue by mdykierek** [osmandapp/OsmAnd#18894]
### Description

There is way to many POIs that cannot be customized (or at least I didn't find a way to do it).
I see schools, libraries, amusements and attractions, etc. They cover actual roads. This seriously impairs legibility and thus safety.
All these POIs and also important icons (like street signals, pedestrian crossings) flicker on and of with most of the screen updates. The flicker applies to street names and  

### Steps to reproduce

Use Android Auto.

### Actual result

Cluttered, flickering, hard to read view.

### Expected result

Either make Android Auto View clearer by default (e.g. same as on phone screen) or provide customization.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.11
Android/iOS version: Android 13
Device model: Motorola Edge 40 Pro
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
Such behavior is indeed present. The map can really get cluttered. 
However, if you want to disable all POIs, we suggest Menu → Configure map → POI overlay...
or Configure map > Hide > POI

You can also try setting the auto zoom map to to long range. Menu → Configure profile → Navigation settings → Map during navigation → Auto zoom map

And set a larger Map magnifier, for example try 200. Menu → Configure map → Map rendering → Map magnifier

**Comment by mdykierek** [comment]
I tried "Menu → Configure map → POI overlay" and it does not seem to affect Android Auto view (on phone works correctly).
I need to check the Hide and I'll update.

**Comment by vshcherb** [comment]
I think we need to attach screenshots and explain how to reduce map icons size or change map magnifier. Actually map magnifier was changed last release

**Comment by DmitryAlexei** [comment]
When using AA, unnessaissary POIs are shown not only in the city, but also on highways. Although, of course, their number is much smaller. Here you can see bus stops, charging stations and already passed gas station + power lines, church, and railway crossings

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/4c4930d4-998d-49e5-9a1d-21de6b80e516"  width="600" height="auto"/> </td>
  </tr>
</table>

We already have the proposal to hide power lines while driving (it has "nice to have" label) 
- https://github.com/osmandapp/OsmAnd/issues/19636

During navigation simulations with all **POI and POI names disabled**:
- the map is still cluttered with black dots - private access restrictions. These black dots can be disabled only when **the Hide Overground objects** option enabled. But when it on, you won't be able to see all the other overground objects except roads.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/68a432cc-b807-4b1b-9567-d27758e69fde"  width="600" height="auto"/> </td>
  </tr>
</table>

- if you disable (hide) house numbers, names of shopping centers, enterprises, and even electrical substations will be still displayed on the screen

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/672d6142-f2ce-4049-82c4-3902c3433fbd"  width="600" height="auto"/> </td>
  </tr>
</table>

- it is clearly seen on the screens above, that distant street names and other objects far away from the current location are also pull the driver's attention away (even with POIs, house numbers, underground objects and military areas disabled!). 

- map magnifier when set to 125% and above significantly impacts Android Auto performance: when on roundabouts, rendering becomes really slow. After 10-15 min. of simulation with map magnifier set to 200%, the phone became very hot, and I received a warning on the AA screen.

<table style="width:100%">
  <tr>e<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/b7b9eb49-c5c6-4fe9-939c-fc4c7e57e12b"  width="600" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
### Todo:
Hide on zooms less than 18 (can be enabled (and will be shown on other zooms) in configure maps > details > more details)
- [ ] power towers and power lines
- [ ] public transport stops
- [ ] house names
- [ ] barriers
- [ ] land use names

**Comment by xmd5a2** [comment]
Most of icons not related to car were hidden from default style and car mode (shops, offices, amenities etc.) at zoom <= 16. Also power towers ans power lines, barriers, public transport stops.

**Comment by dmpr0** [comment]
![Screenshot 2024-07-18 at 11 44 14](https://github.com/user-attachments/assets/d2365ac3-7025-4cad-8f45-6288cb7a65c0)
![Screenshot 2024-07-18 at 11 42 39](https://github.com/user-attachments/assets/e0d65c6c-904f-471d-b182-c5c9d9a596fd)
![Screenshot 2024-07-18 at 11 41 46](https://github.com/user-attachments/assets/7d7a212d-5580-4d05-9c89-ccf7eeabffdb)
![Screenshot 2024-07-18 at 11 41 32](https://github.com/user-attachments/assets/b3eb485d-b21d-4912-83d0-c111fd852fb6)

**Comment by DmitryAlexei** [comment]
Most of the time when navigating in the city, zoom levels are above 16, so different POIs are still visible all the times. House names, barriers, land use names also clutter the map.
Below are some screenshots with speeds and zoom levels.
It is proposed to hide most of the icons at zoom **<= 18** (now they are hidden at zooms <= 16)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5e7b4735-2204-47d0-a675-083d22668ebf"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/823ccf6c-bb5a-4005-ae23-64310de32d8b"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/39e863d6-6701-47ef-972e-1651e21029f5"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Another issue with AA, that many objects are displayed on parallel streets, and not in the direction of movement.
It is much more important to see objects in front rather than on the sides.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/6577fc62-bf6b-4ce5-8538-ef4ca255a1a0"  width="700" height="auto"/> </td>
  </tr>
</table>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/891be779-614c-4bfa-b965-fa4480063871"  width="700" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Important POI should be groupped   - related https://github.com/osmandapp/OsmAnd-Issues/issues/2620
To do  hide
- [ ] Electric pipeline 
- [ ] Electric transformer
- [ ] Benches
![image](https://github.com/user-attachments/assets/0a69f6d5-5ad5-4277-bc61-e201e3f2b61b)

**Comment by dmpr0** [comment]
![Screenshot 2024-07-31 at 16 32 41](https://github.com/user-attachments/assets/9b7c09df-98fe-4a37-b699-6f6cda0692f3)
![Screenshot 2024-07-31 at 16 33 43](https://github.com/user-attachments/assets/6118319d-e731-468a-af9a-a273fc3d2c25)

**Comment by cascer1** [comment]
Instead of discussing which categories will be hidden on AA, can't this just be a setting? Let people choose which POI icons they do and don't care about.

**Comment by mdykierek** [comment]
Thing is - customization is for "power users". There has to be a functional yet robust default. The first impression is made on defaults. Before one learns how to customize, could drop the app.
