### ISSUE TITLE
Any custom prefix is missed for tags in GPX files exported thru OsmAnd

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19027]
## Description

> Similar iOS issue https://github.com/osmandapp/OsmAnd-iOS/issues/3410

### How to reproduce
* Go to `52.51940, 13.38873`
* Tap on Starbucks
* Add it to favorites, create new group for example `Cafe`
* Go to **My Places** – **Favorites**
* Find new group (Cafe) 
* Tap three dot's menu – **Share**

### Actual result

<details>
    <summary>extensions</summary>

```
    <extensions>
      <gpxtpx:TrackPointExtension />
      <osm_tag_official_name>Starbucks Coffee</osm_tag_official_name>
      <osm_tag_outdoor_seating_yes>yes</osm_tag_outdoor_seating_yes>
      <collapsable_cuisine>cuisine_cafe</collapsable_cuisine>
      <address>Friedrichstraße (Spandau), Berlin</address>
      <amenity_origin>Amenity:Starbucks: sustenance:cafe</amenity_origin>
      <color>#a71de1</color>
      <osm_tag_brand>Starbucks</osm_tag_brand>
      <icon>amenity_cafe</icon>
      <amenity_type>sustenance</amenity_type>
      <amenity_subtype>cafe</amenity_subtype>
      <osm_tag_diet_vegetarian_yes>yes</osm_tag_diet_vegetarian_yes>
      <amenity_name>Starbucks</amenity_name>
      <background>circle</background>
      <osm_tag_takeaway_yes>yes</osm_tag_takeaway_yes>
      <collapsable_wheelchair_accessibility>wheelchair_yes</collapsable_wheelchair_accessibility>
      <osm_tag_toilets_wheelchair_yes>yes</osm_tag_toilets_wheelchair_yes>
      <amenity_opening_hours>Mo-Fr 07:00-21:00; Sa 09:00-21:00; Su 09:00-19:30</amenity_opening_hours>
    </extensions>
```

</details>  

Exported file – [favorites-Cafe.gpx.zip](https://github.com/osmandapp/OsmAnd/files/14167156/favorites-Cafe.gpx.zip)

* `osmand:` prefix for OsmAnd tags is missed.

### Expected result

* Add custom tags prefix `<icon>amenity_cafe</icon>` >  `<osmand:icon>amenity_cafe</osmand:icon>`

**Environment**
OsmAnd Version: OsmAnd~ 4.7.0#1529m, released: 2024-02-05
Android: 14
Device model: Pixel 6A

## ToDo
- [ ] Fix export of custom extensions
- [ ] Remove empty  `<gpxtpx:TrackPointExtension />`

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Original</summary>

```
<wpt lat="37.5460870" lon="-77.4532843">
    <time>2023-06-07T12:31:35Z</time>
    <name>Test</name>
    <type>SOTM</type>
    <extensions>
        <osmand:address>Floyd Avenue (The Fan) 907, Richmond</osmand:address>
        <osmand:icon>place_town</osmand:icon>
        <osmand:background>circle</osmand:background>
        <osmand:color>#ff4e4eff</osmand:color>
        <test:country>United States</test:country>
        <test:state>Virginia</test:state>
        <test:telephone>(804) 828-0100</test:telephone>
        <test:postcode>23284</test:postcode>
        <test:start_date>Thursday, June 8, 2023</test:start_date>
    </extensions>
</wpt>
```

</details>  

<details>
    <summary>Export from OsmAnd</summary>

```
  <wpt lat="37.546087" lon="-77.4532843">
    <time>2023-06-07T12:31:35Z</time>
    <name>Test</name>
    <type>SOTM</type>
    <extensions>
      <osmand:country>United States</osmand:country>
      <osmand:address>Floyd Avenue (The Fan) 907, Richmond</osmand:address>
      <osmand:color>#ff4e4eff</osmand:color>
      <osmand:background>circle</osmand:background>
      <osmand:icon>place_town</osmand:icon>
      <osmand:postcode>23284</osmand:postcode>
      <osmand:telephone>(804) 828-0100</osmand:telephone>
      <osmand:state>Virginia</osmand:state>
      <osmand:start_date>Thursday, June 8, 2023</osmand:start_date>
    </extensions>
  </wpt>
```

</details>  



- [ ] Custom extension `test:` was replaced by `osmand:`

**Comment by vshcherb** [comment]
It's ok, it might be another issue that share shouldn't change original GPX but that's another issue.
