### ISSUE TITLE
Update "Add action" screen – Quick Actions

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19258]
## ToDo
* Update UI, move from bottom sheet to full screen activity 
* Add Search
* Group actions by type / affiliation: Favorites, Tracks, Topography, OpenStreetMap
* Add actions used by external keyboards

# Add action, [Figma](https://www.figma.com/file/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?type=design&node-id=1955-91556&mode=dev)

<table style="width:100%">
  <tr>
    <th>Add action</th>
    <th>Group</th>
    <th>Group</th>
    <th>Search</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/46503307-26bd-4967-8297-cfc5098e10c3"  width="150" height="auto"/></td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c037f754-3273-425d-a607-5bddde7282d4"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b6c4de2c-1213-4a22-9bef-fa3f74980918"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6eb1fad3-b5b4-4c00-b7ab-00a8015a9533"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Use full screen activity instead of bottom sheet
- [x] Divide actions into groups
- - [x] Sort by A-Z
- [x] Tap on group, open separate screen with the list of available actions

### AppBar

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/655fdbe8-d369-4f4a-88e8-15af4eb722d2"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Left action = Close
- [x] Right action = Search
- - [x] Tap open Search screen 

### Groups

- [x] **Audio / Video notes** 
- - [x] Icon – `ic_action_micro_dark`
- - [x] Visible if plugin is On

- - -

- [x] **Configure Map**
- - [x] Icon – `ic_layer_top`
- [x] Actions 
- - [x] Show/hide – POI
- - [x] Add map marker
- - [x] Add Parking place
- - [x] Show/hide – Public transport
- - [x] Show/hide – Mapillary
- - [x] Change Map source
- - [x] Change Map Overlay
- - [x] Change Map Underlay

- - -

- [x] **Favorites**
- - [x] Icon –  `ic_action_favorite`
- [x] Actions 
- - [x] Add favorites
- - [x] Show/hide – Favorites

- - -

- [x] **Map appearance**,
- - [x] Icon – `ic_action_map_style`
- [x] Actions 
- - [x] Switch Day/Night mode
- - [x] Change Map style

- - -

- [ ] **Map interactions**, 
- - [ ] Icon – `ic_action_map_move_up`
- [x] Add actions
- - [x] **Move up**, icon – `ic_action_map_move_up`
- - [x] **Move down**, icon – `ic_action_map_move_down`
- - [x] **Move left**, icon – `ic_action_map_move_left`
- - [x] **Move right**, icon – `ic_action_map_move_right`
- - [x] **Zoom in**, icon – `ic_action_magnifier_plus`
- - [x] **Zoom out**, icon – `ic_action_magnifier_minus`
- - [x] **Move to My location**, icon – `ic_action_my_location`

- - -

- [x] **Navigation**
- - [x] Icon – `ic_action_gdirections_dark`
- [x] Actions:
- - [x]  Voice on/off
- - [x]  Direction from
- - [x]  Add first intermediate
- - [x]  Replace destination
- - [x] Auto-zoom map
- - [x]  Start/stop navigation
- - [x]  Pause/Resume navigation
- - [x] Delete next destination point
- - [x]  Simulate location by GPX

- - -

- [x] **OpenStreetMap Editing**
- - [x] Icon – `ic_action_openstreetmap_logo`
- - [x] Visible if plugin is On
- [x] Actions
- - [x] Add OSM Note
- - [x] Add POI
- - [x] Show/hide – OSM Note

- - -

- [x] **Settings**
- - [x] Icon – `ic_action_settings`
- [x] Actions 
- - [x] **Next app profile**, icon – `ic_action_profile_next`
- - [x] **Previous app profile**, icon – `ic_action_profile_previous`
- - [x] Change – Display position always in center
- - [x] Change app profile

- - -

- [x] **Topography**
- - [x] Icon – `ic_action_terrain`
- - [x] Visible if plugin is On
- [x] Actions
- - [x] Show/hide – Contour lines
- - [x] Show/hide – Terrain 

- - -

- [x] **Tracks**
- - [x] Icon – `ic_action_polygom_dark`
- [x] Actions
- - [x] Show/hide – Tracks
- - [x] Add track waypoint *

- - -

- [x] **Weather**
- - [x] Icon – `ic_action_umbrella`
- - [x] Visible if plugin is On
- [x] Actions:
- - [x] Show/Hide – Temperature layer
- - [x] Show/Hide – Wind layer
- - [x] Show/Hide – Pressure layer
- - [x] Show/Hide – Precipitation layer
- - [x] Show/Hide – Clouds layer
- - [x] Open Weather screen

**Comment by dmpr0** [comment]
# Review
- [ ] All map buttons is visible in voiceover mode
- [ ] Use Native AppBars

- - -
![Screenshot_20240523-103703](https://github.com/osmandapp/OsmAnd/assets/9365308/c921398e-cc67-4c15-96f1-e1e1d5c15c3d)


- [ ] Appbar shadow?
- [ ] Native AppBar
- [ ] AppBar Should minimize while scroll?

**Comment by dmpr0** [comment]
**Navigation**
- [ ] Emit navigation hint

**UI Control:**
- [ ] Open Navigation view
- [ ] Open Search
- [ ] Show/hide side menu
 - [ ] Activity back pressed

**Comment by dmpr0** [comment]
## Review

### Names
- [ ] Use new naming rules for actions: "Verb + Action", for example "Add Favorite"

### Groups
- [ ] Divide actions into groups:
- - [ ] Configure Map
- - [ ] Map interactions
- - [ ] My places
- - [ ] Navigation
- - [ ] Settings

**Comment by dmpr0** [comment]
## Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/d4c76ace-4a36-4398-8903-f0902276059e"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] **Add action** screen is visible after taping Apply on action screen.

 - - -

- [ ] Crash – [exception.log](https://github.com/user-attachments/files/16030348/exception.log)

> Device : bluejay
> Brand : google
> Manufacturer : Google
> Model : Pixel 6a
> Product : bluejay_beta
> Build : AP31.240426.023.B4
> Version : 14
> App Version : OsmAnd~
> Apk Version : 4.8.0#2617m 4800

**Comment by dmpr0** [comment]
# Review 2

<table style="width:100%">
  <tr>
    <th>Proper name</th>
    <th>Name show **Disable**</th>
    <th>Empty search results</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/07491fd5-d7d4-40e5-a899-4f2250e71eea"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/403d669a-b535-42b2-aa17-f6c5e57aa9fc"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/80a069f1-e05b-49ff-a673-e525696bc742"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] `Change – Display position always in center` is lost?
- [ ] It also has broken name

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/quick-action#add-and-delete-actions
