### ISSUE TITLE
Units is missed for Cadence sensor

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19300]
## Description
Any units is displayed for Bicycle cadence sensor

### How to reproduce
* Connect any Cadence sensor to OsmAnd
* Add Bicycle cadence widget

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Widget</th>
        <th>Sensort screen</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/38674d62-033b-4dab-8700-f4e82ccfd54e"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/35a1381a-b0b1-411c-8ed2-15f39efed646"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Units is missing

### Expected result
* RPM https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L393

## ToDo
- [x] Add units **RPM** - `revolutions_per_minute_unit`
- - [x] Top / Bottom widget
- - [x] Left / Right widgets.
- [x] Check if graphs show units for Bicycle cadence graph

**Environment**
OsmAnd Version: OsmAnd~ 4.7.0#1797m
Android: 14
Device model: Pixel 6A
Sensor: Garmin Cadence Sensor 2

**Comment by dmpr0** [comment]
# Review 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/f8d6efc8-324e-4a79-a88a-a0d12c297462"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Add units to the sensor settings screen
