### ISSUE TITLE
Vertical exaggeration – 3D Relief

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19474]
# Description 
Add UI for **Vertical exaggeration** option that should allow to upscale 3D relief.

> OpenGL Team task https://github.com/osmandapp/OsmAnd/issues/19443

# ToDo

> API from @Andrewschenko 
> Added core function to support exaggeration of terrain elevation: [link](https://github.com/osmandapp/OsmAnd-iOS/pull/3580)
> Added method to support exaggeration of track elevation: [link](https://github.com/osmandapp/OsmAnd-core/blob/master/include/OsmAndCore/Map/VectorLineBuilder.h#L121)

## Configure map
We need to change **3D Relief** list item similarly to **Terrain**, with two action: open inner screen and switch to turn on/off option.

<details>
    <summary>Screenshot</summary>
<img src="https://github.com/osmandapp/OsmAnd/assets/9365308/11896e7f-5b8f-4af0-b085-d0c27e4fb510"  width="auto" height="auto"/>
</details>  

- [x] Add open inner screen action to **3D Relief** item
- - [x] Tap on left side – open inner screen
- - [x] Tap on right side (switch) – turn on/off 3D Relief

## 3D Relief
Separate screen to configure **3D Relief** and all included options.

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Off</th>
        <th>On</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/a01cabcd-eec3-4a49-9ec8-1f595722da8b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/b0752af4-560d-4f8b-b1bd-887529581288"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Add item **Vertical exaggeration**
- - [x] Icon – `ic_action_terrain_scale`
- - [x] Show selected value on the right side
- [x] Show **Download maps** card, should look and work the same as in the Terrain menu.

## Vertical exaggeration
Separate screen to configure selected parameter, UI is similar to **Visibility** in **Terrain**.

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/efdf8d92-263f-49d9-b906-8b37a047afda"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Use slider to change parameter
- - [x] Available parameters: None / x1 / x2 / x3 
- - [x] Default – None
- [x] Add description – `By changing the scale value, you can emphasise the 3D relief.`

**Comment by EugeneZmeuk** [comment]
**01.05.2024**
- [ ] [Topography](https://osmand.net/docs/user/plugins/contour-lines#vertical-exaggeration)

**Comment by fillwithjoy1** [comment]
I've not been able to find this setting on 4.7.10 on Android. Am I missing something, or am I just stupid?

**Comment by EugeneZmeuk** [comment]
> I've not been able to find this setting on 4.7.10 on Android. Am I missing something, or am I just stupid?

Update to 4.7.14 ( 4.7.10 version has not vertical exaggeration)

**Comment by fillwithjoy1** [comment]
Dear Rohan,
I don't think I'll need a session because after 11:00 a.m. I will just be finishing English exams
However, I do have a chemistry exam in the morning so maybe later today is a session if that works for you at all
Thanks,
Joy

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am95c2luZ2guanMxQGdtYWlsLmNvbQ==>
