### ISSUE TITLE
Attach to the roads > Start automatically

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd#19745]
### Describe the idea (required)

If you need the "Attach to the roads" option with every route, 
the automatic start option "Attach to the roads" would be an advantage.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/146021011/4331df11-f6eb-4085-a6e3-a09f64fb9834"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about the expected behaviour (required)

I start the "Attach to the roads" option with every route because otherwise I get too many turn-by-turn directions.

### Tell us about alternatives you've considered (required)

Integrate the option "Attach to roads" 
automatically in the motorbike profile.

**Comment by dmpr0** [comment]
## ToDo

### Navigation settings 

<table style="width:100%">
  <tr>
    <th>Always</th>
    <th>Ask every time</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/974712d2-270b-4325-bd2a-299772629cdc"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/6cabad8c-dc12-4f7b-85c5-0dd4e2b5102a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Biker729** [comment]
Ab welcher OsmAnd Version ist das verfügbar. ?

**Comment by dmpr0** [comment]
> Ab welcher OsmAnd Version ist das verfügbar. ?

It will be part of the upcoming 4.8 release.

**Comment by Biker729** [comment]
very good, thanks

Am Do., 11. Juli 2024 um 18:01 Uhr schrieb Dmytro Prodchenko <
***@***.***>:

**Comment by sonora** [comment]
Rather than hiding the option once 'Always' has been selected, and thus making this rather intransparent, wouödn't it be better to still show the 'Attach to rosds' switch, ond only pre-select it to 'on'?

Then the user can also de-select it on a case-by-case basis. And it is in any case visible that there has been an 'on' preselection?

**Comment by dmpr0** [comment]
> Rather than hiding the option once 'Always' has been selected, and thus making this rather intransparent, wouödn't it be better to still show the 'Attach to rosds' switch, ond only pre-select it to 'on'?
> 
> Then the user can also de-select it on a case-by-case basis. And it is in any case visible that there has been an 'on' preselection?

Attach to the roads doesn't have switch. 
By default it set to Ask every time. Core team says that Attach to road algorithm work fast so it should not be a problem.

**Comment by sonora** [comment]
Right, thanks @dmpr0 !

My understanding was we perhaps create a way here for users to hide an option out of sight for good. And then mostly over time users tend to forget this, and this will start causing support issues, if it is not clear (visible) what had happened and how o back it out.

**Comment by franco999** [comment]
Is this option already implemented in the nightly version? Because it doesn't appear where it should.

`OsmAnd~ 4.8.0#2830m, Released: 2024-07-24`

<img height="300px" src="https://github.com/user-attachments/assets/88d785b2-c818-4602-91ad-626e9f56c01c">

**Comment by dmpr0** [comment]
## Review

- [ ] Second line should reflect selected status, change Automatically to Always.

**Comment by DmitryAlexei** [comment]
- [ ] during testing we should double-check attach-to-roads screen in the plan-a-route

**Comment by DmitryAlexei** [comment]
tested on OsmAnd~ 4.9.0#2894m, released: 2024-08-02 when Detailed track guidance is set to Always 
- in some situations (even when track is correctly attached to roads), in navigation > details > turn-by-turn it is proposed to Attach track to the roads (see screenshot)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1223ed2e-3cb7-4dc7-bf19-0b78fd85b5dd"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
It is also proposed to attach tracks to roads in the opposite direction when the end of a track is the nearest point to My location

**Comment by scaidermern** [comment]
> It is also proposed to attach tracks to roads in the opposite direction when the end of a track is the nearest point to My location

Careful if the track is a round trip. Then both start and end will be close together.

**Comment by EugeneZmeuk** [comment]
**Docs**
- [ ] [Navigation settings  >  Other](https://osmand.net/docs/user/personal/profiles#navigation-settings)
- [ ] [Navigate by track > Attach to roads](https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-the-roads)

**Comment by Biker729** [comment]
Wo finde ich bei "Apple IOS" die Option "An Straßen anhängen“
Diese Option ist bei Navigation mit dem Motorrad zwingend erforderlich 
da ich sonst zu viele detaillierte Ansagen bekomme.

Wünschenswert wäre die gleiche Option wie mit OsmAndm Android "Detaillierte Streckenführung > Jederzeit."
![1](https://github.com/user-attachments/assets/7d275137-41ff-4f6a-9bf9-1d3e2f9e8967)

**Comment by scaidermern** [comment]
> Wo finde ich bei "Apple IOS" die Option "An Straßen anhängen“

Does the documentation help?
https://osmand.net/docs/user/navigation/setup/gpx-navigation#attach-to-the-roads
https://osmand.net/docs/user/navigation/setup/gpx-navigation#follow-track-options

**Comment by Biker729** [comment]
Danke habe ich gefunden,
nachdem ich unter  IOS „Track folgen  - Auf Straßen einrasten“ - Fortfahren auf Anwenden 
drücke Stürzt die App jedesmal ab.

Der gleiche Track funktioniert mit Android ohne Probleme.

Auch die Option „An Straßen anhängen“ automatisch fehlt bei IOS was sehr umständlich ist jedesmal bei einem Neustart der Route.

**Comment by scaidermern** [comment]
> nachdem ich unter IOS „Track folgen - Auf Straßen einrasten“ - Fortfahren auf Anwenden
> drücke Stürzt die App jedesmal ab.

It would be the best to create a separate issue for this crash.
