### ISSUE TITLE
Improvements for 3D track view

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#19785]
## Description
Previous task https://github.com/osmandapp/OsmAnd-Issues/issues/2436

## ToDo

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Visualized by</th>
        <th>Wall color</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/49e3198c-d386-4c10-bbb1-917a170ecc8a"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eab928a4-b525-4c1b-852b-31ebc090c6ec"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Place **Wall color** as third parameter below **Track line**

### Wall color
- [x] Solid / Downward gradient / Upward gradient
- - [x] Track line – user selected color
- - [x] Wall color – user selected color
- [x] Altitude / Slope / Speed
- - [x] Track line – user selected color
- - [x] Wall color – selected gradient (Altitude / Slope / Speed)

### Visualized by

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Altitude</th>
        <th>Fixed height</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/c7235824-8a04-4340-9196-43326937cad6"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/8998c25f-c753-4046-9826-6b430d047b57"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/353530ad-afdd-4142-abeb-0bb75a0f1a13"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x]  If **Visualized by** = **Fixed height**, change **Vertical exaggeration** to **Wall height**

**Add new options:**

- [x] Speed
- [x] Heart rate
- [x] Bicycle Cadence
- [x] Bicycle Power
- [x] Temperature
- [x] And all other with numers
- [x] Add Height from Relief (altitude from track) - if 3D relief is ON for for all types of visualization except "By height"

**Comment by DmitryAlexei** [comment]
iOS task https://github.com/osmandapp/OsmAnd-Issues/issues/2520

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/20319c04-56fa-4b56-8a82-e5aa5eff5834"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/c2a3ce8a-8914-4a53-a790-924ab068d343"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  


Example track – [LycianWayRealTrack2015.gpx.zip](https://github.com/user-attachments/files/16374020/LycianWayRealTrack2015.gpx.zip)

- [ ] Visualised by should show only available parameters 
- [ ] Lag while switching between presented options

**Comment by DmitryAlexei** [comment]
- [ ] 3d relief + 3d speed the graph is not visible

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/ec31976a-9a59-4c65-87a3-ee17efcb9f1b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/eab928a4-b525-4c1b-852b-31ebc090c6ec"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>  

- [ ] Missing divider

**Comment by dmpr0** [comment]
# Review 

- [ ] Wall color doesn't work. It use Track line color parameter always, but should only if Solid is selected
