### ISSUE TITLE
Add Quick action: to Show / Hide Routes on the map

### ISSUE THREAD

**Issue by Vucumpra** [osmandapp/OsmAnd#19811]
### Describe the idea (required)

Hello,
In some case, will be comfortable to show/hide "Routes" by one touch.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/156325356/d87caf47-b1cb-49fb-a75c-c31d1373c0b5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/156325356/8483db19-3381-4be1-ae3a-e1f04fcb6318"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/156325356/d9414442-2f89-4f19-a18a-e08d24ad40c7"  width="300" height="auto"/> </td>
  </tr>
</table>

### Tell us about the expected behaviour (required)

Add new type of action in  action list for custom buttons

### Tell us about alternatives you've considered (required)

nothing

**Comment by vshcherb** [comment]
We need add variety of show / hide routes or create a setting for it.

**Comment by dmpr0** [comment]
## ToDo
We need to add new set of Quick Actions to Configure Map group.

**Comment by DmitryAlexei** [comment]
- additional settings for routes are not saved after switching routes off

**Comment by shurasmiling** [comment]
- [Vector Maps - Configure Map Style](https://osmand.net/docs/user/map/vector-maps/#routes)
- [QA - Configure map](https://osmand.net/docs/user/widgets/quick-action#configure-map)

**Comment by EugeneZmeuk** [comment]
**01.01.2024 Review**
- [ ] [quick action  - table of actions](https://osmand.net/docs/user/widgets/quick-action/#configure-map)
    - needed to add info about Routes settings (show Routes with last settings after buttons tapping)
 - [ ] [vector maps - routes](https://osmand.net/docs/user/map/vector-maps/#routes)
     - needed to add info about Routes settings (show Routes with last settings after buttons tapping)
     - re-write "In OsmAnd app you can select GPX routes...", it's not GPX route. Text: [Routes from OSM (link)](https://wiki.openstreetmap.org/wiki/Relation:route) - [hiking](https://wiki.openstreetmap.org/wiki/Tag:route%3Dhiking), [bicycle](https://wiki.openstreetmap.org/wiki/Cycle_routes)...., what is it, and all this data from OpenStreetMap(link).
     - "Read about the color scheme of routes in the [Color Palette Schemes](https://osmand.net/docs/user/personal/color-palette-schemes) article." - adding about Paid function
 - [ ] [Track and routes](https://osmand.net/docs/user/map/tracks-on-map/#quick-actions-for-routes)
      - needed to add info about Routes settings (show Routes with last settings after buttons tapping)
