### ISSUE TITLE
Quick Action: Add Track Waypoint no longer allows choosing position

### ISSUE THREAD

**Issue by akkana** [osmandapp/OsmAnd#20102]
### Description

I have the Quick Action set to Add Track Waypoint. This used to give me a view of where the point to be added was on the map, and I could drag the map around under the point if it was in the wrong place. (99.99% of the time I want it to be at my current position, but it seldom is there by default.)

Recently, it changed so that the positioning screen is no longer shown. First it gives me a list of all the tracks currently showing (so I choose Currently Recording Track), and then it goes toe a dialog letting me set various attributes of the waypoint (name, color, icon etc). Both of these dialogs take up pretty much the whole screen (so if there's a map behind them, I can't get to it), and once I click Save from the second dialog, it's saved, without my ever getting a chance to choose the position.

Could the positioning screen please come back? Or, even better, could there be a quick action that makes a waypoint at the current GPS location?

### Steps to reproduce

Set Quick Action to Add Track Waypoint. Move the map around so that the marker for the current position isn't auto-positioned on the screen. Tap Quick Action and go through the two dialogs to set a waypoint in the currently recording track.

### Actual result

A waypoint is added, but there's no way to set its position.

### Expected result

There should be some way to set the position of a new waypoint, or at least predict where it will appear.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.17
Android/iOS version: 14
Device model: Pixel 6a
Crash-Logs: ?
```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, set the Quick Action to "Add Track Waypoint" and move the map so that the current GPS position marker is not in the center or is out of view. Use the Quick Action button to add a Waypoint, choose "Currently Recording Track" from the options, and then proceed through the following dialogue to set attributes like waypoint name, color, and icon. Note that there is no opportunity to interact with the map to adjust the waypoint's position before finalizing.

OsmAnd~ 4.8.0#2509m, released: 2024-06-14


https://github.com/osmandapp/OsmAnd/assets/127092082/3f54fdd3-a387-4831-b079-63cdaeb3f120

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. The first video shows the old version of the Quick Action button, where multiple actions can be assigned to a single button, and you can choose the location for adding a Track Waypoint by moving the orange marker.

In the second video, the new version of the Quick Action button, which allows only one action to be selected, and the location for adding a Track Waypoint cannot be chosen.

OsmAnd~ 4.8.0#2548m, released: 2024-06-21

<table style="width:100%">
  </tr>
  <tr>
    <th>Old version of Quick Action</th>
    <th>New version of Quick Action</th>
  </tr>
  <tr>
   <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/de5c7b29-20b5-4120-adcd-3a4168ab2e61"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/7ddd929f-0882-47ac-b4cb-c9c33ef04cde"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Add new option **Point Placement**: with parameters
- - [ ] **Map center**
- - [ ] **Ask**
- [ ] Quick actions: 
- - [ ] Add Track Waypoint
- - [ ] Add Favorites
- [ ] Replace current (outdated) Move marker dialog

**Comment by Zirochkabila** [comment]
# **Testing 1**

`OsmAnd~ 5.0.0#4596m, Released: 2025-03-07`
[quick actions.osf.zip](https://github.com/user-attachments/files/19125973/quick.actions.osf.zip)

## 🟠 **Major**

- [ ] **1. The set point is not always displayed on the map (with both settings)**
- **Issue:** The set point intermittently does not appear on the map. Similar issue observed on the [WEB](https://github.com/osmandapp/web/issues/653#issuecomment-2656866265).

[logcat (2).log](https://github.com/user-attachments/files/19126032/logcat.2.log)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/315cc29f-e468-499d-a155-73eb299966ca"></video>
</details>

- [ ] **2. For a moment, all other points are no longer displayed on the map after adding a point in Manual mode**
- **Issue:** Possibly related to the issue where the set point is not displayed. This may affect map visualization.

[logcat (3).log](https://github.com/user-attachments/files/19126066/logcat.3.log)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/7bc3d64c-6fd6-4575-9d35-72975a74e807"></video>
</details>

- [ ] **3. Adding a Waypoint (Manual mode) opens the keyboard, blocking the bottom part of the screen**
- **Issue:** The on-screen keyboard covers the functionality of the lower screen, preventing the addition of a point to the map.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/a0f75fd7-fdd3-426b-82ee-76fe41a14d90"></video>
</details>

## 🟡 **Minor**

- [ ] **1. Sorting options are displayed in reverse order**
- **Issue:** Sorting options appear in the opposite order than expected, potentially causing confusion.

<details><summary>Details</summary>
<img width="400" src="https://github.com/user-attachments/assets/d10c2a69-f218-4f5a-843e-bae1ded52671"></img>
</details>

- [ ] **2. Different icon displayed when adding a point to the map**
- **Issue:** A different icon is shown during the selection process compared to the assigned icon for the specific Favorites group. The correct icon is displayed only after the point is added.

<details><summary>Details</summary>
<img width="400" src="https://github.com/user-attachments/assets/11180be6-403a-42bc-876f-58fb586764fd"></img>
</details>

- [ ] **3. After adding an Audio Note, a free space appears at the bottom of the screen**
- **Issue:** When an audio note is added, extra space appears at the bottom of the screen, causing buttons to shift upward.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/7c4f0d23-0cbf-4a1f-bf59-377c43433647"></video>
</details>

- [ ] **4. After adding POIs (in any mode), the map twitches**
- **Issue:** Adding points of interest causes the map to visually twitch, potentially distracting the user.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/ee1d90aa-55dc-467b-9d67-c6974bfb7685"></video>
</details>

- [ ] **5. Adding a video note displays the camera interface below the buttons**
- **Issue:** The camera interface overlaps with UI buttons, impacting usability when recording a video note.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/c3dcdcca-83fd-4ac9-9357-bf4750edc2a8"></video>
</details>

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/00b50b9f-dc00-4d1c-94ee-4da32b41492c"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Divider below parameters?

- - - 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4d7869c7-0918-4c0e-aeb4-2739da53f999"  width="400" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Point not centered in Landscape

**Comment by DmitryAlexei** [comment]
May be related
- https://github.com/osmandapp/OsmAnd/issues/15265

**Comment by Zirochkabila** [comment]
# **Testing 2**
`OsmAnd~ 5.1.0#5014m, Released: 2025-04-15`

## 🟡 Minor

- [ ] **In the video, the point is shifted to the right of the center in landscape orientation, which can affect navigation accuracy and map readability.**

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/28f862ed-3a19-4009-a86b-3aeac822a402"></video>
</details>

**Comment by fcg42** [comment]
Hello,

Besides the "Manual" and "Map Center", I think it makes sense to add another: "Current position". 

The difference between "Current position" and "Manual" is that it doesn't require the user to confirme (touch the screen) to accept and save the point. 

Why is this needed?
So the users can add waypoints without stoping, by just pressing a button on a remote controller. 

Before, when we didn't had this two options, that was the default behaviour and was very good for this scenario. With the new options the previous one is broken.

The workaround if to navigate with the arrow in the center of the screen, so it coincides with the drop position of the waypoint "Map center".

thank you for your time and dedication to build such a powerful and customizable tool.
