### ISSUE TITLE
Allow to set different layout for widget panels on map screen

### ISSUE THREAD

**Issue by Rowin63** [osmandapp/OsmAnd#20155]
### Description

see the attached screenshot.
On both sides of the screen data fields are covered by buttons.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/95540936/2a457d8d-79fc-49c0-a1c3-655251105a96"  width="600" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

see the screenshot.

### Actual result

data fields are covered.

### Expected result

move the buttons to not cover the data fierlds.

### Your Environment (required)

+4.8.0

**Comment by Sonwon1** [comment]
There is a open request to make the all of the onscreen icons movable. This would allow users to sort their screen how they prefer.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it, add more widgets to both the left and right panels, activate navigation, and then rotate the phone horizontally.

As a result, you'll notice that the zoom and 3D buttons on the right side will overlay the widgets. Similarly, the speedometer on the left side will also cover the widgets.

OsmAnd~ 4.8.0#2568m, released: 2024-06-24

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/127092082/a5f60155-591a-4c57-86a1-d290e15859dc"  width="700" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# To-Do

### ⚠️ Important tech note

- [x] We should allow many layouts inside 1 profile. So in future we should not limit only for 2 layouts / Portrait / Landscape. We should store / display multiple layouts, in future it could be "Android Auto", "External Monitor"... This influences how we store data in files / settings / OsmAnd Cloud

# Main

<table style="width:100%">
  <tr>
    <th>Default</th>
    <th>Portrait</th>
    <th>Landscape</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/fac25921-31a4-488c-935e-b30b433c5df6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3cc99ded-296d-485b-8581-e0698da2f1ff"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1473c38c-d131-4c21-8de0-d8e054cc0655"  width="300" height="auto"/> </td>
  </tr>
</table>  
 

## AppBar Changes
<table style="width:100%">
  <tr>
    <th>Updated AppBar</th>
    <th>Actions menu</th>
  </tr>
  <tr>
    <td valign=top><img src="https://github.com/user-attachments/assets/f4677666-a3bd-4cd2-851b-e7d575dcc0b6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/3f8b3548-9a36-4c54-9f32-be4ed96c1509"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Remove the profile chip switcher from the **AppBar**.
- [x] Add the current profile icon to the **NavBar**.
- - [x] A tap should open the existing bottom sheet.
- [x] Add a **More Actions** menu (three-dot icon).
- - [x] Move the **Help** action to this menu.
- - [x] Add a new **Map screen layout** action, using the `ic_action_map_screen_layout_portrait` icon.
- - - [x] Tapping this action should open **Map screen layout** bottom sheet.

## Tabs

<table style="width:100%">
  <tr>
    <th>Portrait</th>
    <th>Landscape</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/233806b3-6db0-426e-aa94-fedb1537b824"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/09e243d0-97ad-42ae-be5e-ac06c660a398"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Display tabs only when the **Map screen layout** is set to **Separate layouts**.
- - [x] Create two tabs: **Portrait** and **Landscape**.
- - [x] Change icons for Widget panels. Use default icons if layout not separated

**Widget panels, updated icons:**
- [x] Left panel
- - [x] Portrait – `ic_action_device_portrait_panel_left`
- - [x] Landscape – `ic_action_device_landscape_panel_right`
- [x] Right panel
- - [x] Portrait – `ic_action_device_portrait_panel_right`
- - [x] Landscape – `ic_action_device_landscape_panel_right`
- [x] Top panel
- - [x] Portrait – `ic_action_device_portrait_panel_top`
- - [x] Landscape – `ic_action_device_landscape_panel_top`
- [x] Bottom panel
- - [x] Portrait – `ic_action_device_portrait_panel_bottom`
- - [x] Landscape – `ic_action_device_landscape_panel_bottom`

# Map screen layout, [Figma](https://www.figma.com/design/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=2949-50114&m=dev)

## Introduction card
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/30e1b890-805c-4a7f-b41a-ced525a664b1"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Show introduction card: (We use the same layout for OsmAnd Cloud promotion in Settings)
- - [x] Icon – `ic_action_map_screen_layout_portrait_colored`
- - [x] Title – `Map screen layout`
- - [x] Description – `Choose whether to use a single layout for all orientations, or customize Portrait and Landscape separately.`
- - [x] Action – `Use Separate layouts`. 
- - - [x] Tap – switch two layout mode

## Screen

<table style="width:100%">
  <tr>
    <th>Single</th>
    <th>Separate</th>
  </tr>
  <tr>
      <td><img src="https://github.com/user-attachments/assets/6f5f9781-5942-4001-99af-57c9026ba5d4"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6bf657a7-e74d-4bb7-b70c-a661a756b7d8"  width="200" height="auto"/> </td>
  </tr>
</table>   


- [x] Screen title – `Map screen layout`
- [x] Show preview box, width = screen width, height = 229 dp
- - [x] Background color `activity_background_color`
- - [x] Change preview image depend on selected option
- [x] Description – `Choose whether to use a single layout for all orientations, or customize Portrait and Landscape separately.`

**Options:** 
- [x] **Single layout**
- - [x] Selected by default
- - [x] Image – `img_map_screen_layout_single_day/night`
- [x] **Separate layouts**
- - [x] Image – `img_map_screen_layout_separate_day/night`

# Panels layout, [Figma](https://www.figma.com/design/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=2864-541382&m=dev)

New parameters that allows to selected how top and bottom panels will fit into layout.

- [x] Show if **Map screen layout** set to **Separate layouts**

## Item

<table style="width:100%">
  <tr>
    <th></th>
    <th>Portrait</th>
    <th>Landscape</th>
  </tr>
  <tr>
    <td>Compact</td>
    <td><img src="https://github.com/user-attachments/assets/1b5a796f-15f7-42b9-b3cf-e50d4835700c"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a2dd6dc7-b2df-489a-889f-01e826c88c62"  width="200" height="auto"/> </td>
  </tr>
  <tr>
    <td>Wide</td>
    <td><img src="https://github.com/user-attachments/assets/d7ce1bf5-7b6d-449a-a48a-04cd2effad6f"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ef273b78-98e1-4a3e-88ab-5a666045e6cf"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Name – **Panels layout**
- [x] Icon should depend on tab: Portrait or Landscape and selected parameter 
- [x] Landscape: Wide – `ic_action_panels_layout_landscape_wide`, compact – `ic_action_panels_layout_landscape_compact`
- [x] Portrait: Wide – `ic_action_panels_layout_portrait_wide`, compact – `ic_action_panels_layout_portrait_compact`


## Screen
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c358364a-d3dd-455e-9905-9091e6ed5738"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/472170aa-2ca5-45c0-90a7-9958c8718c4b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/dff95e4a-3f7d-434b-8349-2f69109e6be2"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Title – **Panels layout**
- [x] Show preview box, width = screen width, height = 229 dp
- - [x] Background color `activity_background_color`
- - [x] Change preview image depend on selected option and current orientation
- [x] Description – `Choose a layout for the top and bottom panels. They can either be wide, spanning the full width of the screen, or compact, fitting between the side panels and buttons.`

**Preview image:**
- [x] **Portrait**
- - [x] Wide – `img_panels_layout_portrait_wide_day/night`
- - [x] Compact – `img_panels_layout_portrait_compact_day/night`
- [x] **Landscape**
- - [x] Wide – `img_panels_layout_landscape_wide_day/night`
- - [x] Compact – `img_panels_layout_landscape_compact_day/night`

# Open panels
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/246debdb-cb19-457a-8dde-3b156cd35dc2"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/a1ea9a30-c2dd-4948-a506-78cf91170224"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Add action **Copy from Portrait layout**
- - [x] Icon – `ic_action_copy_from_portrait`
- - [x] Tap – should copy widget list from Portrait layout of the same profile
- [x] Add action **Copy from Landscape layout**
- - [x] Icon – `ic_action_copy_from_landscape`
- - [x] Tap – should copy widget list from Landscape layout of the same profile

## Follow up
- https://github.com/osmandapp/OsmAnd/issues/22693
- By default provide another landscape layout for driving profile set of widgets to be discussed...

**Comment by dmpr0** [comment]
## Current issues

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th colspan=2>Audio note</th>
        <th>Video note</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/40510c2d-74c5-49e0-8e86-3ba50d02b790"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/e5f878bb-1ee0-49d9-be45-b770f47bf5d0"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4d48f08b-a9da-41cf-9469-1e7345456e0b"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Audio note UI is hidden below bottom widget panel
- [x] Video note ui is not fit into the screen

- - - - - -

- [x] We need to add scrolling to the left and right panels when their height is greater than the screen height.

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/8dd05618-abd3-4ef1-a084-ac60f6b1305c"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/f5adf797-2e28-4b9a-aa57-b7f27b29feb9"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] Wrong position of bottom right buttons in Landscape orientation in case where Top panel is present or not
* * Profile settings – [Автівка.osf.zip](https://github.com/user-attachments/files/22042733/osf.zip)

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#6980m (Released: 2026-01-20)

### **Severity**: 🔴 Critical / **Priority**: 🔴 High

* [x] 1. Attempting to change profile causes freezing and crash (repeats ~1 time every 5 tries)

[exception (41).log.zip](https://github.com/user-attachments/files/24741752/exception.41.log.zip)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/e948ee98-6d52-4602-b569-7f15d82c862c"></video>
</details>


### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [x] 1. Switching to Landscape orientation takes ~3× longer than switching to Portrait orientation (most interactions with the new functionality are accompanied by lag)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/b9565bb5-a205-4c30-bedd-94766e1f495f"></video>
</details>

* [x] 2. Panels layout is available even if **Separate layouts** is disabled (`Show if Map screen layout set to Separate layouts`)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/583f562b-c6e6-4065-864c-6a33db1ad3ed"></video>
</details>

* [x] 3. Panels layout shows **Portrait** orientation although **Landscape** is selected

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/46d8da10-a034-4a28-9646-05b3d69fc413"></video>
</details>

* [x] 4. After installing **Wide**, some widgets are displayed on top of the central widget, and some behind it

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/18278c7b-9e55-450f-9427-fa11d22f902f" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/a0b0e2c8-3a7b-453b-9130-fe2c5943712d" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [x] 5. After installing **Compact**, the interface buttons are shifted

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/99f74b01-485a-4261-86ba-5ce562241fda" width="300" height="auto"/></td>
    <th><img src="https://github.com/user-attachments/assets/42394a40-28e3-4ca7-8b92-ae5350e085fe" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [x] 6. The list of widgets is displayed behind the buttons (information is not visible)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/bc5f803f-7af1-43aa-b65a-34504b798edf"></video>
</details>

* [x] 7. During navigation, widgets and buttons are displayed randomly, speedometer hidden

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/30e84f61-37e1-45dd-bebc-f7e4d4aac9b4" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/a2b94155-581e-435b-b308-db5aa23f9d2c" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/46fee558-3c0e-475e-96b6-7438a5efbfb9" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/11950381-6771-4bc7-bdeb-f8c00bddb525" width="300" height="auto"/></th>
  </tr>
</table>
</details>


* [x] 8. After importing, the configuration is set correctly but is displayed as **Wide** (helps with screen rotation) — manual switching does not help

[Browse map (6).osf.zip](https://github.com/user-attachments/files/24742283/Browse.map.6.osf.zip)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/b3032108-8a47-4317-aec8-09e85d2aa6e6"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/138f3694-01d3-4b64-b429-8e91956e3068"  width="300" height="auto"/> </td>
<th><img src="https://github.com/user-attachments/assets/4d0220d3-c2d7-40c4-9e62-e669f5da4cf7"  width="300" height="auto"/> </th>
  </tr>
</table> 
</details>

- [ ] 9. The Panels layout in the Configure screen is only updated when the profile is changed on the main screen (possibly related to point 8).

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/3e05e3f2-18f3-4d0d-bf1f-6efe3258ea66"></video>
</details> 



### **Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. Buttons during recording **Video notes** are still hidden

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/d6b54de7-dd88-4977-b399-df3bb08618d8" width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/d066d9be-921d-4e89-8d64-65f89fdc82b8" width="300" height="auto"/></td>
  </tr>
</table>
</details>

* [ ] 2. After reducing the size of the widget, the widget name is displayed next to the icon or on the icon

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/f2f060b8-e1b3-44ff-9ba8-d2f5310e95ec" width="300" height="auto"/></td>
    <th><img src="https://github.com/user-attachments/assets/b89ab0a6-07cd-4379-8a8e-c13dee39e689" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/6c5332b1-59c1-4b59-8d9e-7f8717ef08f5" width="300" height="auto"/></th>
  </tr>
</table>
</details>



### **Severity**: 🔵 Trivial / **Priority**: 🔵 Low

* [ ] 1. Add translation for Arabic

<details><summary>Detail</summary>
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/915aa751-6ebd-4fb1-ad1b-40ef2cf7e7bf" width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/b2e170b2-faa0-43a2-b3da-b9e6b9065a3d" width="300" height="auto"/></td>
  </tr>
</table>
</details>

* [ ] 2. It may be worth synchronizing the Screen Orientation icon with Album Orientation (not sure if expected)

<details><summary>Details</summary>
<img width="400" alt="Screenshot" src="https://github.com/user-attachments/assets/1797fad7-36cb-49f2-9310-2baea4e71e25">
</details>

**Comment by dmpr0** [comment]
## UI Review

### Configure Screen
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4e0c55dd-2047-4287-b36b-a90146e05938"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] **Introduction card** increase line height for description


- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/803a0ec0-7920-4647-b59e-2e306ddab2cf"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Swipe left / right should switch tabs

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/efe2bf02-e470-40bc-95d2-b3da3acf7df1"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details> 

- [x] AppBar and Tabs should have the same background color

### Map

- [x] Draw stroke around left / right panel on the phones where inset are present.

**Comment by vshcherb** [comment]
UI Review +
- [x] Compact View for the phone portrait should be calculated that it fits bottom widget and 4 buttons (ruller could go up)
- [x] 6. The list of widgets is displayed behind the buttons (information is not visible). - top buttons should be allowed to move right bottom and should be by default that's different for portrait vs landscape

**Comment by thuryn** [comment]
I often user Osmand on motorbike - in landscape mode. I would like to suggest several UI improvements.
Some of the problem could be done by transparent background of wigdets - but it's not well readable with transparent background when you have one second to check.

My notes

<img width="3216" height="1440" alt="Image" src="https://github.com/user-attachments/assets/3e9f42bf-8738-4235-a169-5f0ecb8fec36" />
<img width="3216" height="1440" alt="Image" src="https://github.com/user-attachments/assets/f15b9c0b-514e-4849-a7de-ff23f9328127" />

- the speedometer should by bellow (see red arrow)
- the  middle widgets can be partialy transparent or it could be one to next the other when info is narrow (it's just a suggestion)
- sometimes there is just one widget in to middle and is completelly void - just white rectangle - it would be nine to hide the widget in that case

**Comment by Sonwon1** [comment]
@vshcherb @Chumva 

When an issue is closed can we also have a noticed for which version of Osmand this will be in?

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.3.0#7175m (Released: 2026-02-16)

### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [x] 1. The speedometer covers the widget about the next turn

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/0629e9e1-ed2a-4f57-85fa-5590896e7f6f" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/addf1b4d-a911-4274-a01d-b1e4eab894f3" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Comment by Chumva** [comment]
@Sonwon1 It is available in nightly & will be available in 5.3 release

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.3.0#7189m (Released: 2026-02-17)

### **Severity**: 🟠 Major / **Priority**: 🔴 High

* [x] 1. In both **Compact** and **Wide** modes, buttons and widgets appear broken (overlapping each other, cropped)

[Автівка.osf.zip](https://github.com/user-attachments/files/25366948/osf.zip)

<details><summary>Details - Compact</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/22921817-f111-4c4b-acaf-0215835c06fb" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/ac223331-8b4f-4ea1-94e4-b58f8230449b" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/40ef7ccc-506d-4a37-bfb4-73949d4ffe95" width="300" height="auto"/></th>
  </tr>
</table>
</details>

<details><summary>Details - Wide</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/09bf2e4f-b57c-463a-a801-7ceeff905ce8" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/19d43fe4-279d-4d03-9091-22e83cb30178" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/a725839d-9ba7-46b9-a4d6-222c740b6ec1" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Comment by Zirochkabila** [comment]
# Testing 3

> OsmAnd~ 5.3.0#7260m, Released: 2026-02-26

Portrait mode - Fixed (no errors observed)

### Landscape orientation

[Driving profile.zip](https://github.com/user-attachments/files/25576113/osf.zip)

### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1. Compact mode - the speedometer shifts when the Menu button appears (the ruler gets in the way)

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/2499f27e-04dd-4a9c-93c8-020a670d4c6a"></video>
  </details>

* [x] 2. Wide mode - the speedometer shifts randomly

  <details><summary>Details</summary>
  <video src="https://github.com/user-attachments/assets/c57e99be-f862-470c-9f5b-b574b4766f34"></video>
  </details>

[Driving_1.osf.zip](https://github.com/user-attachments/files/25576181/Driving_1.osf.zip)

* [ ] 1. Shifted buttons

  <details><summary>Details</summary>
  <img width="900" alt="Screenshot" src="https://github.com/user-attachments/assets/21f698bf-15a2-422e-9a0a-e05875a6377f">
  </details>

**Comment by Zirochkabila** [comment]
- [x] Top and bottom widgets are not displayed when the banner is displayed - **Banner should move the widgets and display above them**



<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/a3858ce0-5c3b-4e75-a90e-0e774b127d5d"></video>
</details>

**Comment by vshcherb** [comment]
- [x] Test default Landscape navigation (Search is broken )
- [x] With alert enabled its broken again. Separate alert in landscape so it's display on top of speedometer not in same line

![Image](https://github.com/user-attachments/assets/5358bb5c-5675-470f-8822-544ed2abfc62)

**Comment by Zirochkabila** [comment]
Add test for landscape placement for search/compass and alarms in grid layout
https://github.com/osmandapp/OsmAnd/pull/24628

**Comment by Zirochkabila** [comment]
> OsmAnd 5.3.0, released: 2026-03-11
> OsmAnd~ 5.3.0#7381m, Released: 2026-03-19

@Chumva 
- [x] [The overlay slider is obscured by the lower control panel](https://github.com/osmandapp/OsmAnd/issues/24634#top)

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/9f60b07c-d4cb-4a10-b2e2-391f57a53b9a"></video>
</details>

**Comment by Zirochkabila** [comment]
# Testing 4

> OsmAnd~ 5.3.0#7452m, Released: 2026-03-27

### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1. When you add a widget from the home screen (for example, while navigating), the widget is added to the “virtual panel.” This means it isn’t actually displayed on the map, but it appears in the list (the list that opens when you long-press on widgets from the home screen). You can only add a widget via the Configure screen

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/2b575ea3-3cb8-4350-9ef1-e73c944962ca"></video>
</details>

### **Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. Landscape mode, Compact widgets – The alert appears above the widgets but behind the buttons. `Suggestion: Display it above the bottom widgets`

<details><summary>Details</summary>
<img width="400" alt="Landscape mode, Compact widgets: alert appears behind the buttons" src="https://github.com/user-attachments/assets/674e9d6d-c189-4cfb-b29d-7ed26799633b">
</details>

* [ ] 2. Landscape mode, Compact widgets, Left panel—two widgets, one of which is Large: The speedometer is displayed above the widget; the alert is displayed above the speedometer and the widget, but behind the buttons. `Suggestion: Display the speedometer to the left of the central widget, and the Alert above the central widget`

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/1507c450-0529-493e-b016-03d56c54b149" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/3aee32c1-ccb6-4fe9-99ee-4675e65670ba" width="300" height="auto"/></th>
  </tr>
</table>
</details>

* [ ] 3. Landscape mode, Wide widgets, Left panel – one widget: The speedometer is displayed above the side and top widgets. `Suggestion: Display the speedometer where the ruler is, and place the alert on the side`

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/a46db235-6aa2-4410-ad6f-202917fe7e02" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/03996e9d-56dd-43e1-829c-dbf043d3515a" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Comment by thuryn** [comment]
Layout is not good in 5.3.3 beta
![Screenshot_20260408-141040_OsmAnd+.png](https://github.com/user-attachments/assets/4a35e775-b2cb-472f-9060-0955c298cdff)

**Comment by Zirochkabila** [comment]
- [ ] The behavior shown in the screenshot can easily be replicated using a user profile (just ask me)

<details><summary>Details</summary>
<img width="900" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/c07bf933-55f6-4345-8c2c-168c960386f7">
</details> 


- [ ] [Testing 4](https://github.com/osmandapp/OsmAnd/issues/20155#issuecomment-4143355163)
