### ISSUE TITLE
Battery widget for ANT+/BLE sensors

### ISSUE THREAD

**Issue by Dunedan** [osmandapp/OsmAnd#20257]
### Describe the idea (required)

I have a BLE sensor whose battery level I'd like to get displayed as a widget.

The battery level of that sensor is already shown in the sensor properties in OsmAnd, but there doesn't seem to be a widget to display that data while also displaying the map.

### Tell us about the expected behaviour (required)

I'd like to have the ability to add a widget for each ANT+/BLE sensor to show its battery level, similar to the widget displaying the battery level of the smartphone.

In addition displaying whether the battery of the sensor gets charged or discharged would be nice, but I'm not sure if that information is available in a generic way.

### Tell us about alternatives you've considered (required)

For now I'm checking the battery level by opening the sensor properties, but that's pretty cumbersome. As far as I'm aware, there is no other way to do that from within OsmAnd.

### Context (optional)

Using OsmAnd+ 4.7.10 on Android right now.

**Comment by vshcherb** [comment]
We can make optional On click to display battery status

**Comment by Dunedan** [comment]
Sorry, but a click on what?

**Comment by dmpr0** [comment]
## ToDo

<table style="width:100%">
  <tr>
    <th>Sensor data</th>
    <th>Battery level</th>
    <th>Show dialog</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e596ecd6-e0f6-4a67-864a-536bcf56a73f"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e6eaeb3d-63b1-43fc-8500-a1bc8162cae1"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/88e57841-a064-4348-9d28-f40c6099d81d"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new option – **Show**
- - [x] **Sensor data**, show main data from sensor
- - [x] **Battery level**, show sensor batter level as main value
- [x] Show icon related to selected mode:
- -  [x] `ic_action_sensor_heart_rate_battery_outlined`
- -  [x] `ic_action_sensor_cadence_battery_outlined`
- -  [x] `ic_action_sensor_bicycle_power_battery_outlined`
- -  [x] `ic_action_sensor_speed_battery_outlined`
- -  [x] `ic_action_sensor_distance_battery_outlined`
- [x] Tap on widget should switch it mode
- [x] Change widget icon and name depend on mode

### Modes
<table style="width:100%">
  <tr>
    <th>Main data</th>
    <th>Battery level</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/354c5ff3-f8ae-4637-bb0a-84529ff28626"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4656f8a4-77ff-455d-a8cb-cccf16f01aed"  width="auto" height="auto"/> </td>
  </tr>
</table>   

### Name & Icons
**Bicycle cadence**
- [x] `Bicycle cadence, battery`
- [x] Icon – `widget_sensor_cadence_battery_day/night`

**Bicycle power**
- [x] `Bicycle power, battery`
- [x] Icon – `widget_sensor_bicycle_power_battery_day/night`

**Temperature**
- [x] `Temperature, battery`
- [x] Icon – `widget_sensor_temperature_battery_day/night`

**Heart rate**
- [x] `Heart rate, battery`
- [x] Icon – `widget_sensor_heart_rate_battery_day/night`

**Bicycle speed**
- [x] `Bicycle speed, battery`
- [x] Icon – `widget_sensor_speed_battery_day/night`

**Bicycle distance**
- [x] `Bicycle distance, battery`
- [x] Icon – `widget_sensort_distance_battery_day/night`

**Additionally:**
- [x] Use new icon for temperature sensors `widget_sensor_temperature_day/night`

**Comment by Dunedan** [comment]
@vshcherb @dmpr0: This sounds like battery status would only be available for sensors of one of the types mentioned above. Is that correct?
For my specific use case I have a sensor which is not one of these types and the only useful information it provides is its battery status and I'd like to be able to see this status in OsmAnd. How would I do that with this feature implemented this way?

**Comment by dmpr0** [comment]
> @vshcherb @dmpr0: This sounds like battery status would only be available for sensors of one of the types mentioned above. Is that correct? For my specific use case I have a sensor which is not one of these types and the only useful information it provides is its battery status and I'd like to be able to see this status in OsmAnd. How would I do that with this feature implemented this way?

It's correct, OsmAnd supports only this type of sensor. If it is not mentioned, you can't connect it.

**Comment by Dunedan** [comment]
> It's correct, OsmAnd supports only this type of sensors. If it is not mentioned, you can't connect it.

Connecting my sensors works fine, however as it's none of the six types mentioned above, there is no widget available to show its battery status (the battery status is shown in the sensors settings though). That's why I created this ticket.

Right now it sounds to me as displaying the battery status of my sensor wouldn't be possible with your planned implementation, as it would only be possible to show the battery status for the six supported sensor types.

Am I missing something here?

**Comment by dmpr0** [comment]
> > It's correct, OsmAnd supports only this type of sensors. If it is not mentioned, you can't connect it.
> 
> Connecting my sensors works fine, however as it's none of the six types mentioned above, there is no widget available to show its battery status (the battery status is shown in the sensors settings though). That's why I created this ticket.
> 
> Right now it sounds to me as displaying the battery status of my sensor wouldn't be possible with your planned implementation, as it would only be possible to show the battery status for the six supported sensor types.
> 
> Am I missing something here?

We will all add a second mode for each external sensor widgets, so you can tap on the widget to switch between modes to view data from the sensor or to view battery level of the sensor. 

<table style="width:100%">
  <tr>
    <th>Main data</th>
    <th>Battery level</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/354c5ff3-f8ae-4637-bb0a-84529ff28626"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4656f8a4-77ff-455d-a8cb-cccf16f01aed"  width="auto" height="auto"/> </td>
  </tr>
</table>

**Comment by Dunedan** [comment]
While I'm still not confident that this will work if the sensor isn't one of the six supported types (as I can't select it as source for the widget in that case), I'll wait until you got that feature implemented to try it out and open a follow-up issue in case it doesn't work.

**Comment by dmpr0** [comment]
> While I'm still not confident that this will work if the sensor isn't one of the six supported types (as I can't select it as source for the widget in that case), I'll wait until you got that feature implemented to try it out and open a follow-up issue in case it doesn't work.

Did you manage to connect sensor of not supported type to OsmAnd?

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.1.0#5373m, Released: 2025-06-12`

**Severity**: 🔶 Major / **Priority**: 🔶 Medium

* [ ] 1\. Cannot hide the icon

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>5.0.6</th>
    <th>Nightly</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/36ce9c9c-4376-4a69-aadd-01d03099a334"  width="300" height="auto"/></td>
    <td><video src="https://github.com/user-attachments/assets/679d0041-059d-430b-9d28-c95e03f83acf"  width="300" height="auto"/></td>
  </tr>
</table>
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9b4ae695-76a9-49fc-9533-128a4ea1c49e"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Apple Default color for icons

- - - - - -

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
        <td><img src="https://github.com/user-attachments/assets/f20f87ba-df37-4960-96a9-d1be921008ec"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/5449befa-bc02-4c8c-85ed-3c8c69e65773"  width="300" height="auto"/> </td>
  </tr>
</table> 

</details>  
  

- [x] Use proper widget icons, start from `widget_` listed on ToDo

- - - - - -

- [x] Show icon option doesn't work for Top/Bottom panel widgets.

**Comment by Zirochkabila** [comment]
# Testing 2

`OsmAnd~ 5.1.0#5516m, Released: 2025-07-03`

### **Severity**: 🟡 Minor \ **Priority**: 🟠 Normal

* [ ] 1\. When hiding/showing an icon, the widget becomes transparent until the screen is refreshed

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/86ed2773-c27f-4e71-8b82-18d70d31aa00"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review 2

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/496ad4f8-8bcf-4b1a-91b4-55c6cae19cff"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Fix icon color

**Comment by dmpr0** [comment]
> # Testing 2
> `OsmAnd~ 5.1.0#5516m, Released: 2025-07-03`
> 
> ### **Severity**: 🟡 Minor \ **Priority**: 🟠 Normal
> * [ ]  1. When hiding/showing an icon, the widget becomes transparent until the screen is refreshed
> 
> Details

This is not related to this task. The described behavior reproduces on each widget.

**Comment by sonora** [comment]
New finding, relating also to https://github.com/osmandapp/Osmand/issues/22609:

The recent 'battery status display' development has introduced an interim bug where the formerly empty tap action on a **disconnected** widget tries to show the battery status. Which is of course bogus for a sensor not currently connected. We should instead **map the tap action for an _unconnected_ sensor widget to the "connect action"**.

<img width="145" height="218" alt="Image" src="https://github.com/user-attachments/assets/c691db74-b567-42be-bfb9-285c0564f0cf" />

**Comment by vshcherb** [comment]
## To do 
- [x] Once disconnected try to reconnect and display toast if it's successful or not
- [x] Tapping on the **Widget** should switch modes, maintaining current functionality.
- [x] If the **Sensor** is disconnected, tapping on the **Widget** should also initiate the connection process.

**Comment by dmpr0** [comment]
> To do
> 
> * [ ]  Once disconnected try to reconnect and display toast if it's successful or not

How it will solve original issue? I think it would be better to add **Connect** to the widget context menu.

**Comment by sonora** [comment]
@dmpr0 But regardless of whether "connect" becomes part of the context or not: If the user taps a _disconnected_ widget, isn't a connection attempt the only useful action to try, and should hence be triggered in that case automatically?

**Comment by sonora** [comment]
I have user feedback that the reconnect works well now!

However, the user says they do not even have to tap the widget, the sensor seems automatically get connected as soon as switched on.

If this is intended behavior, probably ok.  :wink:  Unless it means permanent extra battery usage, and we should limit connection attempts only to widget tap events.

**Comment by Zirochkabila** [comment]
# Testing 3

`OsmAnd~ 5.2.0#5688m, Released: 2025-07-25`

### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] If the Sensor is disconnected, tapping on the Widget should also initiate the connection process - **The connection process is not initiated**

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/7a10394f-de32-4e70-8180-b8dfbe34b061"></video>
</details>

---

### Completed tasks in this build:

* Once disconnected try to reconnect and display toast if it's successful or not - **Done**

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th><img src="https://github.com/user-attachments/assets/e6363ced-9111-4db2-b6cf-663d68f8148b"  width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/53ee2238-7e6a-4822-ac7d-ec66b87f85d4"  width="300" height="auto"/></th>
  </tr>
</table>
</details>

* Tapping on the Widget should switch modes, maintaining current functionality - **Done**

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/6d2f09b7-9315-46a3-bbe9-be839b362aaf"></video>
</details>

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4746827d-5e4d-4938-acdc-272022c88a55"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/7cda84a7-49e0-44ef-ac1b-eb1df9725ddf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/5c664df9-0117-4014-bca0-d24803847d51"  width="300" height="auto"/> </td>
  </tr>
</table>  


- [ ] `-1%` (real `87%`) is shown for Garmin Fenix 7

**Comment by Corwin-Kh** [comment]
Garmin watches does not send battery level data
