### ISSUE TITLE
Coordinates in RTL

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20595]
## Description

> Previous task https://github.com/osmandapp/OsmAnd/issues/15538
> iOS task https://github.com/osmandapp/OsmAnd-Issues/issues/2633

## ToDo
Coordinates format should not be changed when Right-to-left language is selected.

<details>
    <summary>Current</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/9f69d5ab-bc95-4729-8c0c-3480b50a2802"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/4203c504-ebf6-4128-9f73-a7c20ebb9f23"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/1bf77e3d-cf71-4a12-a267-049b7bcdad90"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Prevent coordinate flipping. Ensure latitude and longitude values are displayed in the correct order: latitude first, longitude second, both in RTL and LTR.
- [x] Should apply for coordinates in:
- - [x] **Coordinates: Map center** and **Coordinates: Current location** widget
- - [x] Coordinates in context menu
- - [x] All coordinate formats

**Comment by vshcherb** [comment]
- [ ] Partial revert https://github.com/osmandapp/OsmAnd/commit/eea0e7e5f239c8c167e0aa01d2a3459ad660a7bf

**Comment by nazar-kutz** [comment]
# A Comprehensive View of the Problem
I decided to document my work on this task to preserve information that will be helpful in justifying decisions and understanding the actions taken for future fixes.

This task is fully focused on correcting the incorrect display of coordinates when using RTL (right-to-left) language localization.

To understand why this issue arises and what we aimed to fix, it’s essential to understand how it should ideally work.

The standard approach for displaying complex sets of numbers (such as phone numbers, credit card numbers, coordinates, etc.) is that these text elements should appear the same and remain consistent across both RTL and LTR (left-to-right) orientations. In other words, all numeric formats in the app should display in LTR for every localization.

However, this does not occur automatically. The Android system preserves the original order within individual blocks of numbers (which is correct), but in RTL, the blocks themselves are rearranged. For example, what appears as “1234 5678” in LTR becomes “5678 1234” in RTL. Given this, the output in RTL should still be “1234 5678” across all localizations. This applies to all number sets treated as unified in LTR.

Since the system cannot distinguish which blocks should display in LTR and which in RTL, we need to track and correct such issues individually.

A useful article I found while researching the problem: https://dev.to/pffigueiredo/stop-fixing-numbers-rtl-in-a-web-platform-6-6-29ne

**Comment by nazar-kutz** [comment]
## Specific Case Described in This Task
In this task, the user noticed incorrect formatting of coordinates on the UI — the North and East coordinates were swapped, and the comma was incorrectly repositioned, no longer separating the North and East coordinates but instead appearing before the "N" symbol. This issue also affected coordinates in other formats, such as Swiss CH1903, where number blocks were reordered on certain screens. For example, instead of correctly displaying as "2 306 626.29, 840 452.3," it appeared in RTL as "452.3 840 ,626.58 306 2."

As previously mentioned, these issues arise because the Android system doesn’t accurately recognize whether it’s dealing with standalone numbers or complex numerical data that should be treated as a single unit.

The goal of this task, therefore, was to correct the misrepresentation of coordinates for RTL languages wherever these data are displayed in the app. The task was specifically focused on addressing this problem, as it was the main user complaint in this issue.

**Comment by nazar-kutz** [comment]
## Solution Implemented So Far
Several approaches were considered to address this issue, but we settled on the most general and universal one — using specific Unicode characters to isolate portions of text that need to be displayed in a designated direction (LTR or RTL) regardless of the direction of the surrounding text. These characters are "\u200e" for LTR and "\u200f" for RTL.

The first version of the fix was implemented in this pull request: https://github.com/osmandapp/OsmAnd/pull/20968.

However, this fix led to other issues, as the markers required only for UI display ended up in raw data, which could be copied and used for searching or other purposes, where the extra character could cause problems.

To address this, additional fixes were introduced to remove these markers from coordinates when they are unnecessary.
* For search: https://github.com/osmandapp/OsmAnd/commit/a643f1930ecd27ca818855e61114be7e0274534c
* For coordinate copying: https://github.com/osmandapp/OsmAnd/pull/21261

We also proactively addressed the potential issue of over-forcing directionality for other text segments. Since directional formatting characters apply globally from the point they’re added to the end of the text, we used the "\u202C" character to cancel forced directionality at the end of the targeted text, preventing unintended direction forcing for any subsequent text.

These changes were implemented here: https://github.com/osmandapp/OsmAnd/pull/21263.

**Comment by nazar-kutz** [comment]
# Issues Requiring Solutions
With a clearer understanding of the problem, we now know that this issue affects not only coordinates but also other types of complex numerical data, such as phone numbers, credit card numbers, and similar items. Since only the coordinates have been corrected so far, we also need to apply this fix to other areas. For instance, this issue remains relevant for phone numbers.

Moreover, this problem affects not only display but also data input. Therefore, we need to address areas of the app where users enter phone numbers and other similar data, wherever applicable.

The technical implementation of this approach also warrants careful consideration. While using special characters is a good idea, they should ideally be applied closer to the UI rather than embedding them directly in the raw data. Raw data should not contain any extraneous characters.

Whatever the final solution, it should meet the following requirements:

All instances of incorrect text order formatting should be fixed.
Any additional markers should remain limited to the UI and should not be saved within the "raw" data.
The solution should, if possible, be automated (to avoid the need to change many places in the code if adjustments are needed). At the very least, there should be a guideline or specification ensuring correct formatting in relevant UI fields.
In any case, for manual adjustments, we will need to carefully review and identify all possible areas where similar issues may occur. An automated approach could ensure greater stability and ease of maintenance, but we must remain vigilant to prevent UI-formatted data from being transferred as raw data, where it could cause issues.

**Comment by nazar-kutz** [comment]
We propose moving further fixes into a separate task.
