### ISSUE TITLE
Key “D”, “N”, “S” on external Keyboards - no effect any more

### ISSUE THREAD

**Issue by Officer-on-duty** [osmandapp/OsmAnd#20636]
### Description

The key “D”, “N”, “S” has no effect any more on external keyboards. Other key like "C", "up", "down" and so on work still fine.

### Steps to reproduce

Plug a external keyboard. Type the buttons and see the result.

### Actual result

nothing

### Expected result

D | Keyboard | Map orientation
N | Keyboard | Open Navigation view.
S | Keyboard | Open Search view.

### Your Environment (required)

Device : a21s
Brand : samsung
Version : 12
App Version : OsmAnd
Apk Version : 4.8.4 4804

**Comment by vshcherb** [comment]
https://osmand.net/docs/user/map/interact-with-map/#preconfigured-input-device-type

**Comment by vshcherb** [comment]
According to documentation should work for std Keyboard input type

**Comment by Officer-on-duty** [comment]
Brilliant analysis. This is the exact reason for my bug-report. It does not work but it should.

**Comment by vshcherb** [comment]
I don't think they will be present in UI as quick actions, so they need to be added internally?

**Comment by dmpr0** [comment]
## ToDo 
We need to add missed actions:

**Settings**
- [ ] Show / hide – Navigation view
- [ ] Show / hide – Search
- [ ] Show / hide – Side menu
- [ ] Navigate – Previous screen

**Comment by dmpr0** [comment]
# Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/811c1152-925a-4675-b8c9-520db10cdc9e"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Navigate – Previous screen (Activity back pressed) is not use ESC, but some other button?
