### ISSUE TITLE
Restore the possibility to select the app language from the settings menu

### ISSUE THREAD

**Issue by asereze** [osmandapp/OsmAnd#20683]
### Describe the idea

Hi, in the last few versions of the app I've seen that the possibility to change OsmAnd's language from the app settings has been removed and replaced with the possibility to chose it from the system's settings. That creates a problem for languages that are not yet fully supported by Android on all devices, like Sardinian.
I've been able to keep using it in my language thanks to the fact that LineageOS (in its last versions) supports Sardinian, but in most other distributions that's still impossible.
Could you please restore it? I've seen apps having both ways to select the language, maybe that could be possible for OsmAnd as well.

### Expected behaviour

Ability to select Sardinian (and any other language in the same situation) as app language in devices where Android doesn't support it yet.

### Alternatives you've considered

I tried to wait for a while before asking here, hoping that the latest Android updates would have included Sardinian support for all devices, but unfortunately that has not yet been the case. At least, not for the devices I've seen, except for those using LineageOS.

**Comment by yuriiurshuliak** [comment]
The bug couldn't be reproduced. You can still select the Sardinian language by going to: Menu → Settings → OsmAnd settings → Display language.

OsmAnd~ 4.9.0#3071m, released: 2024-08-25
Android Version : 12

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a37b4fb4-fe47-4264-8da2-cad786752836"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/c181d143-c433-444a-b947-814da0e87725"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
Sardinian is visible as Sardu

<table style="width:100%">
  <tr>
    <th>OsmAnd Menu</th>
    <th>Android Language selection</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d6f55359-88af-408e-8d2d-f8b025475a21"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/9d0d6574-b75a-47fc-a2b3-c8b110c3917c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by asereze** [comment]
@dmpr0 Oh, good! hope they will add it everywhere with Android 15 then! Like you wrote, on most Android 14 distributions is not available. Just to be sure, I've tried again today with a Samsung Galaxy A14 after installing the latest update.
![IMG_20240829_175730_548](https://github.com/user-attachments/assets/814b6bae-d010-4613-a2e6-ceb9ea87611a)

**Comment by vshcherb** [comment]
Hopefully Android 15 will roll out quickly

**Comment by dmpr0** [comment]
## ToDo

- [x] Show **Display language** for all Android versions
- [x] By default set to **System default**

- - - - - -
 
**On Android 13+ (API 33+):**
- [x]  Use AndroidX API to set language, when selected from OsmAnd UI.
```
val appLocale = LocaleListCompat.forLanguageTags("fr")
AppCompatDelegate.setApplicationLocales(appLocale)
```

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7586m, released: 2026-04-15
> Android 15

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 1. The default value displays an incorrect language abbreviation

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/c46f27ee-8551-4397-b2c6-51b48d6fb645"></video>
</details>

**Severity**: 🔵 Trivial / **Priority**: 🔵 Low

* [ ] 1. An additional screen refresh occurs when changing the language

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/9e0f9c65-0e29-4857-bbd9-2c92b0234b58"></video>
</details>

**Comment by nazar-kutz** [comment]
## Task Summary: In-App Language Selection for Android 13+

**What was done (Overview):**
We restored the in-app language selection (`Global Settings -> App language`) for Android 13 (API 33+). Previously, this was hidden because Android 13 introduced system-level per-app language settings. Now, users can change the language via both the App UI and System Settings, and we keep them synchronized.

**Under the Hood & Technical Changes:**
* **Synchronization:** Selecting a language in-app now updates the internal setting AND the system setting simultaneously via `AppCompatDelegate.setApplicationLocales`.
* **Startup Priority (Rare Language Protection):** On app startup, the System locale takes priority over the internal setting. **Exception:** If the system returns "System Default" (empty), we fallback to the internal setting. This prevents certain vendor OSs from overwriting/dropping rare languages (like Sardinian) that the OS doesn't officially support but OsmAnd does.
* **Locale Parsing Refactoring:** We dropped the legacy custom locale parser. We now use standard BCP-47 tags (`forLanguageTag`) managed via a new `SupportedLocale` enum. This enum maps modern tags to OsmAnd's legacy tags to maintain backward compatibility.
* **Restart Dialog Fix:** Fixed a bug where the "Restart required" dialog would disappear on screen rotation or Activity recreation. It now persists reliably until explicitly dismissed by the user.

**To Test (QA Instructions):**
* **General Sync:** Change the language via *both* the in-app settings and the OS App Info settings. Verify they apply correctly.
* **Complex Languages:** Test Serbian (Latin vs. Cyrillic) and Hebrew to ensure our new BCP-47 parser handles them correctly.
* **Rare/Unsupported OS Languages:** Select a language not supported by the OS (e.g., Sardinian) via the in-app settings. Restart the app and verify the language was successfully applied and not wiped by the system.
* **Restart Dialog:** Change the language in-app. Verify the "Restart required" dialog appears, survives screen rotation, and only disappears when the user clicks "Later" or "Restart".

**Known Limitations / Out of Scope (What is left as is):**
1. **Summary Translation Mismatch:** Because the OS sometimes returns a full tag (lang + region) and we use strict language tags, the selected language name in the settings summary might not be translated (due to non-exact matching). Considered a minor issue for now.
2. **No Hot-Reloading:** Applying a new language still requires a full app restart. Dynamic UI/resource updating without a restart is too complex (due to cached data) and was not addressed in this task.
3. **Missing Dialog from System:** Changing the language via *System Settings* and resuming the app does *not* trigger the "Restart required" dialog. The user will need to restart the app manually for all resources to update completely.
