### ISSUE TITLE
Add new quick action Show / hide	– OSM Edits

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20711]
We have missed one quick action that already presented on iOS version

## ToDo
Add new quick action:
- [x] Verb  – `Show / hide`
- [x] Action – `OSM Edits`
- [x] Icon – `ic_action_openstreetmap_logo`
- [x] Group – **My Places**

**Comment by HKMANOJ** [comment]
Hi @dmpr0 can i work on this issue?

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/20979
