### ISSUE TITLE
Quick actions for Trip recording

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#20800]
## ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/05753be4-4f1c-4e85-b415-372c8b81ede1"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] **Start / Pause – Trip recording**
- - [x] Icon start – `ic_action_trip_rec_start`
- - [x] Icons pause –  `ic_action_trip_rec_pause`
- [x] **Start – New trip segment**
- - [x] Icon – `ic_action_trip_rec_new_segment`
- [x] **Save – Recorded Trip & Continue**
- - [x] Icon – `ic_action_trip_rec_save`
- [x] **Finish – Trip recording**
- - [x] Icon – `ic_action_trip_rec_finish`
- [x] Add to **My Places** group

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/quick-action#my-places
https://osmand.net/docs/user/plugins/trip-recording#new-track-recording
https://osmand.net/docs/user/plugins/trip-recording#current-track-recording
