### ISSUE TITLE
Navigation: Reverse track always provides directions to starting point, rather than nearest point

### ISSUE THREAD

**Issue by david-gpu** [osmandapp/OsmAnd#20812]
### Description

The navigation directions provided when the user selects a reversed track always direct the user towards the beginning of the track, even when the user is already half way through and *Point of the track to navigate* is set to *Nearest point*.

### Steps to reproduce

Select a track, preferably one you are already following and roughly half-way through. Click the navigation button. Click on the *Follow track* field. Enable *Reverse track direction*. In the *Point of track to navigate* select *Nearest point*.

### Actual result

The navigation instructions direct you all the way towards the beginning (actually, the end) of the track, rather than realizing that you are already following the track and half way through.

### Expected result

I expected the algorithm to realize that one is already half way through the track and provide instructions on how to continue from there, rather than asking you to reverse course towards the end of the track.

The expected result above is the behavior that is actually observed when *Reverse track direction* is disabled. I don't understand why enabling this option changes the behavior of the navigation algorithm.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.8.6
Android/iOS version: Android
Device model: Samsung A71
Crash-Logs: ?
```

**Comment by RZR-UA** [comment]
The bug is reproduced.

In "usual" (forward) navigation by track, everything is OK.

In the reverse mode, start/finish points are swapped, but the navigation still goes to the "old finish" first and then to the "new finish" using the additional route.

When the track is reversed, the navigation should consider the reversed way (not only start/finish points).

We are working on it to fix the problem.

| forward | reverse |
|--------|--------|
| ![1](https://github.com/user-attachments/assets/d5ee1c9d-3239-4495-a6c0-79c4ddad57c6) | ![2](https://github.com/user-attachments/assets/608b856f-3069-479b-9660-27751a761ef4) |

**Comment by RZR-UA** [comment]
To Do

- [x] Option 1. Ignore `List<RouteSegmentResult> gpxRouteResult = routeParams.gpxRoute.route`.
- [x] Option 2. Calculate route using `Collections.reverse(routePoints)`. Use the result as GPX.
- [ ] Use Option 1 for Pedestrian only and Option 2 for Car/Bicycle profiles (UI choice also?)

**Comment by david-gpu** [comment]
> * Use Option 1 for Bicycle/Pedestrian

Please don't do that. In most jurisdictions bicycles are legally considered vehicles and have to follow the same rules of the road, including e.g. one-direction streets, turn restrictions, etc. Ignoring those laws while routing would put cyclists in danger.

Honestly, I wouldn't implement option 2 at all. The marginal performance optimization for pedestrians cannot possibly justify the additional code and testing complexity.

**Comment by david-gpu** [comment]
Sorry! Fat fingers! Did not mean to close it. And I am now not allowed to reopen? That seems backwards.

**Comment by RZR-UA** [comment]
@david-gpu agree with you about bicycles. Have changed To Do details.

**Comment by RZR-UA** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/0bb51cb9-6660-4ad2-93f8-b4f6a65e7dd8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/63485fec-fc96-48b1-8c15-9d00d4fe9410"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/50f46d70-c948-4e78-b4ae-4b6924bc482e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/356788c7-fdfc-4b37-be35-76912ca5798b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by RZR-UA** [comment]
```
	public enum ReverseStrategy {
		USE_ORIGINAL_GPX,
		RECALCULATE_ALL_ROUTE_POINTS,
		RECALCULATE_FROM_CLOSEST_ROUTE_POINT // faster but less exact
	}
	public static final ReverseStrategy DEFAULT_REVERSE_STRATEGY = ReverseStrategy.RECALCULATE_ALL_ROUTE_POINTS;
```

```
	public ReverseStrategy reverseStrategy = DEFAULT_REVERSE_STRATEGY;
```

The current `reverseStrategy` could be managed from the UI (another task for the Android Team).

**Comment by RZR-UA** [comment]
@Zirochkabila

To Test

- [x] Android: create 2 tracks around/crossing your location, using Plan Route (car)
- [x] Create 2 additional similar tracks using another profile (bicycle)
- [x] Test Navigation with Follow track in direct and reverse mode
- [x] Test these 4 tracks in OsmAnd iOS (code transfer required?)

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.1.0#5407m, Released: 2025-06-18`
`5.1.1.5101`

[Car profile - Wed 18 Jun 2025\_2.gpx.zip](https://github.com/user-attachments/files/20797989/Wed.18.Jun.2025_2.gpx.zip)
[Bike profile - Wed 18 Jun 2025\_3.gpx.zip](https://github.com/user-attachments/files/20797998/Wed.18.Jun.2025_3.gpx.zip)

---

### **Severity**: 🟠 Major \ **Priority**: 🟠 Normal

* [ ] 1\. Android: create 2 tracks around/crossing your location using the Route Plan (**car**) — Often the route is not laid (turned) from the current position, but goes to the nearest turn — it is directed every second time

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/e724966b-9d18-4a9a-9eea-b6bed0021b34"></video>
</details>

---

### ✅ Fixed

2. Create 2 additional similar tracks using another profile (bicycle) — This does not happen with the bike profile — **Fixed**
3. Test Navigation with Follow track in direct and reverse mode — the return path is no longer routed to the starting point — **Fixed**
4. Test these 4 tracks in OsmAnd iOS (code transfer required?) — works without errors for tracks with bike and car profiles, no code transfer required — **Fixed**

**Comment by dmpr0** [comment]
## UI Review

* Reverse track direction always produces messed-up results for OsmAnd tracks. Perhaps it should always reverse based on track line geometry.

- - - - - -


<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/bac57905-638b-4670-845b-6e8fb616f123"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d6b04efa-ca43-475d-b0f0-4e47cdfd18ee"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  




* Point of the track to navigate act the same, track – [Tue 08 Jul 2025_3.gpx.zip](https://github.com/user-attachments/files/21123206/Tue.08.Jul.2025_3.gpx.zip)

- - - - - -

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/57057521-dc4c-46ed-8880-59b11aefc7c1"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  





* Calculated route is empty, file – [Tue 08 Jul 2025_4.gpx.zip](https://github.com/user-attachments/files/21124522/Tue.08.Jul.2025_4.gpx.zip)

**Comment by dmpr0** [comment]
## ToDo
For Android team.

<table style="width:100%">
  <tr>
    <th colspan=2>Reverse track direction</th>
    <th>Reverse mode</th>
  </tr>
  <tr>
    <th>Off</th>
    <th>On</th>
    <th>Bottom sheet</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2d2f2d9d-5eb1-4b87-8968-77cd3174ae4a"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/587ba696-62e7-4d33-8a9a-7080e842ef30"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/eb9ef500-56fe-4dac-be74-7c3efecbd687"  width="300" height="auto"/> </td>
  </tr>
</table>  

We need to add new parameter **Reverse mode** that will allow to select how Reverse track should behave.

- [x] Add new parameter **Reverse mode**
- - [x] Visible only if **Reverse track direction** is On
- - [x] Icon – `ic_action_reverse_mode`
- - [x] By default set to **Calculate route**
- - [x] Tap on item should open bottom sheet

### Reverse mode bottom sheet.

- [x] Title – **Reverse mode**
- [x] **Original track**
- - [x] Description —  `Follow the exact track back to the start. Warning: This can be dangerous as it ignores one-way traffic on roads`
- [x] **Calculate route**
- - [x] Description — `Calculate a new, optimized route to the start. `

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.2.0#5771m, Released: 2025-08-07`

### **Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1\. The route starts flashing when “Original track” is selected

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/fe33f897-76ee-4820-a9ea-d4715afe49e1"></video>
</details> 

* [ ] 2\. Reverse mode settings are not saved in the backup file
[Driving (12).osf.zip](https://github.com/user-attachments/files/21662555/Driving.12.osf.zip)

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Custom settings</th>
    <th>Result after imported file</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/fe06d8f4-c3db-4e09-89d3-66920cd16485"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/663c6c74-f510-4d47-a28e-5ac9f7a2c6bf"  width="300" height="auto"/> </th>
  </tr>
</table> 
</details>
