### ISSUE TITLE
Climbing routes: Support for `climbing=area` and `climbing=crag`

### ISSUE THREAD

**Issue by alensiljak** [osmandapp/OsmAnd#21248]
### Describe the idea

From what I've seen, only `sport=climbing` seems supported when looking for POIs. Considering there is a growing number of climbing areas and crags marked with a relation of type `climbing`, as per [Climbing page](https://wiki.openstreetmap.org/wiki/Climbing) in the OSM wiki, it would be useful to (be able to) show these on a map.
Currently, these are shown as POIs since they are also tagged with `sport=climbing`, but a broader support on a pedestrian map would be great. 

### Expected behaviour

Similar to https://openclimbing.org/, crags and areas could be marked with specific icons in a map profile.
`climbing=crag`
`climbing=area`

The tags are ordered hierachically:
Crags (normally) contain routes and route_bottom. Areas contain (multiple) crags. Areas can be nested (to represent sub-areas of a bigger area).

### Alternatives you've considered

n/a

**Comment by yuriiurshuliak** [comment]
https://taginfo.openstreetmap.org/tags/climbing=area#overview
https://taginfo.openstreetmap.org/tags/climbing=crag#overview

**Comment by vshcherb** [comment]
https://openclimbing.org/#18.82/46.3215/7.9813
https://overpass-turbo.eu/?key=climbing&value=crag&template=key-value

![Screenshot 2024-11-07 at 17 40 06](https://github.com/user-attachments/assets/d3eb7abc-db50-4582-ae2f-54e5f956a173)

**Comment by dmpr0** [comment]
## ToDo

**Core**
- [ ] Add support for routes

**Android** 
- [ ] Use icon `ic_action_hill_climbing`

**Comment by RZR-UA** [comment]
- [ ] fix icon

![Image](https://github.com/user-attachments/assets/b07231b3-26b1-443d-bb27-a44ebda263f0)

**Comment by DmitryAlexei** [comment]
- [ ] add osm_climbing and other strings to translations

**Comment by alensiljak** [comment]
Thanks, guys! You are likely the first to support the climbing taxonomy. 
This should make OsmAnd attractive to the climbing community and also make access to climbing areas easier.

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#4361m, Released: 2025-02-12`
`4.9.5.4972`

1. The icon is not displayed in iOS

<details><summary>iOS</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/adfa0c2b-08a5-41da-9095-f3c1628bfbd3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/57584801-ae1d-46b1-9a5b-d9befe7c039d"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>


____

2. None of the routes are displayed on the map `“climbing”=“area”`, `“climbing”="”`

[area](https://www.openstreetmap.org/way/133143539#map=19/47.829274/13.628159) 
[crag](https://www.openstreetmap.org/way/128264610#map=19/48.335970/14.528888)

`47.829233/13.628183
``48.336002/14.528883`

**Comment by alensiljak** [comment]
>     2. None of the routes are displayed on the map `“climbing”=“area”`, `“climbing”="”`
> 
> [area](https://www.openstreetmap.org/way/133143539#map=19/47.829274/13.628159) [crag](https://www.openstreetmap.org/way/128264610#map=19/48.335970/14.528888)
> 
> `` 47.829233/13.628183 ``48.336002/14.528883 ``

I'm a bit confused by this second part. The crag listed here is a cliff with the tag `climbing=crag`. However, crags should be relations, like the area listed just before, that I created recently.
Tagging cliffs is the way it was done before. Currently, the convention is to use relationships for crags and areas while only the routes are actual elements drawn on the map. And then added into a relationship (usually crag but I also add multi-pitch routes to areas).

**Comment by vshcherb** [comment]
To fix: 
1. The icon is not displayed in iOS
2. Icons in Android differ from those in iOS
3. FIx different address Android / ios - should be consistent

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/map/routes#climbing-routes
https://osmand.net/docs/user/map/map-context-menu#climbing-area-and-crag-details

**Comment by ihoryakovenko** [comment]
Cannot reproduce the problem with 3. Icons in Android differ from those in iOS
IOS
![Image](https://github.com/user-attachments/assets/4fdb4b6a-d5eb-4a76-b842-15ede2840087)
Android
![Image](https://github.com/user-attachments/assets/49d3c826-5fce-46a7-85e6-279fc907b1e9)

**Comment by Zirochkabila** [comment]
> To fix from [@Zirochkabila](https://github.com/Zirochkabila) :
> 
> * [ ]  The icon is not displayed in iOS 
> * [x]   Icons in Android differ from those in iOS
> * [ ]   FIx different address Android / ios - should be consistent  (if it's complicated create a separate task)

# Testing 1
`OsmAnd~ 5.1.0#4965m, Released: 2025-04-09`
`5.0.0.5007`

Taking into account @vshcherb  comment, only **the 2nd** point can be considered fulfilled (now the behavior is not reproduced)
**The 1st** and **3rd** points still need to be fixed

**Comment by DmitryAlexei** [comment]
- [ ] The icon is configure map remains in  iOS

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/700aa087-e972-4b78-9173-5d942363d0a9"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by RZR-UA** [comment]
The iOS icon for Climbing is fixed now. Issue closed.

**Comment by Zirochkabila** [comment]
# **Testing 3**
`5.0.2.5015`
`OsmAnd~ 5.1.0#5089m, Released: 2025-04-23`
`5.0.2.5014`
Address was fixed on Android and icon added on iOS.


## 🚨 Critical

- [ ] **Climbing area no longer displayed starting from version 5015 — possible regression**
- **Location:** `47.69789 / 14.06357`
- **Context:** In version 5015, the climbing area is missing, while it is properly displayed in version 5014 and on Android.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>5014</th>
    <th>5015</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/44cb13a0-99bb-459d-83b6-e81fd501cffd"  width="300" height="auto"/></td>
    <td><video src="https://github.com/user-attachments/assets/c013533b-5242-4877-bc88-5812a24a61a0"  width="300" height="auto"/></td>
    <td><video src="https://github.com/user-attachments/assets/9c567eb3-14f9-462d-ae19-a086348a1b70"  width="300" height="auto"/></td>
  </tr>
</table>
</details>

**Comment by tigrim** [comment]
TestFlight 5015 - Not reproduced

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/1254c977-a0f6-4547-8f75-07b45db9dd6e" />

**Comment by RZR-UA** [comment]
@Zirochkabila, please try to reproduce again

**Comment by Zirochkabila** [comment]
`5.0.2.5018`

Reproduced on macOS, not produced on iOS


<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/d31151a4-123c-484d-ace0-78c83a4e6249"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/25841d3d-ba9b-46e5-848a-8d2e05328ac3"  width="300" height="auto"/> </th>
  </tr>
</table>
