### ISSUE TITLE
OsmAnd does not offer to activate maps

### ISSUE THREAD

**Issue by sonora** [osmandapp/OsmAnd#21302]
When you zoom into a region where you have a standard map, but it is deactivated on your device, OsmAnd offers to download the map, but not to simply activate it. (Although OsmAnd seems to be aware of deactivated maps present, shown with orange instead of green shading on the map in overview zoom levels).

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce it:

- Open the app.
- Ensure that a map for a specific region is already downloaded but deactivated.
- Zoom into the region covered by the deactivated map.

Observed Behavior: OsmAnd suggests downloading the map instead of offering an option to activate it.

OsmAnd~ 5.0.0#3746m, released: 2024-11-18

https://github.com/user-attachments/assets/38c2636f-6ad3-49f7-b402-0ff06366fb5e

**Comment by dmpr0** [comment]
## ToDo

### Dialog

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/7bc77cbd-95f4-4f12-a2d4-7fed0b6c00ec"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [ ] Show over the regions with deacticated maps
- [ ] Use icon `ic_action_box_open_arrow_colored`

### Maps & Resources
<table style="width:100%">
  <tr>
    <th>Deactivate</th>
    <th>Activate</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1677140e-fe0e-4aa2-ac15-1011dcf05672"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d087a63b-d8cb-4638-b0aa-852d61cb62d7"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [ ] Use `ic_action_box_closed_arrow` for **Deactivate** action
- [ ] Use `ic_action_box_open_arrow` for **Activate** action

**Comment by Zirochkabila** [comment]
# **Testing 1**

`OsmAnd~ 5.1.0#5275m, Released: 2025-05-27`

## 💡 Idea

* It may also be worth changing the icon in the context menu when clicking on a deactivated map.

<details><summary>Details</summary>
<img width="400" alt="Deactivated map context menu icon" src="https://github.com/user-attachments/assets/66ed89cb-410a-44a1-bfc9-c6c4d691aef8"/>
</details>
