### ISSUE TITLE
Visibility of roundabout exits in dark mode

### ISSUE THREAD

**Issue by Davi427** [osmandapp/OsmAnd#21339]
### Description

When the map is in light mode, the skipped roundabout exits in the next turn widget are visible because the outline is black on a light background. 

When the map is in dark mode, the skipped roundabout exits in the next turn widget are barely visible because the outline is black on a dark background. 

### Steps to reproduce

Have next turn widget, 
set map to dark mode,  
approach a roundabout.

### Actual result

Exits are barely visible. 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/9afe614a-1af8-4e61-a37b-665ac905033e"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result

Exits are visible.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/533e5e73-bc0a-4e7a-a39f-b0f51e897597"  width="300" height="auto"/> </th>
  </tr>
</table>  

Like this but dark, obviously. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: OsmAnd+ 4.9.5, Released: 2024-11-12
Android/iOS version: 14
Device model: FP5
Crash-Logs: ?
```

**Comment by Zirochkabila** [comment]
OsmAnd~ 5.0.0#3720m, Released: 2024-11-14
agree

**Comment by dmpr0** [comment]
> iOS Task – https://github.com/osmandapp/OsmAnd-iOS/issues/3490

## ToDo
We need to start using colors from assets for navigation arrows,  currently the defined in [OAColors.h](https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/Constants/OAColors.h#L17)

- [ ] Stroke, add new color `navArrowStrokeColor` for stroke outisde arrow and circle
- [ ] Exit number, use `widgetValueColor`


**Circle**

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ed56f005-9b82-4bf3-aa7a-a84037b01713"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e5d93699-315a-428b-b259-37946bb05e50"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Fill circle shape, use color `navArrowCircleColor`

**Comment by nazar-kutz** [comment]
@dmpr0 Thank You for the design!

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.0.0#3999m, Released: 2024-12-26`

`48.15388° N, 14.01091° E` to `48.15412° N, 14.00528° E`

1. If a circular motion is displayed in the second turn widget, it does not have a circular motion fill
2. If the circular motion is displayed in the first turn widget, the color of the circular motion fill is different (only for day mode, only for the top and bottom widgets)


<table style="width:100%">
  <tr>
    <th>1</th>
    <th>2</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/6859a28f-e8c8-443e-a7a1-8352fd16f917"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/cf4b4ab2-8f85-42da-a40b-f8daacd0d0ea"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

- [ ] All turn arrows should looks the same on all widgets.

**Comment by Zirochkabila** [comment]
# Testing 2

`OsmAnd~ 5.0.0#4062m, Released: 2025-01-06` - Fixed

**Comment by Zirochkabila** [comment]
# Testing 3

`OsmAnd~ 5.0.0#4083m, Released: 2025-01-08` - Fixed
