### ISSUE TITLE
Starbucks, Okko not visible: World - National - Local brands

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd#21547]
Web search by brandh
- [x] Starbucks doesn't show up in Warsaw
- [ ] Brand Okko - https://overpass-turbo.eu/s/1VoP (not all fuel stations okko are visible), in some regions they are missing

----------
- [ ] Automatic Updating top brands
- [ ] Support for local / national brands

**Comment by ivanPyrohivskyi** [comment]
List of world brands according to interests of OsmAnd's users.
[brands.json](https://github.com/user-attachments/files/18298695/brands.json)

**Comment by ivanPyrohivskyi** [comment]
Test map https://test.osmand.net/uploads/test/Poland_masovian_europe.obf
Binary inspector (POI section), default count of brands is 100:
```
top_index_brand  encoded 102
...
top_index_brand:
...
Starbucks
```

**Comment by DmitryAlexei** [comment]
### ToDo

- [ ] 26th each month generate only POI section of all maps (top-50 brands)
- [ ] use POI section maps to create brand table
- [ ] use brand table in regular map generation

**Comment by sonora** [comment]
https://github.com/osmandapp/Osmand/issues/22855 could be related?

**Comment by ivanPyrohivskyi** [comment]
https://creator.osmand.net:8080/view/all/job/Maps_GenerateWorldBrands/

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-tools/commit/927544e255289b56bbbfac7bb72c4a2fffee8f85

Utility provided -  scheduled 1 a month https://builder.osmand.net:8080/view/Planet/job/Planet_WorldBrands/

@ivanPyrohivskyi  need to be tested especially lowercase and other languages scenario recently fixed (tested myself 1 time ) - 30 MB ! https://builder.osmand.net/basemap/brands/brands.html

**Comment by vshcherb** [comment]
@ivanPyrohivskyi https://github.com/osmandapp/OsmAnd-tools/pull/1228

**Comment by Zirochkabila** [comment]
# Testing 1
`OsmAnd~ 5.2.0#5939m, Released: 2025-09-02`
`5.2.1 (5227)`
`Web - prod`

The display of brands for **OKKO** and **Starbucks** has been checked - the brands are displayed both in search results and on the map.


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a41361fe-794a-4954-94d5-b783fb8f0249"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/74c3f5bf-71fd-4922-9425-2a8dab603042"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/231069e2-a4e0-41a1-aa49-2bcaae8057ee"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3858caf7-021c-499f-a6a5-d9cea21f4186"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b963019e-ee13-4940-8c50-110aa2403011"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b3b43e50-c4ee-44f6-98e8-9cfd83eef17e"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
        <th>Maps</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/2ae040ed-ba72-43b5-acc5-badb2eda216c"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/bf1d5835-f884-4df0-9a56-05638516475b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/1f46fde2-490d-4535-a47a-2dc2824870f8"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [x] Search for and selection of brand `okko` or `silpo` over Kyiv doesn't work on September maps. Works on Chernihiv oblast map from August
* * Android only. Works on iOS

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Search results for "7"</th>
        <th>7 evelen</th>
        <th>7-Eleven</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/c41238db-dc45-43ee-a00a-97480e619f4b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/65022c0d-4393-42c3-8ea2-9f29e5db35f0"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/user-attachments/assets/5ba701eb-0e28-405d-ae38-573cc81931a5"  width="300" height="auto"/> </td>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ] Two different `7 evelen` and `7-Eleven` over Kanto. Kanto map from 1.09.2025

**Comment by ivanPyrohivskyi** [comment]
Fixed "_Search for and selection of brand okko or silpo over Kyiv doesn't work on September maps. Works on Chernihiv oblast map from August_"
https://github.com/osmandapp/OsmAnd/commit/fb95dfd09e8b39be336d9f0b4d80fcc326fd8776

**Comment by Zirochkabila** [comment]
# Testing 2
`OsmAnd~ 5.2.0#6124m, Released: 2025-09-23`
`5240`

Tested on a map of Kyiv and Kyiv region (01.09.2025) — searching for and selecting the `okko` or `silpo` brand works and is identical to iOS (& WEB).

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/421d6ee3-a7a3-4491-b8ee-0328f5cf6fe4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/8bd678a9-482d-4f21-97af-d68cf34bf5d7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/7c7de212-4016-4a76-945d-d6273e9f02b9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/483e1184-a83e-4403-8613-fa53f41bfb06"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>
