### ISSUE TITLE
OSM Editing UI/Behavior issues

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/Osmand#6589]
**Review:**
- [x] Changing POI category on an existing object has no impact.(try to change the category by tapping on label icon)

**ToDo**
- [x] Changing POI category on an existing object has no impact.
- [x]  Do not allow the creation of the opening hours without a day.
- [x]  Selecting 00:00 in opening hours results in 0 being displayed.
- [x]  Transition to Advanced tab results in floating auto-suggestion field.
![image](https://user-images.githubusercontent.com/20681525/53555562-dcd3d680-3b4a-11e9-9cb2-47f99eb66e4c.png)
![image](https://user-images.githubusercontent.com/20681525/53555575-e2312100-3b4a-11e9-8c14-8842ef86024c.png)
