### ISSUE TITLE
[Feature request] Show AVNotes within favourites/POIs

### ISSUE THREAD

**Issue by MiMoHo** [osmandapp/Osmand#7125]
When media is taken by "Actions" tab within a saved POI or moved to the exact same location as a POI, it should appear **within** the saved favourites point. The current navigation is impractical as it requires the user to leave the POI, tap somewhere else on the map, before tapping on a bunch of items in order to choose between the POI and one or more photo(s) for example.
When the user deletes the POI, Osmand should ask to delete the images of the same location as well or keep them saved.

**Comment by dmpr0** [comment]
# ToDo

@dmpr0 Allow to Export / Share with Media attached to File .osf.zip 
@vshcherb Proposed changes in file names - Pattern: `[Type]_[YYYY-MM-DD]_[HH-mm-ss]_[Day].[ext]`

Examples:
* Save **GPS coordinates** and **Heading** into metadata

### Media item
<table>
  <thead>
    <tr>
      <th rowspan="2">Type</th>
      <th colspan="2">Small</th>
      <th colspan="2">Large</th>
    </tr>
    <tr>
      <th>Placeholder</th>
      <th>Preview</th>
      <th>Placeholder</th>
      <th>Preview</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><b>Audio</b></td>
      <td><img src="https://github.com/user-attachments/assets/a52f47f2-1ce7-4bf3-9b4c-de5f922f25b0" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/a52f47f2-1ce7-4bf3-9b4c-de5f922f25b0" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/84e762b1-8715-48f8-a59b-9c95eb027c93" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/04461f49-f686-439f-80a0-52619cfb5573" width="auto" /></td>
    </tr>
    <tr>
      <td><b>Photo</b></td>
      <td><img src="https://github.com/user-attachments/assets/ccd91332-f15a-4c1b-b298-42a171a64efa" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/18a510ae-a260-4c84-be0f-c09f6e37c7ac" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/185074b1-f5bd-43ce-8757-5abea9ec5141" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/2258d439-dfaa-4fba-a843-2b36ec4665c2" width="auto" /></td>
    </tr>
    <tr>
      <td><b>Video</b></td>
      <td><img src="https://github.com/user-attachments/assets/5eb45bac-779f-40d7-89ca-0e0de7970007" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/c8372daa-e9c8-4098-b342-5979dd09872d" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/de5865dd-c466-4d32-a27e-aca16b709514" width="auto" /></td>
      <td><img src="https://github.com/user-attachments/assets/6bb566af-5c88-48ee-926f-fbb8a3103c87" width="auto" /></td>
    </tr>
  </tbody>
</table>

**Placeholder**
- [x] Small size – `48x48 dp` (used in Media card on Add / Edit Favorite)
- [x] Big size – depend on screen
- [x] Show placeholder if preview is not available:
- - [x] Background – `activity_background_color`
- - [x] Photo icon – `ic_action_photo`
- - [x] Video icon – `ic_type_video`
- - [x] Audio icon – `ic_action_music_note`

**Preview**
- [x] Small size – `48x48 dp` (used in Media card on Add / Edit Favorite)
- [x] Big size – depend on screen
- [x] **Video, Large**
- - [x] Show dark 30% transparent background (to make duration visible)
- - [x] Show duration
- - [x] Show icon – `ic_action_play_in_shape`
- [x] Video, small `48x48 dp` 
- - [x] Show dark 30% transparent background (to make duration visible)
- - [x] Show icon – `ic_action_play_in_shape`
- [x] **Audio**
- - [x] Show icon icon – `ic_action_music_note`
- - [x] Show duration
- [x] **Photo**
- - [x] Show preview

# Add / Edit Favorite

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d82aa1db-b1ef-4cd3-8260-8ad404ab7e75"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/154cc7bc-06c6-46a4-98b4-c24d7383329c"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/4a2d925c-4018-42bd-8e92-6ea45c030c56"  width="150" height="auto"/> </td>
  </tr>
</table>  


- [x] Add new card **Media**
- [x] Card UI similar to Color, with horizontal scroll and Add button.
- [x] Placed as last item, below Shape

### Media card

<table style="width:100%">
  <tr>
    <th>Empty state</th>
    <th>With media</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/49aa9ffa-dfa7-4a54-bd7b-cd9b896d8204"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/0ecb01f8-23ca-4f78-9690-4c98105f5ee0"  width="300" height="auto"/> </td>
  </tr>
</table>

- [x] **Empty State** description – `Add photos, videos, or audio notes from your camera or library.`
- [x] **Add Button** – circular with a `+` icon (consistent with the **Color Card**).
- - [x] Show the **Add Menu** on tap.
- [x] **View All Button** – visible when at least one media item is added.
- - [x] Opens the **Gallery View** on tap.
- [x] Display a media preview in a horizontal strip with scrolling (similar to **Color Selection**).

**Media item preview:**

- [x] Size – `48x48 dp`

### Add Menu

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9124664c-4454-4b46-a75f-05dcaa4b84f5"  width="150" height="auto"/> </td>
  </tr>
</table>   

- [x] Show Add media menu after tap on Add button

**Actions:**
- [x] **Take a photo**
- - [x] Icon – `ic_action_photo_dark`
- - [x] Launch current take photo action
- [x] **Take a video note**
- - [x] Icon – `ic_action_video_dark`
- - [x] Launch current take video action
- [x] **Take an audio note**
- - [x] Icon – `ic_action_micro_dark`
- - [x] Launch current take audio action
- [x] **Choose from Gallery**
- - [x] Icon – `ic_action_photo_album`
- - [x] Launch system photo picker (permission needed)
- [x] **Choose from Files**
- - [x] Icon – `ic_action_group_list`
- - [x] Launch system file picker to choose an image
- - [x] Should be copied to OsmAnd Media folder?


# Gallery view, [Figma](https://www.figma.com/design/5013PasL9jCDFHGBgjx9lY/UI-Templates--AND-?node-id=1398-110860&m=dev)

<table style="width:100%">
  <tr>
    <th>Gallery, grid view</th>
    <th>Add menu</th>
    <th>Sort menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/11569ede-a8d4-40b1-9d2f-42ddb285be04"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/17f37716-5d36-44b9-9f6a-db00b8970b2e"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f5c33014-cdd6-4bb8-860a-d038b8b6edb9"  width="150" height="auto"/> </td>
  </tr>
</table>   

The **Gallery View** should be consistent across the **Add / Edit Favorite** screen and when opened via the **Context Menu**.

**AppBar**
- [x] Action – **Add**, icon – `ic_action_add_2`
-  - [x] Open **Add menu** on tap
- [x] Action **Edit**, icon – `ic_action_edit_outlined`
- - [x] Tap open **Selection Mode** UI

**Content**
- [x] Show all media in a grid (utilizing the existing layout from **Online Photos**).
- [x] Tapping on a **Media Item** opens the **Full Screen Gallery**.
- [x] The **Last Item** displays media statistics: **Photos** [quantity], **Videos** [quantity], **Audio** [quantity]. **Size** [#] MB.
- [x] Long tap on media item - open **Selection mode**

### Sorting
- [x] Show sorting bar
- [x] Show sorting menu on tap

**Sorting Menu**
- [x] Use system dropdown menu
- - [ ] By default set to **Last modified**
- [x] Sorting options:
- - [x] Nearest
- - [x] Last modified
- - [x] Name A – Z
- - [x] Name Z – A
- - [x] Newest date first
- - [x] Oldest date first
- - [x] Longest duration first
- - [x] Shorter duration first

# Selection mode, [Figma](https://www.figma.com/design/5013PasL9jCDFHGBgjx9lY/UI-Templates--AND-?node-id=1422-17656&m=dev)

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/33c31d4c-f5e2-4a3b-826c-742d686aa0e5"  width="150" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/6655bca0-c3f3-4ba1-a17c-a69ccf7b9333"  width="150" height="auto"/> </td>
  </tr>
</table>   

* Should be consistent across the **Add / Edit Favorite** screen and when opened via the **Context Menu** – **Gallery**.
* As a base use Selection mode UI implemented for Tracks and Favorites.
 
- [x] Show media items in list view
- [x] AppBar actions:
- - [x] Select all / Deselect all
- - [x] Actions

**Menu actions:**
- [x] **Export**, icon – `ic_action_export`
- - [x] Tap – 
- [x] **Delete**, icon – `ic_action_delete_outlined`
- - [x] Tap – Show confirmation alert

**Delete alert**
- [x] Title – Depend on media type and quantity, see in Strings details
- [x] Description – Depend on quantity:
- - [x] One – `This file will be permanently deleted from your device and removed from all linked favorites and tracks.`
- - [x] Plural – `These %d files will be permanently deleted from your device and removed from all linked favorites and tracks.`

<details>
    <summary>Strings</summary>
```

<resources>

    <plurals name="dialog_delete_photo_title">
        <item quantity="one">Delete photo?</item>
        <item quantity="other">Delete %d photos?</item>
    </plurals>

    <plurals name="dialog_delete_video_title">
        <item quantity="one">Delete video?</item>
        <item quantity="other">Delete %d videos?</item>
    </plurals>

    <plurals name="dialog_delete_audio_title">
        <item quantity="one">Delete audio note?</item>
        <item quantity="other">Delete %d audio notes?</item>
    </plurals>

    <plurals name="dialog_delete_items_title">
        <item quantity="one">Delete item?</item>
        <item quantity="other">Delete %d items?</item>
    </plurals>


    <plurals name="dialog_delete_media_message">
        <item quantity="one">This file will be permanently deleted from your device and removed from all linked favorites and tracks.</item>
        <item quantity="other">These %d files will be permanently deleted from your device and removed from all linked favorites and tracks.</item>
    </plurals>


    <string name="shared_string_delete">Delete</string>
    <string name="shared_string_cancel">Cancel</string>

</resources>
```

</details>  


**Media item:**
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/b2f37dcc-d598-46dc-ba66-c2ec0a03455f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/480c7f6e-a11e-44e3-a1f0-c22dafd0e0fd"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Placeholder / Preview size - 36x36dp
- [x] First line – File name
- [x] Second line: Date of creation and File size, `3 Dec 2025 • 1.2 MB`
- - [x] Add • Duration for Audio and Video items, `3 Dec 2025 • 1.2 MB • 03:45`

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7995m, released: 2026-06-17

**Severity**: 🟠 Major / **Priority**: 🔴 High

* [ ] 3. If the Favourite point is uploaded to the Cloud and then all data for that point is deleted, including Video, Audio and Photos, then after downloading from the Cloud, only items uploaded from the gallery or added via the file manager are displayed. Items created directly with OsmAnd are not displayed.

<details><summary>Details</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/82b2dff4-bbed-4efc-b9e6-892029bad1bc">
</details>

**Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [ ] 1. The interface menu is not displayed while recording video and audio notes, unlike when recording a photo note.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/8aa872a1-c53c-4bf7-a43b-5eca75e6d8c7"></video>
</details>

**Severity**: 🟡 Minor / **Priority**: 🟠 Normal

* [ ] 2. For files uploaded via the file manager or gallery, the date is not displayed.

<details><summary>Details</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/800b2885-712e-4591-958b-fc8474215b44">
</details>

**Comment by dmpr0** [comment]
## UI Review

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/821771bf-bc07-4671-9ea6-e91e979f16e1"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Take a video note – should open camera above Add favorite UI or any other UI


## Gallery view

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/482f6b2d-ce84-4044-9ef6-1e52e7d624a4"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [x] Add `48 dp` bottom padding below all content 

- - - - - -
 
### Sort bar

- [x] Set icon size to 18x18 dp
- [x] item height = 48 dpv

### Sort menu

- [x] Redo using compose?
- [x] Make reusable component with proper paddings
- [x] Add divider between sorting groups

## Selection mode


- [x] Show confirmation alert on Delete

## Voice recorder
We need a new bottom sheet for audio recordings because Android doesn't have any native intents as it does for photo or video.

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.4.0#8334m, released: 2026-07-20

**Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [x] 1. When adding an Audio file, the interface still does not appear.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Actual</th>
    <th>Expected</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/f03adf4d-3c22-483c-94b9-71b8c5374961" width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/0eb78afd-c93d-44f4-8771-0f3d01d1f37d" width="300" height="auto"/></td>
  </tr>
</table>
</details>

* [x] 2. Adding a video or photo does not work immediately while an audio file is being added. This may be related to point 1.

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/aa827481-d55f-4331-bc17-7585c71dea6a"></video>
</details>

**Comment by vshcherb** [comment]
Documentation: 
- where we describe migration process? 
- is new feature fully documented now?
