### ISSUE TITLE
New Track Menu: Extra actions for GPX (Name, Delete)

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd#8426]
# Review 

# ToDo 

Options in the GPX context menu:
- [x] Show on map
- [x] Appearance
- [x] Direction
- [x] Join gaps
- [x] Analyze on maps
- [x] Analyze by intervals
- [x] Share
- [x] Upload to OSM
- [x] Edit track
- [x] Rename
- [x] Change folder
- [x] Delete

![image](https://user-images.githubusercontent.com/1042025/104200371-dd1ca880-5428-11eb-8980-347cba68af60.png)
