### ISSUE TITLE
Favorites: allow to edit address (even set it empty)

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9055]
### Review
- [x]  Address doesn't saved if it enters manualy while adding favorite
- [x]  Context menu stop show up after adding.
- - - - - 
**Add favorite Screen**
- [x]  paddings sizes "Address" = 42pt > divider 1 pt > "Add description" = 42pt.
- [x]  "Delete address" icon = ic_action_trash_basket_16
- [x]  Align address text to the left side if it contains few lines of text.
- [x]  "Delete description" icon = ic_action_trash_basket_16
- [x]  Missed divider between "Address" and "Description buttons. 
- [x]  Delete address button doesn't work.
- [x]  Show delete adress icon in the address line 
![Снимок экрана 2020-09-11 в 16 12 22](https://user-images.githubusercontent.com/9365308/92929658-9488ba80-f449-11ea-9e5e-24767f284d4e.png)
- [x]  After the user tap on the text field, place the cursor at the end of the text.
- [x]  if the address in unknown > show "add address" button

**Context Menu:**
- [x] **Skip** Address text: the second line should start below the direction, without padding from the left screen side.
- [x] **Skip** first direction, then coma - address: "1.22 km, Bohdana Khmelnytskogo 1"

**Work in Progress** branch 9055
Review:
**Add favorite screen:**
- [x] By default show address as text line (don't open text field)
- [x] Check paddings (similar to Figma)
- [x] Check buttons height (similar to Figma) "Add address" and "Add description buttons height = 42dp.
- [x] Add divider between address and description button.
- [x] After taping on text filed, move cursor to the end.

**Context menu:**
- [x] Address text style regular
- [x] Can get two line.

- [x] Group name and group icon, horizontal align.
-------------------------
We must add a line with the address in the favorites context menu if the address was saved during creation or was in file.
favourites.gpx contains the address, but doesn't visible after creation.
```
<name>Point</name>
<extensions>
      <address>Alte Jakobstraße (Mitte) 128, Berlin</address>
      <icon>special_heart</icon>
      <background>circle</background>
      <color>#ff5020</color>
</extensions>
```
![Group 1](https://user-images.githubusercontent.com/9365308/82683170-2da48300-9c59-11ea-9cd1-e30df40a3266.png)

**ToDo:**
- [x] Show address in Context menu
- [x] Context menu use group color for "folder icon"
- [x] Multiply point menu: use group color for "folder icon"

**Second iteration**
- [x] Show button with address below name text field (location icon - address - delete button)
- [x] tapping on address will open text field with ability to change it, text field appears only after taping on address.
- [x] If user remove address, show "Add address" button instead.
- [x]  Change style of "Add description" button. 
Icons: ic_action_trash_basket_16, ic_action_description_16, ic_action_location_16

**Comment by androiddevkotlin** [comment]
Pull request fix only some minor bugs and ugly menu items after swap direction and distance but not entire problem.

**Comment by Chumva** [comment]
This should be fixed here - https://github.com/osmandapp/OsmAnd/pull/9814
