### ISSUE TITLE
Navigation: Suggest maps to download

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd#9144]
## Complex cases to be solved only with online routing

- [ ]  `Strömstad – Oslo`, OsmAnd propose to download `Västra Götaland County, Sweden` and `Viken, Norway`, but Viken doesn't contain a map for Oslo.
- [ ]  `Paris – Shanghai` propose to download unnecessary maps: Belgium, both Latvia, and Estonia.
- [ ] `Tunis, Tunisia – Tripoli, Libya` show toast "Could not calculate route. Ending point too far from nearest road."
- [ ] `Toronto, Canada – Erie, Pennsylvania, United States` don't propose to download needed regions, difficult case due to two lakes in the area.

## Review

- [x] Route from `Kyiv to Severodonetsk`, OsmAnd doesn't propose to download the map for "Luhansk oblast" where the city is located.
- [x] Route from `Kopenhagen to Malmö` only show toast "Could not calculate the route: Additional maps available".
- [x] Route from `Groningen to Amsterdam`, OsmAnd propose to download only Fevoland and Friesland.
## ToDo
If route goes thru or ends in the area without offline map, we need to suggest download needed region maps.
UI Places:
- Route preparation, after user select start and destination
- While user browse Public transport route and it go thru area without map

**Comment by scaidermern** [comment]
Isn't this the same as #5734 and #2525?

**Comment by dmpr0** [comment]
We need to:
• Show empty state if the route is required additional offline maps
• Taping "Download Maps" shows the bottom sheet with the list of needed maps (similar to the bottom sheets that we used to download a list of maps in downloads).

## UI, [Figma link](https://www.figma.com/file/kMPs78dpebmgBKcOWmGZUR/Route-Preparation?node-id=207%3A557)
![Снимок экрана 2021-03-11 в 16 04 11](https://user-images.githubusercontent.com/9365308/110799081-775f6800-8283-11eb-8f2d-2e68e75f361f.png)

**Comment by scaidermern** [comment]
How is this supposed to work? With the current nightly I just get a toast
"Could not calculate route.: Additional maps available".
I don't see a list with suggested maps do download.

**Comment by vshcherb** [comment]
Work in progress, The dialog appears if you have "Download maps" link. There were issues that it required internet and it was not correctly detecting region boundaries.

**Comment by scaidermern** [comment]
Works better now. 

But it ignores deactivated maps. Maps that are deactivated should get activated instead of downloading them again..

**Comment by scaidermern** [comment]
@vshcherb I guess this should be fixed.
