### ISSUE TITLE
Feature request dashed line for tracks

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd#9953]
The users ask to add a dashed line appearance for tracks

**Comment by mikehgentry** [comment]
This would mostly make #6224 moot if it applied to routes as well.

**Comment by dmpr0** [comment]
## ToDo
Add ability to select Line style for the track based on user PR https://github.com/osmandapp/OsmAnd/pull/25243

## Appearance – Track context menu
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1c5e1809-359c-40af-95b4-ec5ea1fa1c69"  width="300" height="auto"/> </td>
  </tr>
</table>   

### UI
- [x] Add new parameter **Line style** to the track Appearance menu
	- [x] Placement: below **Width**
- [x] Control: segmented button group — same component, sizing and behavior as **Width**
- [x] Current value shown on the right side of the row header (`Solid` / `Dashed` / `Dotted`)
	- [ ] Add `contentDescription` for each segment (icon-only buttons)

| Option | Behavior | Icon |
|---|---|---|
| **Solid** (default) | Continuous line, current behavior | `ic_action_line_style_solid` |
| **Dashed** | Dashed line | `ic_action_line_style_dashed` |
| **Dotted** | Dotted line | `ic_action_line_style_dotted` |


### Rendering
- [x] Dash pattern is defined in screen dp and scales with the line's stroke width:
      dash = `2 × strokeWidth`, gap = `1 × strokeWidth`
      dot  = `1 × strokeWidth`, gap = `1 × strokeWidth`
- [x] Applies to all width presets and to custom width from the slider
- [x] Pattern does not change with map zoom level (stroke width is already zoom-independent)

## Import / Export
- [x] Store selected value in new `<osmand:line_style>` tag inside `<extensions>` (values: `solid` / `dashed` / `dotted`)
- [x] Column in the tracks DB; DB takes priority over the file — same as color/width
- [x] Tracks without the tag fall back to `solid`

## Change / Default appearance

<table style="width:100%">
  <tr>
    <th>Change appearance</th>
    <th>Default appearance</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/999ee7ba-9599-4c29-baa7-7e0fe3a73eee"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/b06a78f3-6f93-47fe-ad79-825b6d359ea3"  width="200" height="auto"/> </td>
  </tr>
</table>  

- [x] Line style is available in both **Change appearance** and **Default appearance** dialogs
- [x] Supports **Unchanged** and **Original** states, same as Color and Width
      - **Unchanged** — each track keeps its current line style
      - **Original** — restores the value from the track file (`solid` if the tag is absent)

**Comment by rustyqt** [comment]
@dmpr0 the last unchecked item on your spec — "Add `contentDescription` for each segment (icon-only buttons)" — is actually implemented in #25852, the checkbox is just stale.

Both controllers set it when building the segments, in `getRadioItems()`:

```java
IconRadioItem item = new IconRadioItem(getIconId(style));
item.setTag(style);
item.setContentDescription(style.getDisplayName());
```

`LineStyleCardController` (Change / Default appearance) and `TrackLineStyleController` (single-track appearance) both do this, so each segment is labelled Solid / Dashed / Dotted for TalkBack. That makes the spec complete as far as I can tell.

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.5.0#8909m, released: 2026-09-23

| # | Test Scenario | Expected Result | Actual Result | Status |
| :--- | :--- | :--- | :--- | :---: |
| **TP-01** | Track Appearance UI & Accessibility | "Line style" row is placed below Width, switches styles, and supports TalkBack | UI components and TalkBack descriptions work properly | 🟢 **PASSED** |
| **TP-02** | Line Rendering (Dashed / Dotted) | Line pattern renders correctly on map and scales with stroke width and zoom | Renders properly according to defined proportions | 🟢 **PASSED** |
| **TP-03** | Change / Default Appearance States | Unchanged and Original states correctly preserve or reset line style values | Batch settings apply and reset as expected | 🟢 **PASSED** |
| **TP-04** | GPX Import / Export Parity | `<osmand:line_style>` tag is correctly written to GPX extensions and restored on import | GPX tag imports/exports seamlessly | 🟢 **PASSED** |
| **TP-05** | Direction Arrows Alignment | Direction arrows are synced and aligned properly with dashed/dotted line segments | Direction arrows render inside the gaps/spaces of the dashed line | 🟡 **FAILED (Minor)** |


<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/45211f4c-6988-4130-9708-55deceb70cc2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/eb7810e5-eb38-4d7f-aa40-2bca504f406b"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>
