### ISSUE TITLE
Favorites: Introduce subgroups

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd#9967]
It would be nice to have subgroups for favorites, the same way as we already have them for tracks. Currently with many favorites and favorite groups it becomes quite a mess.

**Comment by vshcherb** [comment]
Actually we are looking to simplify tracks structure somehow. Tracks subfolders are just folders and they have flat representation in My Places / Tracks.  Favorites are only grouped in the file. 

We plan to migrate Favorites to Single / Multiple Track file, so it will have easier On / Off functionality

**Comment by partiemann** [comment]
I would like to have subgroups, too.

**Comment by MiMoHo** [comment]
> It would be nice to have subgroups for favorites, the same way as we already have them for tracks. Currently with many favorites and favorite groups it becomes quite a mess.

Now, that I have many favorite groups, I would rather prefer to have folders than subgroups as I don't mean to split my groups further apart but group them together into a folder.

At this point, it would be great to also have a merging function for favorite groups, so when I decided to dissolve one group but keep the places, I would like to move them to another group while keeping their icon, not necessarily the color as discussed in #16507

**Comment by dmpr0** [comment]
# ToDo

# Backend
- [x] Read and write full path in `<type>` tag. Example `<type>Amsterdam/Museums</type>`
- - [x] Use a forward slash `/` as a delimiter without extra spaces

```
  <wpt lat="52.3743553" lon="4.8980303">
    <time>2026-04-23T15:51:06Z</time>
    <name>Oude Kerk</name>
    <type>Amsterdam/Museums</type>
    <extensions>
        ...
    </extensions>
  </wpt>

```

- [x] Sync with `osmand:points_groups `. Name attribute in the `<osmand:points_groups>` section must match this full path string exactly to apply group styles (colors/icons).
```
  <extensions>
    <osmand:points_groups>
      <group name="Amsterdam/Museums" color="#EECC22" icon="special_star" background="circle" pinned="false" />
    </osmand:points_groups>
  </extensions>

```

## Saving (File System)

- [x] **Physical Storage**: Store each subfolder hierarchy as a separate GPX file to maintain the current file-based sync logic.
- [x] **Filename Convention**: Use the existing `favorites-Root_%_Subfolder.gpx` pattern.
- [x] **Multi-level Hierarchy**: For deeper nesting, continue using the `_%_` delimiter in the filename.
    * *Example*: `favorites-Netherlands_%_Amsterdam_%_Museums.gpx`


# My Places

- [x] Show folders as a separate list at the top, the same as done in Tracks.
- [x] Sorting by name should apply separately to each list: folders and points.

## Merging

- [x] UI must consolidate separate GPX files into a single hierarchical structure if they share the same Root/Parent prefix.
* * Example:  two files `favorites-Amsterdam_%_Museums.gpx`and `favorites-Amsterdam_%_Transport.gpx`
* * Result in UI: A single root folder **Amsterdam** containing two subfolders: **Museums** and **Transport**.

 

## Folder menu
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/672da36f-8bb2-4c0e-a448-03b173bab891"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new item **Add folder**, icon – `ic_action_folder_add_outlined`
- - [x] Show **Add new category** screen on tap
- - [x] Rename to **Add new folder**
- [x] Add new option **Rename**, icon – `ic_action_edit_outlined`
- - [x] Show default dialog with TextField on tap

## Selection mode
Actions list needs to be dynamic to show context-aware actions: the ones that work with folders and ones that only work with favourite points.

## Move / Choose category
We have similar dialog for Tracks, where subfolders are supported/

- [x] **Flattened list**: Show all subfolders as individual selectable items.
- [x] **Full Path**: Display the complete breadcrumb path for each item (e.g., `Netherlands / Amsterdam / Museums`).
- [x] **Middle Truncation**: Apply the same truncation rules as in the Context Menu if the path is too long.

# Context menu / What's here menu
<table style="width:100%">
  <tr>
    <th>Short path</th>
    <th>Long path</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5a137785-7ced-4564-a1ff-5e1ca024bf06"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/25eceffb-1e75-4762-a7dc-dcf2b73ab279"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/74dca358-724a-4d83-be85-333bdb69560d"  width="200" height="auto"/> </td>
  </tr>
</table>   

**Context menu**

- [x] Show full path in Context menu. 
- - [x] Combine folders using a forward slash with spaces: Example: `Amsterdam / Museums`
- [x] Divider Styling: Use `text_color_tertiary_light/dark` specifically for the `/ `character.
- [x] Trim interim folders if line is too long, to leave only Parent and Last folder visible. Example: `Netherlands / … / … / Museums`
- [x] Hide intermediate folders to keep only the Root (first) and Current (last) folders visible,  If the full path exceeds the available screen width.
* * Example: `Netherlands / ... / Museums.`

**What's here menu**

- [x] Show full path on the second line

# Navigation: Set destination / Favorites list
 
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/984d8967-bf14-4b56-99a1-c15e509bc9ba"  width="200" height="auto"/> </td> 
<td><img src="https://github.com/user-attachments/assets/e4216868-a237-4f2a-9112-0bf4c6781894"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] Show only the **Last Folder** name to save space 

# Export
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/6839347f-caeb-414a-b328-372e9ca19a6b"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x] **Flattened list**: Show all subfolders as individual items for selection.
- [x] **Naming**: Use breadcrumb style from Context menu (e.g., `Netherlands / Museums`).


# Cloud Sync

- [x] **File-level sync**: Maintain current behaviour where each folder stores as a separate GPX file. 
- [x] **No UI changes**: Subfolder hierarchy should not affect the Cloud Sync interface or file list.

**Comment by Zirochkabila** [comment]
# Testing 1

> OsmAnd~ 5.4.0#7798m, released: 2026-05-21

**Severity**: 🟠 Major / **Priority**: 🟠 Normal

* [x] 1. If a folder has many subfolders or a long path, the name of the last folder is not displayed because it does not fit when selecting a folder from the folder list while adding a Favorite or during Export. **Suggestion:** Display the folder name/path the same way as when moving a Favorite or when it is shown in the context menu.

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
    <th>Actual - Add Favourites</th>
    <th>Actual - Export list</th>
    <th>Expected - Moving Favourites</th>
    <th>Expected - Context menu</th>
  </tr>
  <tr>
    <th><img src="https://github.com/user-attachments/assets/e8f0b041-43ac-4b23-b1cc-fe88d2d87eb6" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/da913eea-0a2f-45a9-b14c-542aa6c39cbd" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/0709c4cd-d3cb-4cf3-aacc-b3fd6bdae4e0" width="300" height="auto"/></th>
    <th><img src="https://github.com/user-attachments/assets/36a745fb-6521-4966-8677-597e2501b263" width="300" height="auto"/></th>
  </tr>
</table>
</details>

**Comment by Zirochkabila** [comment]
# Testing 2

> OsmAnd~ 5.4.0#7899m, released: 2026-06-08

If a folder has many subfolders or a long path, the name of the last folder is not displayed - **Fixed**

<details><summary>Details</summary>
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/58e62b13-89c9-4eb6-b0cd-5c73c246e127"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/d10c3867-22f7-403b-9ffb-6e0eb98536be"  width="300" height="auto"/> </th>
  </tr>
</table>  
</details>

**Comment by vshcherb** [comment]
# Additional

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/65d0a7fd-db26-43a7-8abf-d57e2b1dbc80"  width="300" height="auto"/> </td>
  </tr>
</table>   


Add ability to move folder between folder.

- [x] Move **Share** action into separate group
- [x] Place below **Change default appearance**
- [x] Add new action **Move**, icon – `ic_action_folder_move_outlined`
	- [x] Place below Share
	- [x] Open **Select folder** bottom sheet on tap
	- [x] Hide the selected folder and all its subfolders from the list
	- [x] Move all points and subfolders into the new place after selection
- [x] Remove **Add new folder** action from the folder menu

**Comment by Zirochkabila** [comment]
# Testing 3

> OsmAnd~ 5.4.0#8377m, released: 2026-07-22

Tested the “Share” and “Move” actions for folders (both parent folders and root folders) - **Implemented**
Root folders are imported while preserving the entire folder hierarchy.

[Archive 10.zip](https://github.com/user-attachments/files/30256874/Archive.10.zip)

**Comment by dmpr0** [comment]
## UI Review

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8959410b-299c-4d45-ac19-091a09950eaa"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/716e7b50-5699-453d-8cbc-e08b7638700b"  width="300" height="auto"/> </td>
  </tr>
</table>   

We need to fix issue with limited groups that doesn't have GPX file

**Comment by vshcherb** [comment]
Actions that don't require separate file:
- [x] Move
Should work recursively
- [x] Add to a track (all folders recursively)
- [x] Share should create a joint file with subfolders inside (type=)

Not needed to work recursively
- [x] Add to map markers.

**Comment by dmpr0** [comment]
## UI Review

- [x] Recursive Share of all subfolders.

**Comment by Zirochkabila** [comment]
# Testing 4

> OsmAnd~ 5.4.0#8538m, released: 2026-08-12

| Module | Status | Observed Behavior & Requirements Check |
| :--- | :--- | :--- |
| **01. Backend & GPX Parsing** | 🔴 **FAILED** | • **`<type>` Tag Formatting:** Internal GPX tag includes spaces around slash (`<type>Amsterdam / Museums</type>`), whereas backend spec mandates no spaces (`<type>Amsterdam/Museums</type>`).<br>• **Filename Delimiter:** Filename/metadata uses extra spaces around `_%_` (`favorites-Amsterdam _%_ Museums.gpx`), violating the `favorites-Root_%_Subfolder.gpx` convention. |
| **02. UI Breadcrumbs** | 🔴 **FAILED** | • **Inconsistent Slash Spacing:** Breadcrumbs display missing spaces on the first hierarchy level while retaining spaces on subsequent levels (`Ä/Amsterdam / Museums` instead of `Ä / Amsterdam / Museums`). |
| **03. My Places & Merging** | 🟢 **PASSED** | Merging of shared prefixes, folder list rendering, and folder menu options (**Add folder**, **Rename**) work as expected. |
| **04. Nav & Export Displays** | 🟢 **PASSED** | Middle truncation rules and path display across "What's here", Navigation, and Export function as expected. |
| **05. Mass Actions** | ⚠️ **PARTIAL FAIL** | • **Move (🔴 Bug):** Recursive moving works, but **resets/corrupts folder & subfolder sort order** after the move operation.<br>• **Add to track (🟢 Passed):** Recursively adds all nested points.<br>• **Share (🟢 Passed):** Correctly exports a single combined GPX file.<br>• **Add to markers (🟢 Passed):** Non-recursive point addition works as expected. |


- [ ] 1. Extra spaces in `<type>` tag and GPX filename delimiter

* **Expected:** Internal GPX tag `<type>Amsterdam/Museums</type>` (no spaces) and filename `favorites-Amsterdam_%_Museums.gpx`.
* **Actual:** Written internally as `<type>Amsterdam / Museums</type>` and `favorites-Amsterdam _%_ Museums.gpx`.

[Archive 13.zip](https://github.com/user-attachments/files/31014531/Archive.13.zip)

- [ ] 2. Inconsistent spacing in UI breadcrumbs (`Ä/Amsterdam / Museums`)

* **Expected:** Consistent ` / ` delimiter with spaces across all hierarchy levels (`Ä / Amsterdam / Museums`).
* **Actual:** The first hierarchy boundary lacks spaces around the slash (`Ä/Amsterdam`), while subsequent levels include spaces (` / Museums`).

<details><summary>Details</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://github.com/user-attachments/assets/14400ca5-3c0b-49b1-a7eb-38285cbb0c67">
</details> 

- [ ] 3. Folder sort order reset after recursive Move operation

* **Expected:** Preserving pre-existing folder and subfolder sort order when moved to a new destination category.
* **Actual:** Custom/applied sort order is lost or reset after executing the Move action.

**Comment by dmpr0** [comment]
@vshcherb 
- [ ] **Pin** and **Show on map** is missing too
